# kubernetes scheduling = filtering + scoring
# label a node
sysuser@ubuntuprod:~/git/ldk/k8s/17-affinity (master -> origin/master)$ kubectl label node/klc-worker disktype=ssd

# output
node/klc-worker labeled

# get nodes and show labels
sysuser@ubuntuprod:~/git/ldk/k8s/17-affinity (master -> origin/master)$ kubectl get nodes --show-labels | tee nodes-labels.txt

# output
NAME                STATUS   ROLES           AGE     VERSION   LABELS
klc-control-plane   Ready    control-plane   7d10h   v1.35.0   beta.kubernetes.io/arch=amd64,beta.kubernetes.io/os=linux,kubernetes.io/arch=amd64,kubernetes.io/hostname=klc-control-plane,kubernetes.io/os=linux,node-role.kubernetes.io/control-plane=,node.kubernetes.io/exclude-from-external-load-balancers=
klc-worker          Ready    <none>          7d10h   v1.35.0   beta.kubernetes.io/arch=amd64,beta.kubernetes.io/os=linux,disktype=ssd,kubernetes.io/arch=amd64,kubernetes.io/hostname=klc-worker,kubernetes.io/os=linux
klc-worker2         Ready    <none>          7d10h   v1.35.0   beta.kubernetes.io/arch=amd64,beta.kubernetes.io/os=linux,kubernetes.io/arch=amd64,kubernetes.io/hostname=klc-worker2,kubernetes.io/os=linux

# create pod yaml
sysuser@ubuntuprod:~/git/ldk/k8s/17-affinity (master -> origin/master)$ kubectl run node-affinity-pod --image=nginx --dry-run=client -o yaml | tee node-affinity-pod-base.yaml

# output
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: node-affinity-pod
  name: node-affinity-pod
spec:
  containers:
  - image: nginx
    name: node-affinity-pod
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}

sysuser@ubuntuprod:~/git/ldk/k8s/17-affinity (master -> origin/master)$ kubectl apply -f node-affinity-pod-base-modified.yaml && sleep 5 && echo "---PODS---" && kubectl get pods -o wide

# output
pod/node-affinity-pod created
---PODS---
NAME                READY   STATUS    RESTARTS   AGE   IP           NODE         NOMINATED NODE   READINESS GATES
node-affinity-pod   1/1     Running   0          23s   10.244.1.7   klc-worker   <none>           <none>

# force replace pod
sysuser@ubuntuprod:~/git/ldk/k8s/17-affinity (master -> origin/master)$ kubectl replace --force -f node-affinity-pod-base-modified2.yaml && sleep 5 && echo "---PODS---" && kubectl get pods -o wide

# output
pod "node-affinity-pod" deleted from myns namespace
pod/node-affinity-pod replaced
---PODS---
NAME                READY   STATUS    RESTARTS   AGE   IP       NODE     NOMINATED NODE   READINESS GATES
node-affinity-pod   0/1     Pending   0          5s    <none>   <none>   <none>           <none>

# create node label and get pods
sysuser@ubuntuprod:~/git/ldk/k8s/17-affinity (master -> origin/master)$ kubectl label node/klc-worker2 disktype=nvme && kubectl get nodes --show-labels | tee nodes-labels2.txt && sleep 5 && echo "---PODS---" && kubectl get pods -o wide

# output
node/klc-worker2 labeled
NAME                STATUS   ROLES           AGE     VERSION   LABELS
klc-control-plane   Ready    control-plane   7d10h   v1.35.0   beta.kubernetes.io/arch=amd64,beta.kubernetes.io/os=linux,kubernetes.io/arch=amd64,kubernetes.io/hostname=klc-control-plane,kubernetes.io/os=linux,node-role.kubernetes.io/control-plane=,node.kubernetes.io/exclude-from-external-load-balancers=
klc-worker          Ready    <none>          7d10h   v1.35.0   beta.kubernetes.io/arch=amd64,beta.kubernetes.io/os=linux,disktype=ssd,kubernetes.io/arch=amd64,kubernetes.io/hostname=klc-worker,kubernetes.io/os=linux
klc-worker2         Ready    <none>          7d10h   v1.35.0   beta.kubernetes.io/arch=amd64,beta.kubernetes.io/os=linux,disktype=nvme,kubernetes.io/arch=amd64,kubernetes.io/hostname=klc-worker2,kubernetes.io/os=linux
---PODS---
NAME                READY   STATUS    RESTARTS   AGE    IP           NODE          NOMINATED NODE   READINESS GATES
node-affinity-pod   1/1     Running   0          3m2s   10.244.2.8   klc-worker2   <none>           <none>

# create a new yaml file with preferred affinity and scoring and do a force replace
sysuser@ubuntuprod:~/git/ldk/k8s/17-affinity (master -> origin/master)$ kubectl replace --force -f node-affinity-pod-base-modified3.yaml && sleep 5 && echo "---PODS---" && kubectl get pods -o wide

# output
pod "node-affinity-pod" deleted from myns namespace
pod/node-affinity-pod replaced
---PODS---
NAME                READY   STATUS    RESTARTS   AGE   IP           NODE          NOMINATED NODE   READINESS GATES
node-affinity-pod   1/1     Running   0          5s    10.244.2.9   klc-worker2   <none>           <none>

# if we delete the label nvme from worker2 and then reapply, the pod will land on worker1 due to the weight
sysuser@ubuntuprod:~/git/ldk/k8s/17-affinity (master -> origin/master)$ kubectl label node/klc-worker2 disktype- && kubectl get nodes --show-labels | tee nodes-labels3.txt && kubectl replace --force -f node-affinity-pod-base-modified3.yaml && sleep 5 && echo "---PODS---" && kubectl get pods -o wide

# output
node/klc-worker2 unlabeled
NAME                STATUS   ROLES           AGE     VERSION   LABELS
klc-control-plane   Ready    control-plane   7d11h   v1.35.0   beta.kubernetes.io/arch=amd64,beta.kubernetes.io/os=linux,kubernetes.io/arch=amd64,kubernetes.io/hostname=klc-control-plane,kubernetes.io/os=linux,node-role.kubernetes.io/control-plane=,node.kubernetes.io/exclude-from-external-load-balancers=
klc-worker          Ready    <none>          7d11h   v1.35.0   beta.kubernetes.io/arch=amd64,beta.kubernetes.io/os=linux,disktype=ssd,kubernetes.io/arch=amd64,kubernetes.io/hostname=klc-worker,kubernetes.io/os=linux
klc-worker2         Ready    <none>          7d11h   v1.35.0   beta.kubernetes.io/arch=amd64,beta.kubernetes.io/os=linux,kubernetes.io/arch=amd64,kubernetes.io/hostname=klc-worker2,kubernetes.io/os=linux
pod "node-affinity-pod" deleted from myns namespace
pod/node-affinity-pod replaced
---PODS---
NAME                READY   STATUS    RESTARTS   AGE   IP           NODE         NOMINATED NODE   READINESS GATES
node-affinity-pod   1/1     Running   0          5s    10.244.1.8   klc-worker   <none>           <none>

# INTER POD AFFITNITY and ANTI POD AFFINITY

# manually create pod-affinity-nginxdep-base.yaml apply it and get pods
sysuser@ubuntuprod:~/git/ldk/k8s/17-affinity (master -> origin/master)$ kubectl apply -f pod-affinity-nginxdep-base.yaml && sleep 3 && echo "---POD---" && kubectl get pods -o wide

# output
deployment.apps/nginxdep created
---POD---
NAME                        READY   STATUS    RESTARTS   AGE   IP       NODE     NOMINATED NODE   READINESS GATES
nginxdep-6fb5488967-4zcc5   0/1     Pending   0          3s    <none>   <none>   <none>           <none>

# create a redis deployment with a role matching the affinity of nginxdep and get pods
sysuser@ubuntuprod:~/git/ldk/k8s/17-affinity (master -> origin/master)$ kubectl apply -f redis-base.yaml && sleep 5 && echo "---DEPLOYMENTS---" && kubectl get deployment -o wide && echo "---PODS---" && kubectl get pods -o wide

# output
deployment.apps/redisdep created
---DEPLOYMENTS---
NAME       READY   UP-TO-DATE   AVAILABLE   AGE     CONTAINERS   IMAGES   SELECTOR
nginxdep   0/1     1            0           9m11s   nginxdep     nginx    app=nginxdep
redisdep   1/1     1            1           5s      redisdep     redis    app=redisdep
---PODS---
NAME                        READY   STATUS    RESTARTS   AGE     IP            NODE         NOMINATED NODE   READINESS GATES
nginxdep-6fb5488967-4zcc5   1/1     Running   0          9m31s   10.244.1.10   klc-worker   <none>           <none>
redisdep-868f956b84-kszsl   1/1     Running   0          25s     10.244.1.9    klc-worker   <none>           <none>

# the following file can be used to apply both deployments
sysuser@ubuntuprod:~/git/ldk/k8s/17-affinity (master -> origin/master)$ kubectl replace --force -f combined-redis-nginx-dep-base.yaml 

# cordon klc-worker to make the pods schedule on klc-worker2
sysuser@ubuntuprod:~/git/ldk/k8s/17-affinity (master -> origin/master)$ kubectl cordon klc-worker && kubectl replace --force -f combined-redis-nginx-dep-base.yaml && sleep 10 && echo "---DEPLOYMENTS---" && kubectl get deployment -o wide && echo "---PODS---" && kubectl get pods -o wide
node/klc-worker cordoned
deployment.apps "redisdep" deleted from myns namespace
deployment.apps "nginxdep" deleted from myns namespace
deployment.apps/redisdep replaced
deployment.apps/nginxdep replaced
---DEPLOYMENTS---
NAME       READY   UP-TO-DATE   AVAILABLE   AGE   CONTAINERS   IMAGES   SELECTOR
nginxdep   1/1     1            1           10s   nginxdep     nginx    app=nginxdep
redisdep   1/1     1            1           10s   redisdep     redis    app=redisdep
---PODS---
NAME                        READY   STATUS    RESTARTS   AGE   IP            NODE          NOMINATED NODE   READINESS GATES
nginxdep-6fb5488967-8w9st   1/1     Running   0          10s   10.244.2.16   klc-worker2   <none>           <none>
redisdep-868f956b84-tn9df   1/1     Running   0          10s   10.244.2.15   klc-worker2   <none>           <none>

# uncordon klc-worker
sysuser@ubuntuprod:~/git/ldk/k8s/17-affinity (master -> origin/master)$ kubectl uncordon klc-worker

# output
node/klc-worker uncordoned

# create combined-redis-nginx-dep-antiaffinity.yaml and set podAntiAffinity. pods are always on different nodes.
sysuser@ubuntuprod:~/git/ldk/k8s/17-affinity (master -> origin/master)$ kubectl replace --force -f combined-redis-nginx-dep-antiaffinity.yaml && sleep 10 && echo "---DEPLOYMENTS---" && kubectl get deployment -o wide && echo "---PODS---" && kubectl get pods -o wide
deployment.apps "redisdep" deleted from myns namespace
deployment.apps "nginxdep" deleted from myns namespace
deployment.apps/redisdep replaced
deployment.apps/nginxdep replaced
---DEPLOYMENTS---
NAME       READY   UP-TO-DATE   AVAILABLE   AGE   CONTAINERS   IMAGES   SELECTOR
nginxdep   1/1     1            1           10s   nginxdep     nginx    app=nginxdep
redisdep   1/1     1            1           10s   redisdep     redis    app=redisdep
---PODS---
NAME                        READY   STATUS    RESTARTS   AGE   IP            NODE          NOMINATED NODE   READINESS GATES
nginxdep-8548c66669-xq7f6   1/1     Running   0          10s   10.244.1.15   klc-worker    <none>           <none>
redisdep-868f956b84-mv4mc   1/1     Running   0          10s   10.244.2.19   klc-worker2   <none>           <none>
