apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: redisdep
spec:
  selector:
    matchLabels:
      app: redisdep
  replicas: 1
  template: 
    metadata:
      labels:
        app: redisdep
        run: redisdep-backend
        role: backend
    spec:
      containers:
      - name: redisdep
        image: redis
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: nginxdep
spec:
  selector:
    matchLabels:
      app: nginxdep
  replicas: 1
  template: 
    metadata:
      labels:
        app: nginxdep
        run: nginxdep-frontend
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: role
                operator: In
                values:
                - backend
            topologyKey: "kubernetes.io/hostname"
      containers:
      - name: nginxdep
        image: nginx
        ports:
        - containerPort: 80