apiVersion: v1
kind: Pod
metadata:
  labels:
    run: node-affinity-pod
  name: node-affinity-pod
spec:
  containers:
  - image: nginx
    name: node-affinity-pod
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
