# create a deployment of nginx
sysuser@ubuntuprod:~/git/ldk/k8s/11-annotations (master -> origin/master)$ kubectl create deployment nginxdep --image=nginx --dry-run=client -o yaml | tee nginxdep.yaml nginxannotations.yaml

# output
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginxdep
  name: nginxdep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginxdep
  strategy: {}
  template:
    metadata:
      labels:
        app: nginxdep
    spec:
      containers:
      - image: nginx
        name: nginx
        resources: {}
status: {}

# edit annotations yaml and add annotations. 
sysuser@ubuntuprod:~/git/ldk/k8s/11-annotations (master -> origin/master)$ kubectl apply -f nginxannotations.yaml && kubectl describe deployment/nginxdep

# output
deployment.apps/nginxdep created
Name:                   nginxdep
Namespace:              myns
CreationTimestamp:      Tue, 23 Jun 2026 05:49:28 -0500
Labels:                 app=nginxdep
Annotations:            company.org/owner: platform-team
                        company.org/ticket: OPS-1234
                        deployment.kubernetes.io/revision: 1
Selector:               app=nginxdep
Replicas:               1 desired | 1 updated | 1 total | 0 available | 1 unavailable
StrategyType:           RollingUpdate
MinReadySeconds:        0
RollingUpdateStrategy:  25% max unavailable, 25% max surge
Pod Template:
  Labels:       app=nginxdep
  Annotations:  company.org/note: This is a pod annotation
  Containers:
   nginx:
    Image:         nginx
    Port:          <none>
    Host Port:     <none>
    Environment:   <none>
    Mounts:        <none>
  Volumes:         <none>
  Node-Selectors:  <none>
  Tolerations:     <none>
Conditions:
  Type           Status  Reason
  ----           ------  ------
  Available      False   MinimumReplicasUnavailable
  Progressing    True    ReplicaSetUpdated
OldReplicaSets:  <none>
NewReplicaSet:   nginxdep-84b7c587db (1/1 replicas created)
Events:
  Type    Reason             Age   From                   Message
  ----    ------             ----  ----                   -------
  Normal  ScalingReplicaSet  0s    deployment-controller  Scaled up replica set nginxdep-84b7c587db from 0 to 1


# get pods
sysuser@ubuntuprod:~/git/ldk/k8s/11-annotations (master -> origin/master)$ kubectl get pods -o wide

# output
NAME                        READY   STATUS    RESTARTS   AGE   IP             NODE         NOMINATED NODE   READINESS GATES
nginxdep-84b7c587db-gzq7p   1/1     Running   0          34s   10.244.1.149   klc-worker   <none>           <none>


# describe the pod
sysuser@ubuntuprod:~/git/ldk/k8s/11-annotations (master -> origin/master)$ kubectl describe pod/nginxdep-84b7c587db-gzq7p

# output
Name:             nginxdep-84b7c587db-gzq7p
Namespace:        myns
Priority:         0
Service Account:  default
Node:             klc-worker/172.18.0.2
Start Time:       Tue, 23 Jun 2026 05:49:28 -0500
Labels:           app=nginxdep
                  pod-template-hash=84b7c587db
Annotations:      company.org/note: This is a pod annotation
Status:           Running
IP:               10.244.1.149
IPs:
  IP:           10.244.1.149
Controlled By:  ReplicaSet/nginxdep-84b7c587db
Containers:
  nginx:
    Container ID:   containerd://ad4f0196470166088f4bdc39a820dae066a4c10793d0d2d93ba6691b6c38d7e0
    Image:          nginx
    Image ID:       docker.io/library/nginx@sha256:42f2d24ae18df9b5251d1cc45548085656d2335e9338fd150a24e415462d151f
    Port:           <none>
    Host Port:      <none>
    State:          Running
      Started:      Tue, 23 Jun 2026 05:49:30 -0500
    Ready:          True
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-qdcjs (ro)
Conditions:
  Type                        Status
  PodReadyToStartContainers   True 
  Initialized                 True 
  Ready                       True 
  ContainersReady             True 
  PodScheduled                True 
Volumes:
  kube-api-access-qdcjs:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    Optional:                false
    DownwardAPI:             true
QoS Class:                   BestEffort
Node-Selectors:              <none>
Tolerations:                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type    Reason     Age   From               Message
  ----    ------     ----  ----               -------
  Normal  Scheduled  67s   default-scheduler  Successfully assigned myns/nginxdep-84b7c587db-gzq7p to klc-worker
  Normal  Pulling    66s   kubelet            spec.containers{nginx}: Pulling image "nginx"
  Normal  Pulled     65s   kubelet            spec.containers{nginx}: Successfully pulled image "nginx" in 1.039s (1.039s including waiting). Image size: 63132582 bytes.
  Normal  Created    65s   kubelet            spec.containers{nginx}: Container created
  Normal  Started    65s   kubelet            spec.containers{nginx}: Container started


# make a change to the annotations file and apply it. this will get a new replica set 
sysuser@ubuntuprod:~/git/ldk/k8s/11-annotations (master -> origin/master)$ kubectl apply -f nginxannotations-modified.yaml && kubectl rollout status deployment/nginxdep && kubectl get pods -o wide

# output
deployment.apps/nginxdep configured
Waiting for deployment "nginxdep" rollout to finish: 1 old replicas are pending termination...
Waiting for deployment "nginxdep" rollout to finish: 1 old replicas are pending termination...
deployment "nginxdep" successfully rolled out
NAME                        READY   STATUS        RESTARTS   AGE     IP             NODE          NOMINATED NODE   READINESS GATES
nginxdep-69744d7994-86jct   1/1     Running       0          2s      10.244.2.106   klc-worker2   <none>           <none>
nginxdep-84b7c587db-gzq7p   1/1     Terminating   0          2m51s   10.244.1.149   klc-worker    <none>           <none>
