apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginxwebdep
  name: nginxwebdep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginxwebdep
  strategy: {}
  template:
    metadata:
      labels:
        app: nginxwebdep
    spec:
      containers:
      - image: nginx
        name: nginx
        ports:
        - containerPort: 80
        resources: {}
status: {}
