# create the volume
docker volume create portainer_data

# create the container
docker run -d \
  -p 8000:8000 \
  -p 9443:9443 \
  -p 9090:9090 \
  -p 9000:9000 \
  --name portainer \
  --restart=always \
  -v /var/run/docker.sock:/var/run/docker.sock \
  -v portainer_data:/data \
  portainer/portainer-ce:sts

# do a docker pull of portainer
docker pull portainer/portainer-ce:latest
docker pull portainer/portainer-ce:sts

# stop and remove the container
docker stop portainer && docker rm portainer
