# simplifies management of kubernetes applications. 

# we will create flappy app directory using helm
sysuser@ubuntudev:~/git/ldk/k8s/27-helm (master -> origin/master)$ helm create flappy-app

# output
Creating flappy-app

# directory structure
sysuser@ubuntudev:~/git/ldk/k8s/27-helm (master -> origin/master)$ tree

# output
.
├── 27-helm-commands.ini
└── flappy-app
    ├── charts
    ├── Chart.yaml
    ├── templates
    │   ├── deployment.yaml
    │   ├── _helpers.tpl
    │   ├── hpa.yaml
    │   ├── httproute.yaml
    │   ├── ingress.yaml
    │   ├── NOTES.txt
    │   ├── serviceaccount.yaml
    │   ├── service.yaml
    │   └── tests
    │       └── test-connection.yaml
    └── values.yaml

5 directories, 12 files

# package the application
sysuser@ubuntudev:~/git/ldk/k8s/27-helm/flappy-app (master -> origin/master)$ helm package .

# output
Successfully packaged chart and saved it to: /home/sysuser/git/ldk/k8s/27-helm/flappy-app/flappy-app-0.1.0.tgz

# install this application. follow the instructions in the notes to serve this game locally. 
sysuser@ubuntudev:~/git/ldk/k8s/27-helm/flappy-app (master -> origin/master)$ helm install flappy-app /home/sysuser/git/ldk/k8s/27-helm/flappy-app/flappy-app-0.1.0.tgz

# output
NAME: flappy-app
LAST DEPLOYED: Thu Jul  9 18:54:56 2026
NAMESPACE: default
STATUS: deployed
REVISION: 1
DESCRIPTION: Install complete
NOTES:
1. Get the application URL by running these commands:
  export POD_NAME=$(kubectl get pods --namespace default -l "app.kubernetes.io/name=flappy-app,app.kubernetes.io/instance=flappy-app" -o jsonpath="{.items[0].metadata.name}")
  export CONTAINER_PORT=$(kubectl get pod --namespace default $POD_NAME -o jsonpath="{.spec.containers[0].ports[0].containerPort}")
  echo "Visit http://127.0.0.1:8080 to use your application"
  kubectl --namespace default port-forward $POD_NAME 8080:$CONTAINER_PORT

# get a list of all the charts installed
sysuser@ubuntudev:~/git/ldk/k8s/27-helm/flappy-app (master -> origin/master)$ helm list
NAME      	NAMESPACE	REVISION	UPDATED                                	STATUS  	CHART           	APP VERSION
flappy-app	default  	1       	2026-07-09 18:54:56.385563461 -0500 CDT	deployed	flappy-app-0.1.0	1.16.0     

# uninstall this game
sysuser@ubuntudev:~/git/ldk/k8s/27-helm/flappy-app (master -> origin/master)$ helm uninstall flappy-app

# output
release "flappy-app" uninstalled