# workload api objects used to manage stateful applications
# statefulsets have no concept of replicaset
# valuable when stable persistent storage, stable/unique network identifiers, ordered graceful deployment, ordered automated rolling updates
# cannot create a statefulset via cli. have to use a deployment and make changes manually to the yaml

# create a deployment and modify it
sysuser@ubuntuprod:~/git/ldk/k8s/19-statefulsets (master -> origin/master)$ kubectl create deployment nginxsts --image=nginx --replicas=3 --dry-run=client -o yaml | tee nginxsts.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginxsts
  name: nginxsts
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginxsts
  strategy: {}
  template:
    metadata:
      labels:
        app: nginxsts
    spec:
      containers:
      - image: nginx
        name: nginx
        resources: {}
status: {}

# apply and get pods, statefulset. no replicaset. pods have statefulset name and an incremental number
sysuser@ubuntuprod:~/git/ldk/k8s/19-statefulsets (master -> origin/master)$ kubectl apply -f nginxsts.yaml && sleep 10 && echo "---STS---" && kubectl get statefulset -o wide && echo "---PODS---" && kubectl get pods -o wide

# output
statefulset.apps/nginxsts created
---STS---
NAME       READY   AGE   CONTAINERS   IMAGES
nginxsts   3/3     10s   nginx        nginx
---PODS---
NAME         READY   STATUS    RESTARTS   AGE   IP            NODE          NOMINATED NODE   READINESS GATES
nginxsts-0   1/1     Running   0          10s   10.244.2.5    klc-worker2   <none>           <none>
nginxsts-1   1/1     Running   0          8s    10.244.1.13   klc-worker    <none>           <none>
nginxsts-2   1/1     Running   0          6s    10.244.1.14   klc-worker    <none>           <none>

# create a headless cluster ip service. use the same name as service name in statefulset spec
sysuser@ubuntuprod:~/git/ldk/k8s/19-statefulsets (master -> origin/master)$ kubectl create service clusterip --clusterip=None nginxsts --dry-run=client -o yaml | tee headlesscip.yaml

# output
apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginxsts
  name: nginxsts
spec:
  clusterIP: None
  selector:
    app: nginxsts
  type: ClusterIP
status:
  loadBalancer: {}

# apply the file and get svc, endpoints
sysuser@ubuntuprod:~/git/ldk/k8s/19-statefulsets (master -> origin/master)$ kubectl apply -f headlesscip.yaml && kubectl get svc -o wide && kubectl get EndpointSlices -o wide

# output
service/nginxsts created
NAME       TYPE        CLUSTER-IP   EXTERNAL-IP   PORT(S)   AGE   SELECTOR
nginxsts   ClusterIP   None         <none>        <none>    0s    app=nginxsts
NAME             ADDRESSTYPE   PORTS     ENDPOINTS                            AGE
nginxsts-2rj6n   IPv4          <unset>   10.244.1.14,10.244.2.5,10.244.1.13   0s


sysuser@ubuntuprod:~/git/ldk/k8s/19-statefulsets (master -> origin/master)$ kubectl get EndpointSlices/nginxsts-2rj6n -o yaml | tee nginxsts-endpointslices.yaml
addressType: IPv4
apiVersion: discovery.k8s.io/v1
endpoints:
- addresses:
  - 10.244.1.11
  conditions:
    ready: true
    serving: true
    terminating: false
  nodeName: klc-worker
  targetRef:
    kind: Pod
    name: nginxsts-0
    namespace: myns
    uid: 0036a35b-ef34-4aa2-afaf-7c488a94eae6
- addresses:
  - 10.244.2.3
  conditions:
    ready: true
    serving: true
    terminating: false
  nodeName: klc-worker2
  targetRef:
    kind: Pod
    name: nginxsts-1
    namespace: myns
    uid: f8ddffe0-06dc-4854-bf34-f5ae73fc1b69
- addresses:
  - 10.244.1.12
  conditions:
    ready: true
    serving: true
    terminating: false
  nodeName: klc-worker
  targetRef:
    kind: Pod
    name: nginxsts-2
    namespace: myns
    uid: 77fbf4a7-7331-4b59-8f27-11a87d8b834d
kind: EndpointSlice
metadata:
  creationTimestamp: "2026-06-28T17:01:11Z"
  generateName: nginxsts-
  generation: 1
  labels:
    app: nginxsts
    endpointslice.kubernetes.io/managed-by: endpointslice-controller.k8s.io
    kubernetes.io/service-name: nginxsts
    service.kubernetes.io/headless: ""
  name: nginxsts-9w5z2
  namespace: myns
  ownerReferences:
  - apiVersion: v1
    blockOwnerDeletion: true
    controller: true
    kind: Service
    name: nginxsts
    uid: 6731294a-a561-496a-afe7-2386ec570667
  resourceVersion: "945498"
  uid: e3b011a7-1082-43ba-b637-9619ecdc1ece
ports: null

# stable network id has the following format: <hostname>.<servicename>.<namespace>.svc.cluster.local
# create a curlpod
sysuser@ubuntuprod:~/git/ldk/k8s/19-statefulsets (master -> origin/master)$ kubectl run -it --rm curlpod --image=curlimages/curl --restart=Never -- sh

# output
All commands and output from this session will be recorded in container logs, including credentials and sensitive information passed through the command prompt.
If you don't see a command prompt, try pressing enter.
~ $ 

# run from inside curlpod
~ $ curl nginxsts-0.nginxsts.myns.svc.cluster.local

# output
<!DOCTYPE html>
<html>
<head>
<title>Welcome to nginx!</title>
<style>
html { color-scheme: light dark; }
body { width: 35em; margin: 0 auto;
font-family: Tahoma, Verdana, Arial, sans-serif; }
</style>
</head>
<body>
<h1>Welcome to nginx!</h1>
<p>If you see this page, nginx is successfully installed and working.
Further configuration is required for the web server, reverse proxy, 
API gateway, load balancer, content cache, or other features.</p>

<p>For online documentation and support please refer to
<a href="https://nginx.org/">nginx.org</a>.<br/>
To engage with the community please visit
<a href="https://community.nginx.org/">community.nginx.org</a>.<br/>
For enterprise grade support, professional services, additional 
security features and capabilities please refer to
<a href="https://f5.com/nginx">f5.com/nginx</a>.</p>

<p><em>Thank you for using nginx.</em></p>
</body>
</html>
~ $ 

# get the yaml spec of the stateful set and save it to a file. this is for reference purposes. 
sysuser@ubuntuprod:~/git/ldk/k8s/19-statefulsets (master -> origin/master)$ kubectl get statefulset/nginxsts -o yaml | tee statefulset-nginxsts.yaml

# output
apiVersion: apps/v1
kind: StatefulSet
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"StatefulSet","metadata":{"annotations":{},"labels":{"app":"nginxsts"},"name":"nginxsts","namespace":"myns"},"spec":{"replicas":3,"selector":{"matchLabels":{"app":"nginxsts"}},"serviceName":"nginxsts","template":{"metadata":{"labels":{"app":"nginxsts"}},"spec":{"containers":[{"image":"nginx","name":"nginx"}]}}}}
  creationTimestamp: "2026-06-28T17:21:43Z"
  generation: 1
  labels:
    app: nginxsts
  name: nginxsts
  namespace: myns
  resourceVersion: "947441"
  uid: c1560d34-4657-4769-b55b-eb555ea82ea9
spec:
  persistentVolumeClaimRetentionPolicy:
    whenDeleted: Retain
    whenScaled: Retain
  podManagementPolicy: OrderedReady
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: nginxsts
  serviceName: nginxsts
  template:
    metadata:
      labels:
        app: nginxsts
    spec:
      containers:
      - image: nginx
        imagePullPolicy: Always
        name: nginx
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 1
      partition: 0
    type: RollingUpdate
status:
  availableReplicas: 3
  collisionCount: 0
  currentReplicas: 3
  currentRevision: nginxsts-644b8794c5
  observedGeneration: 1
  readyReplicas: 3
  replicas: 3
  updateRevision: nginxsts-644b8794c5
  updatedReplicas: 3

# create a new stateful set file and change the partition in that file and apply it
sysuser@ubuntuprod:~/git/ldk/k8s/19-statefulsets (master -> origin/master)$ kubectl apply -f nginxsts-partition-update.yaml && sleep 2 && kubectl get statefulset/nginxsts -o yaml | tee statefulset-nginxsts-updated-partition.yaml

# output
statefulset.apps/nginxsts configured
apiVersion: apps/v1
kind: StatefulSet
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"StatefulSet","metadata":{"annotations":{},"labels":{"app":"nginxsts"},"name":"nginxsts","namespace":"myns"},"spec":{"replicas":3,"selector":{"matchLabels":{"app":"nginxsts"}},"serviceName":"nginxsts","template":{"metadata":{"labels":{"app":"nginxsts"}},"spec":{"containers":[{"image":"nginx","name":"nginx"}]}},"updateStrategy":{"rollingUpdate":{"partition":2},"type":"RollingUpdate"}}}
  creationTimestamp: "2026-06-28T17:21:43Z"
  generation: 2
  labels:
    app: nginxsts
  name: nginxsts
  namespace: myns
  resourceVersion: "948455"
  uid: c1560d34-4657-4769-b55b-eb555ea82ea9
spec:
  persistentVolumeClaimRetentionPolicy:
    whenDeleted: Retain
    whenScaled: Retain
  podManagementPolicy: OrderedReady
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: nginxsts
  serviceName: nginxsts
  template:
    metadata:
      labels:
        app: nginxsts
    spec:
      containers:
      - image: nginx
        imagePullPolicy: Always
        name: nginx
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 1
      partition: 2
    type: RollingUpdate
status:
  availableReplicas: 3
  collisionCount: 0
  currentReplicas: 3
  currentRevision: nginxsts-644b8794c5
  observedGeneration: 2
  readyReplicas: 3
  replicas: 3
  updateRevision: nginxsts-644b8794c5
  updatedReplicas: 3

# we will change the image to nginx:alpine and apply
sysuser@ubuntuprod:~/git/ldk/k8s/19-statefulsets (master -> origin/master)$ kubectl apply -f nginxsts-partition-image-update.yaml && kubectl rollout status statefulset/nginxsts

# output
statefulset.apps/nginxsts configured
Waiting for partitioned roll out to finish: 0 out of 1 new pods have been updated...
Waiting for 1 pods to be ready...
Waiting for 1 pods to be ready...
Waiting for 1 pods to be ready...
partitioned roll out complete: 1 new pods have been updated...

# check image of the pods
sysuser@ubuntuprod:~/git/ldk/k8s/19-statefulsets (master -> origin/master)$ kubectl get pods -o yaml > nginxsts-pods.yaml && kubectl get pods -o yaml | grep image:

# output
    - image: nginx
      image: docker.io/library/nginx:latest
    - image: nginx
      image: docker.io/library/nginx:latest
    - image: nginx:alpine
      image: docker.io/library/nginx:alpine

# add volumeclaim to the statefulset spec yaml
sysuser@ubuntuprod:~/git/ldk/k8s/19-statefulsets (master -> origin/master)$ kubectl delete statefulset/nginxsts && kubectl apply -f nginxsts-partition-volumeclaim.yaml && sleep 20 && echo "---PODS---" && kubectl get pods -o wide && echo "---PVC---" && kubectl get pvc -o wide

# output
statefulset.apps "nginxsts" deleted from myns namespace
statefulset.apps/nginxsts created
---PODS---
NAME         READY   STATUS    RESTARTS   AGE   IP            NODE          NOMINATED NODE   READINESS GATES
nginxsts-0   1/1     Running   0          20s   10.244.1.33   klc-worker    <none>           <none>
nginxsts-1   1/1     Running   0          14s   10.244.2.16   klc-worker2   <none>           <none>
nginxsts-2   1/1     Running   0          9s    10.244.1.35   klc-worker    <none>           <none>
---PVC---
NAME                             STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   VOLUMEATTRIBUTESCLASS   AGE   VOLUMEMODE
nginxstsvolumeclaim-nginxsts-0   Bound    pvc-5f5d1be4-9c64-42d2-96a4-91e3f30d89b6   1Gi        RWO            standard       <unset>                 20s   Filesystem
nginxstsvolumeclaim-nginxsts-1   Bound    pvc-9e8a826b-8368-4b40-bb4b-b2965e8b7138   1Gi        RWO            standard       <unset>                 14s   Filesystem
nginxstsvolumeclaim-nginxsts-2   Bound    pvc-9d10d360-391a-4fea-972f-3c0818df1046   1Gi        RWO            standard       <unset>                 9s    Filesystem

# get pv
sysuser@ubuntuprod:~/git/ldk/k8s/19-statefulsets (master -> origin/master)$ kubectl get pv -o wide

# output
NAME                                       CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS   CLAIM                                 STORAGECLASS   VOLUMEATTRIBUTESCLASS   REASON   AGE    VOLUMEMODE
pvc-5f5d1be4-9c64-42d2-96a4-91e3f30d89b6   1Gi        RWO            Delete           Bound    myns/nginxstsvolumeclaim-nginxsts-0   standard       <unset>                          113s   Filesystem
pvc-9d10d360-391a-4fea-972f-3c0818df1046   1Gi        RWO            Delete           Bound    myns/nginxstsvolumeclaim-nginxsts-2   standard       <unset>                          102s   Filesystem
pvc-9e8a826b-8368-4b40-bb4b-b2965e8b7138   1Gi        RWO            Delete           Bound    myns/nginxstsvolumeclaim-nginxsts-1   standard       <unset>                          107s   Filesystem

# exec into one of the pods
sysuser@ubuntuprod:~/git/ldk/k8s/19-statefulsets (master -> origin/master)$ kubectl exec -it nginxsts-0 -- bash

# run this from inside the pod
root@nginxsts-0:/# cd /data && df -h . && echo "this is from nginxsts-0" > nginxsts-0.txt && cd .. && ls /data/ && cat /data/nginxsts-0.txt 

# output
Filesystem      Size  Used Avail Use% Mounted on
/dev/sda2        59G   25G   31G  45% /data
nginxsts-0.txt
this is from nginxsts-0

# delete the pod and let kubernetes create it again
sysuser@ubuntuprod:~/git/ldk/k8s/19-statefulsets (master -> origin/master)$ kubectl delete pod nginxsts-0 && watch -n 3 kubectl get pods -o wide 

# output
Every 3.0s: kubectl get pods -o wide                                                                                                                                                                      ubuntuprod: Sun Jun 28 13:10:52 2026

NAME         READY   STATUS    RESTARTS   AGE     IP            NODE          NOMINATED NODE   READINESS GATES
nginxsts-0   1/1     Running   0          9s      10.244.1.36   klc-worker    <none>           <none>
nginxsts-1   1/1     Running   0          9m      10.244.2.16   klc-worker2   <none>           <none>
nginxsts-2   1/1     Running   0          8m55s   10.244.1.35   klc-worker    <none>           <none>

# exec back into the pod
sysuser@ubuntuprod:~/git/ldk/k8s/19-statefulsets (master -> origin/master)$ kubectl exec -it nginxsts-0 -- bash

# run the command
root@nginxsts-0:/# cd /data && df -h . && cd .. && ls /data/ && cat /data/nginxsts-0.txt

# output
Filesystem      Size  Used Avail Use% Mounted on
/dev/sda2        59G   25G   31G  45% /data
nginxsts-0.txt
this is from nginxsts-0

# we can also delete the stateful set, and then recreate it and the data will still be there. 