apiVersion: v1
items:
- apiVersion: v1
  kind: Pod
  metadata:
    creationTimestamp: "2026-06-28T17:21:43Z"
    generateName: nginxsts-
    generation: 1
    labels:
      app: nginxsts
      apps.kubernetes.io/pod-index: "0"
      controller-revision-hash: nginxsts-644b8794c5
      statefulset.kubernetes.io/pod-name: nginxsts-0
    name: nginxsts-0
    namespace: myns
    ownerReferences:
    - apiVersion: apps/v1
      blockOwnerDeletion: true
      controller: true
      kind: StatefulSet
      name: nginxsts
      uid: c1560d34-4657-4769-b55b-eb555ea82ea9
    resourceVersion: "947411"
    uid: 6b3f83f5-cee5-4288-a7a7-9354327ae5e9
  spec:
    containers:
    - image: nginx
      imagePullPolicy: Always
      name: nginx
      resources: {}
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      volumeMounts:
      - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
        name: kube-api-access-jq5fz
        readOnly: true
    dnsPolicy: ClusterFirst
    enableServiceLinks: true
    hostname: nginxsts-0
    nodeName: klc-worker2
    preemptionPolicy: PreemptLowerPriority
    priority: 0
    restartPolicy: Always
    schedulerName: default-scheduler
    securityContext: {}
    serviceAccount: default
    serviceAccountName: default
    subdomain: nginxsts
    terminationGracePeriodSeconds: 30
    tolerations:
    - effect: NoExecute
      key: node.kubernetes.io/not-ready
      operator: Exists
      tolerationSeconds: 300
    - effect: NoExecute
      key: node.kubernetes.io/unreachable
      operator: Exists
      tolerationSeconds: 300
    volumes:
    - name: kube-api-access-jq5fz
      projected:
        defaultMode: 420
        sources:
        - serviceAccountToken:
            expirationSeconds: 3607
            path: token
        - configMap:
            items:
            - key: ca.crt
              path: ca.crt
            name: kube-root-ca.crt
        - downwardAPI:
            items:
            - fieldRef:
                apiVersion: v1
                fieldPath: metadata.namespace
              path: namespace
  status:
    conditions:
    - lastProbeTime: null
      lastTransitionTime: "2026-06-28T17:21:45Z"
      observedGeneration: 1
      status: "True"
      type: PodReadyToStartContainers
    - lastProbeTime: null
      lastTransitionTime: "2026-06-28T17:21:43Z"
      observedGeneration: 1
      status: "True"
      type: Initialized
    - lastProbeTime: null
      lastTransitionTime: "2026-06-28T17:21:45Z"
      observedGeneration: 1
      status: "True"
      type: Ready
    - lastProbeTime: null
      lastTransitionTime: "2026-06-28T17:21:45Z"
      observedGeneration: 1
      status: "True"
      type: ContainersReady
    - lastProbeTime: null
      lastTransitionTime: "2026-06-28T17:21:43Z"
      observedGeneration: 1
      status: "True"
      type: PodScheduled
    containerStatuses:
    - containerID: containerd://db15d003b4ce618edcfca81e388d112b8ed12786c88a27cb16676299c567c324
      image: docker.io/library/nginx:latest
      imageID: docker.io/library/nginx@sha256:ec4ed8b5299e5e90694af7750eb6dffd2627317d30544d056b0371f8082f7bce
      lastState: {}
      name: nginx
      ready: true
      resources: {}
      restartCount: 0
      started: true
      state:
        running:
          startedAt: "2026-06-28T17:21:45Z"
      user:
        linux:
          gid: 0
          supplementalGroups:
          - 0
          uid: 0
      volumeMounts:
      - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
        name: kube-api-access-jq5fz
        readOnly: true
        recursiveReadOnly: Disabled
    hostIP: 172.18.0.4
    hostIPs:
    - ip: 172.18.0.4
    observedGeneration: 1
    phase: Running
    podIP: 10.244.2.5
    podIPs:
    - ip: 10.244.2.5
    qosClass: BestEffort
    startTime: "2026-06-28T17:21:43Z"
- apiVersion: v1
  kind: Pod
  metadata:
    creationTimestamp: "2026-06-28T17:21:45Z"
    generateName: nginxsts-
    generation: 1
    labels:
      app: nginxsts
      apps.kubernetes.io/pod-index: "1"
      controller-revision-hash: nginxsts-644b8794c5
      statefulset.kubernetes.io/pod-name: nginxsts-1
    name: nginxsts-1
    namespace: myns
    ownerReferences:
    - apiVersion: apps/v1
      blockOwnerDeletion: true
      controller: true
      kind: StatefulSet
      name: nginxsts
      uid: c1560d34-4657-4769-b55b-eb555ea82ea9
    resourceVersion: "947426"
    uid: 1670d485-905d-4b3d-a35e-a18f3d962448
  spec:
    containers:
    - image: nginx
      imagePullPolicy: Always
      name: nginx
      resources: {}
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      volumeMounts:
      - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
        name: kube-api-access-zllk7
        readOnly: true
    dnsPolicy: ClusterFirst
    enableServiceLinks: true
    hostname: nginxsts-1
    nodeName: klc-worker
    preemptionPolicy: PreemptLowerPriority
    priority: 0
    restartPolicy: Always
    schedulerName: default-scheduler
    securityContext: {}
    serviceAccount: default
    serviceAccountName: default
    subdomain: nginxsts
    terminationGracePeriodSeconds: 30
    tolerations:
    - effect: NoExecute
      key: node.kubernetes.io/not-ready
      operator: Exists
      tolerationSeconds: 300
    - effect: NoExecute
      key: node.kubernetes.io/unreachable
      operator: Exists
      tolerationSeconds: 300
    volumes:
    - name: kube-api-access-zllk7
      projected:
        defaultMode: 420
        sources:
        - serviceAccountToken:
            expirationSeconds: 3607
            path: token
        - configMap:
            items:
            - key: ca.crt
              path: ca.crt
            name: kube-root-ca.crt
        - downwardAPI:
            items:
            - fieldRef:
                apiVersion: v1
                fieldPath: metadata.namespace
              path: namespace
  status:
    conditions:
    - lastProbeTime: null
      lastTransitionTime: "2026-06-28T17:21:47Z"
      observedGeneration: 1
      status: "True"
      type: PodReadyToStartContainers
    - lastProbeTime: null
      lastTransitionTime: "2026-06-28T17:21:45Z"
      observedGeneration: 1
      status: "True"
      type: Initialized
    - lastProbeTime: null
      lastTransitionTime: "2026-06-28T17:21:47Z"
      observedGeneration: 1
      status: "True"
      type: Ready
    - lastProbeTime: null
      lastTransitionTime: "2026-06-28T17:21:47Z"
      observedGeneration: 1
      status: "True"
      type: ContainersReady
    - lastProbeTime: null
      lastTransitionTime: "2026-06-28T17:21:45Z"
      observedGeneration: 1
      status: "True"
      type: PodScheduled
    containerStatuses:
    - containerID: containerd://0d886e54cf5ff3999a5b19b249a140af9a2a9e028da524ce35517df0f44e1423
      image: docker.io/library/nginx:latest
      imageID: docker.io/library/nginx@sha256:ec4ed8b5299e5e90694af7750eb6dffd2627317d30544d056b0371f8082f7bce
      lastState: {}
      name: nginx
      ready: true
      resources: {}
      restartCount: 0
      started: true
      state:
        running:
          startedAt: "2026-06-28T17:21:46Z"
      user:
        linux:
          gid: 0
          supplementalGroups:
          - 0
          uid: 0
      volumeMounts:
      - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
        name: kube-api-access-zllk7
        readOnly: true
        recursiveReadOnly: Disabled
    hostIP: 172.18.0.2
    hostIPs:
    - ip: 172.18.0.2
    observedGeneration: 1
    phase: Running
    podIP: 10.244.1.13
    podIPs:
    - ip: 10.244.1.13
    qosClass: BestEffort
    startTime: "2026-06-28T17:21:45Z"
- apiVersion: v1
  kind: Pod
  metadata:
    creationTimestamp: "2026-06-28T17:35:44Z"
    generateName: nginxsts-
    generation: 1
    labels:
      app: nginxsts
      apps.kubernetes.io/pod-index: "2"
      controller-revision-hash: nginxsts-68959d6bdd
      statefulset.kubernetes.io/pod-name: nginxsts-2
    name: nginxsts-2
    namespace: myns
    ownerReferences:
    - apiVersion: apps/v1
      blockOwnerDeletion: true
      controller: true
      kind: StatefulSet
      name: nginxsts
      uid: c1560d34-4657-4769-b55b-eb555ea82ea9
    resourceVersion: "948753"
    uid: a26f8b8e-f254-48b3-ac43-fbb05ee26d4b
  spec:
    containers:
    - image: nginx:alpine
      imagePullPolicy: Always
      name: nginx
      resources: {}
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      volumeMounts:
      - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
        name: kube-api-access-jvn5l
        readOnly: true
    dnsPolicy: ClusterFirst
    enableServiceLinks: true
    hostname: nginxsts-2
    nodeName: klc-worker
    preemptionPolicy: PreemptLowerPriority
    priority: 0
    restartPolicy: Always
    schedulerName: default-scheduler
    securityContext: {}
    serviceAccount: default
    serviceAccountName: default
    subdomain: nginxsts
    terminationGracePeriodSeconds: 30
    tolerations:
    - effect: NoExecute
      key: node.kubernetes.io/not-ready
      operator: Exists
      tolerationSeconds: 300
    - effect: NoExecute
      key: node.kubernetes.io/unreachable
      operator: Exists
      tolerationSeconds: 300
    volumes:
    - name: kube-api-access-jvn5l
      projected:
        defaultMode: 420
        sources:
        - serviceAccountToken:
            expirationSeconds: 3607
            path: token
        - configMap:
            items:
            - key: ca.crt
              path: ca.crt
            name: kube-root-ca.crt
        - downwardAPI:
            items:
            - fieldRef:
                apiVersion: v1
                fieldPath: metadata.namespace
              path: namespace
  status:
    conditions:
    - lastProbeTime: null
      lastTransitionTime: "2026-06-28T17:35:48Z"
      observedGeneration: 1
      status: "True"
      type: PodReadyToStartContainers
    - lastProbeTime: null
      lastTransitionTime: "2026-06-28T17:35:44Z"
      observedGeneration: 1
      status: "True"
      type: Initialized
    - lastProbeTime: null
      lastTransitionTime: "2026-06-28T17:35:48Z"
      observedGeneration: 1
      status: "True"
      type: Ready
    - lastProbeTime: null
      lastTransitionTime: "2026-06-28T17:35:48Z"
      observedGeneration: 1
      status: "True"
      type: ContainersReady
    - lastProbeTime: null
      lastTransitionTime: "2026-06-28T17:35:44Z"
      observedGeneration: 1
      status: "True"
      type: PodScheduled
    containerStatuses:
    - containerID: containerd://f2b8d2d2adb8cfb2cb980d1ac187fc9c6897c7f139e7c6b30beea679f947a77d
      image: docker.io/library/nginx:alpine
      imageID: docker.io/library/nginx@sha256:54f2a904c251d5a34adf545a72d32515a15e08418dae0266e23be2e18c66fefa
      lastState: {}
      name: nginx
      ready: true
      resources: {}
      restartCount: 0
      started: true
      state:
        running:
          startedAt: "2026-06-28T17:35:48Z"
      user:
        linux:
          gid: 0
          supplementalGroups:
          - 0
          - 1
          - 2
          - 3
          - 4
          - 6
          - 10
          - 11
          - 20
          - 26
          - 27
          uid: 0
      volumeMounts:
      - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
        name: kube-api-access-jvn5l
        readOnly: true
        recursiveReadOnly: Disabled
    hostIP: 172.18.0.2
    hostIPs:
    - ip: 172.18.0.2
    observedGeneration: 1
    phase: Running
    podIP: 10.244.1.15
    podIPs:
    - ip: 10.244.1.15
    qosClass: BestEffort
    startTime: "2026-06-28T17:35:44Z"
kind: List
metadata:
  resourceVersion: ""
