# create an ubuntu pod from custom image to demonstrate privilege escalation
sysuser@ubuntuprod:~/git/ldk/k8s/24-security-contexts (master -> origin/master)$ kubectl run ubuntupod --image=spurin/rootshell:latest -o yaml --dry-run=client -- sleep infinity > ubuntu_secure.yaml

# apply the file
sysuser@ubuntuprod:~/git/ldk/k8s/24-security-contexts (master -> origin/master)$ kubectl apply -f ubuntu_secure.yaml 

# output
pod/ubuntupod created

# exec into the pod. have root access at this point. 
sysuser@ubuntuprod:~/git/ldk/k8s/24-security-contexts (master -> origin/master)$ kubectl exec -it ubuntupod -- bash

# output
root@ubuntupod:/# 

# Exit out of the pod
root@ubuntupod:/# exit

# output
exit

# create a new yaml from the pod spec yaml and add security context - ubuntu_secure2.yaml. replace existing with this. this can take a minute.
sysuser@ubuntuprod:~/git/ldk/k8s/24-security-contexts (master -> origin/master)$ kubectl replace --force -f ubuntu_secure2.yaml 

# output
pod "ubuntupod" deleted from myns namespace
pod/ubuntupod replaced

# exec into the pod. no longer the root. 
sysuser@ubuntuprod:~/git/ldk/k8s/24-security-contexts (master -> origin/master)$ kubectl exec -it ubuntupod -- bash

# output
nonpriv@ubuntupod:/$ 

# confirm
nonpriv@ubuntupod:/$ id

# output
uid=1000(nonpriv) gid=1000(nonpriv) groups=1000(nonpriv)

# can upgrade our privileges to root by running /rootshell
nonpriv@ubuntupod:/$ /rootshell 

# output
root@ubuntupod:/# 

# run id
root@ubuntupod:/# id

# output
uid=0(root) gid=1000(nonpriv) groups=1000(nonpriv)

# we want to improve security to prevent this. ubuntu_secure3.yaml has allowPrivilegeEscalation to false, so cant run /rootshell anymore. replace existing pod
sysuser@ubuntuprod:~/git/ldk/k8s/24-security-contexts (master -> origin/master)$ kubectl replace --force -f ubuntu_secure3.yaml 

# output
pod "ubuntupod" deleted from myns namespace
pod/ubuntupod replaced

# exec into the pod
sysuser@ubuntuprod:~/git/ldk/k8s/24-security-contexts (master -> origin/master)$ kubectl exec -it ubuntupod -- bash

# output
nonpriv@ubuntupod:/$

# run /rootshell. nothing happens. 
nonpriv@ubuntupod:/$ /rootshell 

# output
nonpriv@ubuntupod:/$ 

