# if myns namespace doesnt exist create it and set the context to myns namespace
sysuser@ubuntuprod:~/git/ldk/k8s/22-gateway-api (master -> origin/master)$ kubectl create namespace myns && kubectl config set-context --current --namespace=myns && kubectl config view

# output
namespace/myns created
Context "kind-klc" modified.
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: DATA+OMITTED
    server: https://127.0.0.1:34285
  name: kind-klc
contexts:
- context:
    cluster: kind-klc
    namespace: myns
    user: kind-klc
  name: kind-klc
current-context: kind-klc
kind: Config
users:
- name: kind-klc
  user:
    client-certificate-data: DATA+OMITTED
    client-key-data: DATA+OMITTED



# helm is required to setup gateway api
sysuser@ubuntuprod:~/git/ldk/k8s/22-gateway-api (master -> origin/master)$ sudo apt update

# output
[sudo: authenticate] Password:          
Hit:1 http://us.archive.ubuntu.com/ubuntu resolute InRelease
Get:2 https://download.docker.com/linux/ubuntu resolute InRelease [32.5 kB] 
Hit:3 http://us.archive.ubuntu.com/ubuntu resolute-updates InRelease        
Hit:4 http://security.ubuntu.com/ubuntu resolute-security InRelease         
Hit:5 http://us.archive.ubuntu.com/ubuntu resolute-backports InRelease      
Get:6 https://download.docker.com/linux/ubuntu resolute/stable amd64 Packages [18.7 kB]
Fetched 51.2 kB in 1s (87.6 kB/s)
18 packages can be upgraded. Run 'apt list --upgradable' to see them.

# https://docs.nginx.com/nginx-gateway-fabric/install/helm/#installing-the-gateway-api-resources get the latest version reference from there to deploy api resource. pre requisite to nginx gateway fabric
sysuser@ubuntuprod:~/git/ldk/k8s/22-gateway-api (master -> origin/master)$ kubectl kustomize "https://github.com/nginx/nginx-gateway-fabric/config/crd/gateway-api/standard?ref=v2.6.5" | kubectl apply -f -

# output
sysuser@ubuntuprod:~/git/ldk/k8s/22-gateway-api (master -> origin/master)$ kubectl kustomize "https://github.com/nginx/nginx-gateway-fabric/config/crd/gateway-api/standard?ref=v2.6.5" | kubectl apply -f -
customresourcedefinition.apiextensions.k8s.io/backendtlspolicies.gateway.networking.k8s.io created
customresourcedefinition.apiextensions.k8s.io/gatewayclasses.gateway.networking.k8s.io created
customresourcedefinition.apiextensions.k8s.io/gateways.gateway.networking.k8s.io created
customresourcedefinition.apiextensions.k8s.io/grpcroutes.gateway.networking.k8s.io created
customresourcedefinition.apiextensions.k8s.io/httproutes.gateway.networking.k8s.io created
customresourcedefinition.apiextensions.k8s.io/listenersets.gateway.networking.k8s.io created
customresourcedefinition.apiextensions.k8s.io/referencegrants.gateway.networking.k8s.io created
customresourcedefinition.apiextensions.k8s.io/tlsroutes.gateway.networking.k8s.io created
validatingadmissionpolicy.admissionregistration.k8s.io/safe-upgrades.gateway.networking.k8s.io created
validatingadmissionpolicybinding.admissionregistration.k8s.io/safe-upgrades.gateway.networking.k8s.io created

# to get the crd yaml for api resources
sysuser@ubuntuprod:~/git/ldk/k8s/22-gateway-api (master -> origin/master)$ kubectl kustomize "https://github.com/nginx/nginx-gateway-fabric/config/crd/gateway-api/standard?ref=v2.6.5" > nginx-gateway-fabric.yaml

# install nginx gateway fabric
# https://docs.nginx.com/nginx-gateway-fabric/install/helm/#install-from-the-oci-registry
sysuser@ubuntuprod:~/git/ldk/k8s/22-gateway-api (master -> origin/master)$ helm install ngf oci://ghcr.io/nginx/charts/nginx-gateway-fabric --create-namespace -n nginx-gateway

# output
Pulled: ghcr.io/nginx/charts/nginx-gateway-fabric:2.6.6
Digest: sha256:f6e155af4804ec5e45de8a793ebfa3af633edcba94f4f02c4c8b5e6bdb9f8ad6
NAME: ngf
LAST DEPLOYED: Mon Jun 29 05:19:58 2026
NAMESPACE: nginx-gateway
STATUS: deployed
REVISION: 1
DESCRIPTION: Install complete
TEST SUITE: None

# get resources
sysuser@ubuntuprod:~/git/ldk/k8s/22-gateway-api (master -> origin/master)$ kubectl -n nginx-gateway get svc,deployment,pods

# output
NAME                               TYPE        CLUSTER-IP     EXTERNAL-IP   PORT(S)   AGE
service/ngf-nginx-gateway-fabric   ClusterIP   10.96.24.161   <none>        443/TCP   112s

NAME                                       READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/ngf-nginx-gateway-fabric   1/1     1            1           112s

NAME                                            READY   STATUS    RESTARTS   AGE
pod/ngf-nginx-gateway-fabric-6675fcdbd6-q869n   1/1     Running   0          112s

# get gatewayclass
sysuser@ubuntuprod:~/git/ldk/k8s/22-gateway-api (master -> origin/master)$ kubectl get gatewayclass

# output
NAME                  CONTROLLER                                   ACCEPTED   AGE
cloud-provider-kind   kind.sigs.k8s.io/gateway-controller          True       8d
nginx                 gateway.nginx.org/nginx-gateway-controller   True       2m38s

# get nginx gateway class yaml
sysuser@ubuntuprod:~/git/ldk/k8s/22-gateway-api (master -> origin/master)$ kubectl get gatewayclass nginx -o yaml | tee nginx-gatewayclass.yaml
apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  annotations:
    meta.helm.sh/release-name: ngf
    meta.helm.sh/release-namespace: nginx-gateway
  creationTimestamp: "2026-06-29T10:20:09Z"
  generation: 1
  labels:
    app.kubernetes.io/instance: ngf
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: nginx-gateway-fabric
    app.kubernetes.io/version: 2.6.6
    helm.sh/chart: nginx-gateway-fabric-2.6.6
  name: nginx
  resourceVersion: "1041852"
  uid: 2a8f6f72-4bf5-476c-9771-fae5370978b1
spec:
  controllerName: gateway.nginx.org/nginx-gateway-controller
  parametersRef:
    group: gateway.nginx.org
    kind: NginxProxy
    name: ngf-proxy-config
    namespace: nginx-gateway
status:
  conditions:
  - lastTransitionTime: "2026-06-29T10:20:13Z"
    message: The GatewayClass is accepted
    observedGeneration: 1
    reason: Accepted
    status: "True"
    type: Accepted
  - lastTransitionTime: "2026-06-29T10:20:13Z"
    message: The Gateway API CRD versions are supported
    observedGeneration: 1
    reason: SupportedVersion
    status: "True"
    type: SupportedVersion
  - lastTransitionTime: "2026-06-29T10:20:13Z"
    message: The ParametersRef resource is resolved
    observedGeneration: 1
    reason: ResolvedRefs
    status: "True"
    type: ResolvedRefs
  supportedFeatures:
  - name: BackendTLSPolicy
  - name: GRPCRoute
  - name: Gateway
  - name: GatewayAddressEmpty
  - name: GatewayBackendClientCertificate
  - name: GatewayFrontendClientCertificateValidation
  - name: GatewayFrontendClientCertificateValidationInsecureFallback
  - name: GatewayHTTPListenerIsolation
  - name: GatewayHTTPSListenerDetectMisdirectedRequests
  - name: GatewayInfrastructurePropagation
  - name: GatewayPort8080
  - name: GatewayStaticAddresses
  - name: HTTPRoute
  - name: HTTPRoute303RedirectStatusCode
  - name: HTTPRoute307RedirectStatusCode
  - name: HTTPRoute308RedirectStatusCode
  - name: HTTPRouteBackendProtocolWebSocket
  - name: HTTPRouteCORS
  - name: HTTPRouteDestinationPortMatching
  - name: HTTPRouteHostRewrite
  - name: HTTPRouteMethodMatching
  - name: HTTPRouteParentRefPort
  - name: HTTPRoutePathRedirect
  - name: HTTPRoutePathRewrite
  - name: HTTPRoutePortRedirect
  - name: HTTPRouteQueryParamMatching
  - name: HTTPRouteRequestMirror
  - name: HTTPRouteRequestMultipleMirrors
  - name: HTTPRouteRequestPercentageMirror
  - name: HTTPRouteResponseHeaderModification
  - name: HTTPRouteSchemeRedirect
  - name: ListenerSet
  - name: ReferenceGrant
  - name: TLSRoute

  
# create pod yamls
sysuser@ubuntuprod:~/git/ldk/k8s/22-gateway-api (master -> origin/master)$ kubectl run nginx-frontend --image=spurin/nginx-debug --port=80 --dry-run=client -o yaml | tee nginx-frontend.yaml && kubectl run nginx-api --image=spurin/nginx-debug --port=80 --dry-run=client -o yaml | tee nginx-api.yaml && kubectl run nginx-admin --image=spurin/nginx-debug --port=80 --dry-run=client -o yaml | tee nginx-admin.yaml

# output
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginx-frontend
  name: nginx-frontend
spec:
  containers:
  - image: spurin/nginx-debug
    name: nginx-frontend
    ports:
    - containerPort: 80
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginx-api
  name: nginx-api
spec:
  containers:
  - image: spurin/nginx-debug
    name: nginx-api
    ports:
    - containerPort: 80
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginx-admin
  name: nginx-admin
spec:
  containers:
  - image: spurin/nginx-debug
    name: nginx-admin
    ports:
    - containerPort: 80
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}

# apply the files
sysuser@ubuntuprod:~/git/ldk/k8s/22-gateway-api (master -> origin/master)$ kubectl apply -f nginx-admin.yaml && kubectl apply -f nginx-api.yaml && kubectl apply -f nginx-frontend.yaml

# output
pod/nginx-admin created
pod/nginx-api created
pod/nginx-frontend created

# expose pods and get resources
sysuser@ubuntuprod:~/git/ldk/k8s/22-gateway-api (master -> origin/master)$ kubectl expose pod/nginx-api && kubectl expose pod/nginx-admin && kubectl expose pod/nginx-frontend && echo "---PODS---" && kubectl get pods -o wide --show-labels && echo "---SVC---" && kubectl get svc -o wide && echo "---ENDPOINT-SLICES---" && kubectl get endpointslices -o wide

# output
service/nginx-api exposed
service/nginx-admin exposed
service/nginx-frontend exposed
---PODS---
NAME             READY   STATUS    RESTARTS   AGE   IP            NODE          NOMINATED NODE   READINESS GATES   LABELS
nginx-admin      1/1     Running   0          64s   10.244.2.31   klc-worker2   <none>           <none>            run=nginx-admin
nginx-api        1/1     Running   0          64s   10.244.1.55   klc-worker    <none>           <none>            run=nginx-api
nginx-frontend   1/1     Running   0          64s   10.244.2.32   klc-worker2   <none>           <none>            run=nginx-frontend
---SVC---
NAME             TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)   AGE   SELECTOR
nginx-admin      ClusterIP   10.96.140.52    <none>        80/TCP    0s    run=nginx-admin
nginx-api        ClusterIP   10.96.104.167   <none>        80/TCP    1s    run=nginx-api
nginx-frontend   ClusterIP   10.96.162.28    <none>        80/TCP    0s    run=nginx-frontend
---ENDPOINT-SLICES---
NAME                   ADDRESSTYPE   PORTS   ENDPOINTS     AGE
nginx-admin-c7vjx      IPv4          80      10.244.2.31   0s
nginx-api-bqtxm        IPv4          80      10.244.1.55   1s
nginx-frontend-qxt5b   IPv4          80      10.244.2.32   0s

# create gateway resource
# create namespace for it
sysuser@ubuntuprod:~/git/ldk/k8s/22-gateway-api (master -> origin/master)$ kubectl create namespace gateway-system

# output
namespace/gateway-system created

# create nginx-gateway.yaml manually add spec
sysuser@ubuntuprod:~/git/ldk/k8s/22-gateway-api (master -> origin/master)$ kubectl apply -f nginx-gateway.yaml
gateway.gateway.networking.k8s.io/edge-gw created

# get the gateway and write to yaml also. might have to give it some time to populate address. 
sysuser@ubuntuprod:~/git/ldk/k8s/22-gateway-api (master -> origin/master)$ kubectl get gateway -n gateway-system && kubectl get -n gateway-system gateway/edge-gw -o yaml > edge-gw-applied.yaml
NAME      CLASS   ADDRESS      PROGRAMMED   AGE
edge-gw   nginx   172.18.0.6   True         9m3s

# manually create httproute.yaml and apply it
sysuser@ubuntuprod:~/git/ldk/k8s/22-gateway-api (master -> origin/master)$ kubectl apply -f httproute.yaml

# output
httproute.gateway.networking.k8s.io/mygateway-app created

# get the http route and write it to file also
sysuser@ubuntuprod:~/git/ldk/k8s/22-gateway-api (master -> origin/master)$ kubectl get httproute && kubectl get httproute/mygateway-app -o yaml > httproute-mygateway-app-applied.yaml

# output
NAME            HOSTNAMES                 AGE
mygateway-app   ["mygateway-app.local"]   54s

# curl the IP using the edge-gw IP address
sysuser@ubuntuprod:~/git/ldk/k8s/22-gateway-api (master -> origin/master)$ curl --resolve *:80:172.18.0.6 http://mygateway-app.local

# output
<!DOCTYPE html>
<body>
<p><em>Hostname: nginx-frontend</em></p>
<p><em>IP Address: 10.244.2.32:80</em></p>
<p><em>URL: /</em></p>
<p><em>Request Method: GET</em></p>
<p><em>Request ID: e66548a7b4411eec22ed401082a44fcb</em></p>
</body>
</html>

# 
sysuser@ubuntuprod:~/git/ldk/k8s/22-gateway-api (master -> origin/master)$ openssl req -x509 -nodes -days 99999 -newkey rsa:2048 -keyout mygateway-app.local.key -out mygateway-app.local.crt -subj "/CN=mygateway-app.local" -addext "subjectAltName=DNS:mygateway-app.local"

# output
.+++++++++++++++++++++++++++++++++++++++*....+...+++++++++++++++++++++++++++++++++++++++*....+.......+..+.......+...+......+............+..+.......+........+...+....+...+......+......+...+..+.+..+.+.....+......+...+..........+...+.....+....+.....+.........+....+..+..........+...........+.......+...+..................+......+......+..+...+..........+..+................+..............+.+......+...........+....+...+...........+.+...+...+..+............+.+........+.........++++++
...+...+.+...+.....+..........+.....+.....................+....+..+.+.....+...+....+++++++++++++++++++++++++++++++++++++++*...+.+..............+.+...+.....+................+++++++++++++++++++++++++++++++++++++++*......+...++++++
-----

# we will copy the file into the control plane container
sysuser@ubuntuprod:~/git/ldk/k8s/22-gateway-api (master -> origin/master)$ docker cp /home/sysuser/git/ldk/k8s/22-gateway-api/mygateway-app.local.crt klc-control-plane:/usr/local/share/ca-certificates/

# output
Successfully copied 1.19kB (transferred 3.07kB) to klc-control-plane:/usr/local/share/ca-certificates/

# in a new terminal exec shell into the control plane container
sysuser@ubuntuprod:~/git/ldk/k8s/22-gateway-api (master -> origin/master)$ docker exec -it klc-control-plane bash

# output
root@klc-control-plane:/# 

# update certificates
root@klc-control-plane:/# update-ca-certificates

# output
Updating certificates in /etc/ssl/certs...
rehash: warning: skipping ca-certificates.crt,it does not contain exactly one certificate or CRL
1 added, 0 removed; done.
Running hooks in /etc/ca-certificates/update.d...
done.

# create a secret
sysuser@ubuntuprod:~/git/ldk/k8s/22-gateway-api (master -> origin/master)$ kubectl create secret tls mygateway-app-tls-secret --cert=mygateway-app.local.crt --key=mygateway-app.local.key && kubectl get secrets -o wide

# output
secret/mygateway-app-tls-secret created
NAME                       TYPE                DATA   AGE
mygateway-app-tls-secret   kubernetes.io/tls   2      0s

# apply the change and get the yaml of the gateway and check it to make sure the secret is referenced
sysuser@ubuntuprod:~/git/ldk/k8s/22-gateway-api (master -> origin/master)$ kubectl apply -f nginx-gateway-secret.yaml && sleep 2 && kubectl get gateway/edge-gw -n gateway-system > edge-gw-applied-secret.yaml

# output
gateway.gateway.networking.k8s.io/edge-gw configured

# run curl command on control plane
