apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"gateway.networking.k8s.io/v1","kind":"Gateway","metadata":{"annotations":{},"name":"edge-gw","namespace":"gateway-system"},"spec":{"gatewayClassName":"nginx","listeners":[{"allowedRoutes":{"namespaces":{"from":"All"}},"hostname":"mygateway-app.local","name":"http","port":80,"protocol":"HTTP"},{"allowedRoutes":{"namespaces":{"from":"All"}},"hostname":"mygateway-app.local","name":"https","port":443,"protocol":"HTTPS","tls":{"certificateRefs":[{"kind":"Secret","name":"mygateway-app-tls-secret"}],"mode":"Terminate"}}]}}
  creationTimestamp: "2026-06-29T10:40:37Z"
  generation: 2
  name: edge-gw
  namespace: gateway-system
  resourceVersion: "1190626"
  uid: 2d2dad13-f350-4431-ac62-ee9bdc09c56e
spec:
  gatewayClassName: nginx
  listeners:
  - allowedRoutes:
      namespaces:
        from: All
    hostname: mygateway-app.local
    name: http
    port: 80
    protocol: HTTP
  - allowedRoutes:
      namespaces:
        from: All
    hostname: mygateway-app.local
    name: https
    port: 443
    protocol: HTTPS
    tls:
      certificateRefs:
      - group: ""
        kind: Secret
        name: mygateway-app-tls-secret
      mode: Terminate
status:
  addresses:
  - type: IPAddress
    value: 172.18.0.6
  attachedListenerSets: 0
  conditions:
  - lastTransitionTime: "2026-06-30T11:05:17Z"
    message: The Gateway is programmed
    observedGeneration: 2
    reason: Programmed
    status: "True"
    type: Programmed
  - lastTransitionTime: "2026-06-30T11:05:17Z"
    message: The Gateway has at least one valid listener
    observedGeneration: 2
    reason: ListenersNotValid
    status: "True"
    type: Accepted
  listeners:
  - attachedRoutes: 1
    conditions:
    - lastTransitionTime: "2026-06-30T11:05:17Z"
      message: The Listener is programmed
      observedGeneration: 2
      reason: Programmed
      status: "True"
      type: Programmed
    - lastTransitionTime: "2026-06-30T11:05:17Z"
      message: The Listener is accepted
      observedGeneration: 2
      reason: Accepted
      status: "True"
      type: Accepted
    - lastTransitionTime: "2026-06-30T11:05:17Z"
      message: All references are resolved
      observedGeneration: 2
      reason: ResolvedRefs
      status: "True"
      type: ResolvedRefs
    - lastTransitionTime: "2026-06-30T11:05:17Z"
      message: No conflicts
      observedGeneration: 2
      reason: NoConflicts
      status: "False"
      type: Conflicted
    name: http
    supportedKinds:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
    - group: gateway.networking.k8s.io
      kind: GRPCRoute
  - attachedRoutes: 1
    conditions:
    - lastTransitionTime: "2026-06-30T11:05:17Z"
      message: 'tls.certificateRefs[0]: Invalid value: {"Namespace":"gateway-system","Name":"mygateway-app-tls-secret"}:
        Secret gateway-system/mygateway-app-tls-secret does not exist'
      observedGeneration: 2
      reason: InvalidCertificateRef
      status: "False"
      type: Accepted
    - lastTransitionTime: "2026-06-30T11:05:17Z"
      message: 'tls.certificateRefs[0]: Invalid value: {"Namespace":"gateway-system","Name":"mygateway-app-tls-secret"}:
        Secret gateway-system/mygateway-app-tls-secret does not exist'
      observedGeneration: 2
      reason: InvalidCertificateRef
      status: "False"
      type: ResolvedRefs
    - lastTransitionTime: "2026-06-30T11:05:17Z"
      message: 'tls.certificateRefs[0]: Invalid value: {"Namespace":"gateway-system","Name":"mygateway-app-tls-secret"}:
        Secret gateway-system/mygateway-app-tls-secret does not exist'
      observedGeneration: 2
      reason: Invalid
      status: "False"
      type: Programmed
    name: https
    supportedKinds:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
    - group: gateway.networking.k8s.io
      kind: GRPCRoute
