# create nginx pod

kubectl run nginx --image=nginx

# get pods

kubectl get pods

# wide option

kubectl get pods -o wide

# output
sysuser@ubuntuprod:~/git/ldk (master -> origin/master)$ kubectl get pods -o wide
NAME    READY   STATUS    RESTARTS   AGE   IP           NODE         NOMINATED NODE   READINESS GATES
nginx   1/1     Running   0          95s   10.244.1.2   klc-worker   <none>           <none>

# use port forward to access the pod IP address from outside of the cluster. 
sysuser@ubuntuprod:~/git/ldk (master -> origin/master)$ kubectl port-forward pod/nginx 8080:80

# now curl to localhost:8080
sysuser@ubuntuprod:~/git/ldk (master -> origin/master)$ curl localhost:8080

# output
<!DOCTYPE html>
<html>
<head>
<title>Welcome to nginx!</title>
<style>
html { color-scheme: light dark; }
body { width: 35em; margin: 0 auto;
font-family: Tahoma, Verdana, Arial, sans-serif; }
</style>
</head>
<body>
<h1>Welcome to nginx!</h1>
<p>If you see this page, nginx is successfully installed and working.
Further configuration is required for the web server, reverse proxy, 
API gateway, load balancer, content cache, or other features.</p>

<p>For online documentation and support please refer to
<a href="https://nginx.org/">nginx.org</a>.<br/>
To engage with the community please visit
<a href="https://community.nginx.org/">community.nginx.org</a>.<br/>
For enterprise grade support, professional services, additional 
security features and capabilities please refer to
<a href="https://f5.com/nginx">f5.com/nginx</a>.</p>

<p><em>Thank you for using nginx.</em></p>
</body>
</html>

# another way to access the pod is by creating a curl pod.
sysuser@ubuntuprod:~/git/ldk (master -> origin/master)$ kubectl run -it --rm curlpod --image=curlimages/curl --restart=Never -- http://10.244.1.2

# output
<!DOCTYPE html>
<html>
<head>
<title>Welcome to nginx!</title>
<style>
html { color-scheme: light dark; }
body { width: 35em; margin: 0 auto;
font-family: Tahoma, Verdana, Arial, sans-serif; }
</style>
</head>
<body>
<h1>Welcome to nginx!</h1>
<p>If you see this page, nginx is successfully installed and working.
Further configuration is required for the web server, reverse proxy, 
API gateway, load balancer, content cache, or other features.</p>

<p>For online documentation and support please refer to
<a href="https://nginx.org/">nginx.org</a>.<br/>
To engage with the community please visit
<a href="https://community.nginx.org/">community.nginx.org</a>.<br/>
For enterprise grade support, professional services, additional 
security features and capabilities please refer to
<a href="https://f5.com/nginx">f5.com/nginx</a>.</p>

<p><em>Thank you for using nginx.</em></p>
</body>
</html>
pod "curlpod" deleted from default namespace

# run ubuntu pod and let it run in the background
sysuser@ubuntuprod:~/git/ldk (master -> origin/master)$ kubectl run --image=ubuntu ubuntupod sleep infinity

# output
pod/ubuntupod created

# shell into the ubuntupod
sysuser@ubuntuprod:~/git/ldk (master -> origin/master)$ kubectl exec -it ubuntupod -- bash

# run the following command to update apt, install curl and curl the pod IP
root@ubuntupod:/# apt update && apt install curl -y && curl 10.244.1.2

# output
Hit:1 http://archive.ubuntu.com/ubuntu resolute InRelease
Hit:2 http://security.ubuntu.com/ubuntu resolute-security InRelease
Hit:3 http://archive.ubuntu.com/ubuntu resolute-updates InRelease
Hit:4 http://archive.ubuntu.com/ubuntu resolute-backports InRelease
5 packages can be upgraded. Run 'apt list --upgradable' to see them.
curl is already the newest version (8.18.0-1ubuntu2.1).
Summary:                    
  Upgrading: 0, Installing: 0, Removing: 0, Not Upgrading: 5
<!DOCTYPE html>
<html>
<head>
<title>Welcome to nginx!</title>
<style>
html { color-scheme: light dark; }
body { width: 35em; margin: 0 auto;
font-family: Tahoma, Verdana, Arial, sans-serif; }
</style>
</head>
<body>
<h1>Welcome to nginx!</h1>
<p>If you see this page, nginx is successfully installed and working.
Further configuration is required for the web server, reverse proxy, 
API gateway, load balancer, content cache, or other features.</p>

<p>For online documentation and support please refer to
<a href="https://nginx.org/">nginx.org</a>.<br/>
To engage with the community please visit
<a href="https://community.nginx.org/">community.nginx.org</a>.<br/>
For enterprise grade support, professional services, additional 
security features and capabilities please refer to
<a href="https://f5.com/nginx">f5.com/nginx</a>.</p>

<p><em>Thank you for using nginx.</em></p>
</body>
</html>

# create nginx pod yaml spec
sysuser@ubuntuprod:~/git/ldk/kcna/prestige2/01-pods (master -> origin/master)$ kubectl run nginxpod --image=nginx --dry-run=client -o yaml | tee nginxpod.yaml

# output
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginxpod
  name: nginxpod
spec:
  containers:
  - image: nginx
    name: nginxpod
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}

# create a namespace kcna
sysuser@ubuntuprod:~/git/ldk/kcna/prestige2/01-pods (master -> origin/master)$ kubectl create namespace kcna

# output
namespace/kcna created

# apply the pod
sysuser@ubuntuprod:~/git/ldk/kcna/prestige2/01-pods (master -> origin/master)$ kubectl apply -f nginxpod.yaml -n kcna

# create a ubuntu pod yaml spec
sysuser@ubuntuprod:~/git/ldk/kcna/prestige2/01-pods (master -> origin/master)$ kubectl run --image=ubuntu --dry-run=client -o yaml ubuntupod sleep infinity | tee ubuntupod.yaml

# apply the pod
sysuser@ubuntuprod:~/git/ldk/kcna/prestige2/01-pods (master -> origin/master)$ kubectl apply -f ubuntupod.yaml -n kcna

# output
pod/ubuntupod created

# combine both the pods into one pod spec. this will create two pods at the same time
sysuser@ubuntuprod:~/git/ldk/kcna/prestige2/01-pods (master -> origin/master)$ { cat nginxpod.yaml; echo "---"; cat ubuntupod.yaml; } | tee ubuntunginxpod.yaml

# apply the pod spec
sysuser@ubuntuprod:~/git/ldk/kcna/prestige2/01-pods (master -> origin/master)$ kubectl apply -f ubuntunginxpod.yaml -n kcna

# output
pod/nginxpod created
pod/ubuntupod created

# delete both the pods
sysuser@ubuntuprod:~/git/ldk/kcna/prestige2/01-pods (master -> origin/master)$ kubectl delete -f ubuntunginxpod.yaml -n kcna --now

# combine both images to run inside one pod as two containers
sysuser@ubuntuprod:~/git/ldk/kcna/prestige2/01-pods (master -> origin/master)$ kubectl apply -f combined.yaml 

# output
pod/combined created

# get pods
sysuser@ubuntuprod:~/git/ldk/kcna/prestige2/01-pods (master -> origin/master)$ kubectl get pods -o wide

# output
NAME       READY   STATUS    RESTARTS   AGE   IP           NODE         NOMINATED NODE   READINESS GATES
combined   2/2     Running   0          41s   10.244.1.2   klc-worker   <none>           <none>

# describe the pods
sysuser@ubuntuprod:~/git/ldk/kcna/prestige2/01-pods (master -> origin/master)$ kubectl describe pod/combined

# output
Name:             combined
Namespace:        default
Priority:         0
Service Account:  default
Node:             klc-worker/172.18.0.2
Start Time:       Fri, 19 Jun 2026 08:36:33 -0500
Labels:           run=combined
Annotations:      <none>
Status:           Running
IP:               10.244.1.2
IPs:
  IP:  10.244.1.2
Containers:
  nginxpod:
    Container ID:   containerd://20b79db4e67735e5735d537096d75119621d559bd0d8ded1970c270facdc2ae9
    Image:          nginx
    Image ID:       docker.io/library/nginx@sha256:42f2d24ae18df9b5251d1cc45548085656d2335e9338fd150a24e415462d151f
    Port:           <none>
    Host Port:      <none>
    State:          Running
      Started:      Fri, 19 Jun 2026 08:36:38 -0500
    Ready:          True
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-w7cv6 (ro)
  ubuntupod:
    Container ID:  containerd://a729bc1ebd54aa07e3fe7e2406580962676f20740d9096677b12d5e9f6159ad9
    Image:         ubuntu
    Image ID:      docker.io/library/ubuntu@sha256:e153663f92c94118ff22a5dc397b59b351ffd695480566debb5850e017e5937a
    Port:          <none>
    Host Port:     <none>
    Args:
      /bin/sh
      -c
      while true; do echo "$(date + '%T') - Hello from ubuntu"; sleep 5; if [ -f /tmp/crash ]; then exit 1; fi; done
    State:          Running
      Started:      Fri, 19 Jun 2026 08:36:41 -0500
    Ready:          True
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-w7cv6 (ro)
Conditions:
  Type                        Status
  PodReadyToStartContainers   True 
  Initialized                 True 
  Ready                       True 
  ContainersReady             True 
  PodScheduled                True 
Volumes:
  kube-api-access-w7cv6:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    Optional:                false
    DownwardAPI:             true
QoS Class:                   BestEffort
Node-Selectors:              <none>
Tolerations:                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type    Reason     Age   From               Message
  ----    ------     ----  ----               -------
  Normal  Scheduled  93s   default-scheduler  Successfully assigned default/combined to klc-worker
  Normal  Pulling    93s   kubelet            spec.containers{nginxpod}: Pulling image "nginx"
  Normal  Pulled     90s   kubelet            spec.containers{nginxpod}: Successfully pulled image "nginx" in 3.34s (3.34s including waiting). Image size: 63132582 bytes.
  Normal  Created    90s   kubelet            spec.containers{nginxpod}: Container created
  Normal  Started    89s   kubelet            spec.containers{nginxpod}: Container started
  Normal  Pulling    89s   kubelet            spec.containers{ubuntupod}: Pulling image "ubuntu"
  Normal  Pulled     86s   kubelet            spec.containers{ubuntupod}: Successfully pulled image "ubuntu" in 3.695s (3.695s including waiting). Image size: 41575098 bytes.
  Normal  Created    86s   kubelet            spec.containers{ubuntupod}: Container created
  Normal  Started    86s   kubelet            spec.containers{ubuntupod}: Container started
