# create nginx pod

kubectl run nginx --image=nginx

# get pods

kubectl get pods

# wide option

kubectl get pods -o wide

# output
sysuser@ubuntuprod:~/git/ldk (master -> origin/master)$ kubectl get pods -o wide
NAME    READY   STATUS    RESTARTS   AGE   IP           NODE         NOMINATED NODE   READINESS GATES
nginx   1/1     Running   0          95s   10.244.1.2   klc-worker   <none>           <none>

# use port forward to access the pod IP address from outside of the cluster. 
sysuser@ubuntuprod:~/git/ldk (master -> origin/master)$ kubectl port-forward pod/nginx 8080:80

# now curl to localhost:8080
sysuser@ubuntuprod:~/git/ldk (master -> origin/master)$ curl localhost:8080

# output
<!DOCTYPE html>
<html>
<head>
<title>Welcome to nginx!</title>
<style>
html { color-scheme: light dark; }
body { width: 35em; margin: 0 auto;
font-family: Tahoma, Verdana, Arial, sans-serif; }
</style>
</head>
<body>
<h1>Welcome to nginx!</h1>
<p>If you see this page, nginx is successfully installed and working.
Further configuration is required for the web server, reverse proxy, 
API gateway, load balancer, content cache, or other features.</p>

<p>For online documentation and support please refer to
<a href="https://nginx.org/">nginx.org</a>.<br/>
To engage with the community please visit
<a href="https://community.nginx.org/">community.nginx.org</a>.<br/>
For enterprise grade support, professional services, additional 
security features and capabilities please refer to
<a href="https://f5.com/nginx">f5.com/nginx</a>.</p>

<p><em>Thank you for using nginx.</em></p>
</body>
</html>

# another way to access the pod is by creating a curl pod.
sysuser@ubuntuprod:~/git/ldk (master -> origin/master)$ kubectl run -it --rm curlpod --image=curlimages/curl --restart=Never -- http://10.244.1.2

# output
<!DOCTYPE html>
<html>
<head>
<title>Welcome to nginx!</title>
<style>
html { color-scheme: light dark; }
body { width: 35em; margin: 0 auto;
font-family: Tahoma, Verdana, Arial, sans-serif; }
</style>
</head>
<body>
<h1>Welcome to nginx!</h1>
<p>If you see this page, nginx is successfully installed and working.
Further configuration is required for the web server, reverse proxy, 
API gateway, load balancer, content cache, or other features.</p>

<p>For online documentation and support please refer to
<a href="https://nginx.org/">nginx.org</a>.<br/>
To engage with the community please visit
<a href="https://community.nginx.org/">community.nginx.org</a>.<br/>
For enterprise grade support, professional services, additional 
security features and capabilities please refer to
<a href="https://f5.com/nginx">f5.com/nginx</a>.</p>

<p><em>Thank you for using nginx.</em></p>
</body>
</html>
pod "curlpod" deleted from default namespace

# run ubuntu pod and let it run in the background
sysuser@ubuntuprod:~/git/ldk (master -> origin/master)$ kubectl run --image=ubuntu ubuntupod sleep infinity

# output
pod/ubuntupod created

# shell into the ubuntupod
sysuser@ubuntuprod:~/git/ldk (master -> origin/master)$ kubectl exec -it ubuntupod -- bash

# run the following command to update apt, install curl and curl the pod IP
root@ubuntupod:/# apt update && apt install curl -y && curl 10.244.1.2

# output
Hit:1 http://archive.ubuntu.com/ubuntu resolute InRelease
Hit:2 http://security.ubuntu.com/ubuntu resolute-security InRelease
Hit:3 http://archive.ubuntu.com/ubuntu resolute-updates InRelease
Hit:4 http://archive.ubuntu.com/ubuntu resolute-backports InRelease
5 packages can be upgraded. Run 'apt list --upgradable' to see them.
curl is already the newest version (8.18.0-1ubuntu2.1).
Summary:                    
  Upgrading: 0, Installing: 0, Removing: 0, Not Upgrading: 5
<!DOCTYPE html>
<html>
<head>
<title>Welcome to nginx!</title>
<style>
html { color-scheme: light dark; }
body { width: 35em; margin: 0 auto;
font-family: Tahoma, Verdana, Arial, sans-serif; }
</style>
</head>
<body>
<h1>Welcome to nginx!</h1>
<p>If you see this page, nginx is successfully installed and working.
Further configuration is required for the web server, reverse proxy, 
API gateway, load balancer, content cache, or other features.</p>

<p>For online documentation and support please refer to
<a href="https://nginx.org/">nginx.org</a>.<br/>
To engage with the community please visit
<a href="https://community.nginx.org/">community.nginx.org</a>.<br/>
For enterprise grade support, professional services, additional 
security features and capabilities please refer to
<a href="https://f5.com/nginx">f5.com/nginx</a>.</p>

<p><em>Thank you for using nginx.</em></p>
</body>
</html>

# create nginx pod yaml spec
sysuser@ubuntuprod:~/git/ldk/kcna/prestige2/01-pods (master -> origin/master)$ kubectl run nginxpod --image=nginx --dry-run=client -o yaml | tee nginxpod.yaml

# output
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginxpod
  name: nginxpod
spec:
  containers:
  - image: nginx
    name: nginxpod
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}

# create a namespace kcna
sysuser@ubuntuprod:~/git/ldk/kcna/prestige2/01-pods (master -> origin/master)$ kubectl create namespace kcna

# output
namespace/kcna created

# apply the pod
sysuser@ubuntuprod:~/git/ldk/kcna/prestige2/01-pods (master -> origin/master)$ kubectl apply -f nginxpod.yaml -n kcna

# create a ubuntu pod yaml spec
sysuser@ubuntuprod:~/git/ldk/kcna/prestige2/01-pods (master -> origin/master)$ kubectl run --image=ubuntu --dry-run=client -o yaml ubuntupod sleep infinity | tee ubuntupod.yaml

# apply the pod
sysuser@ubuntuprod:~/git/ldk/kcna/prestige2/01-pods (master -> origin/master)$ kubectl apply -f ubuntupod.yaml -n kcna

# output
pod/ubuntupod created

# combine both the pods into one pod spec. this will create two pods at the same time
sysuser@ubuntuprod:~/git/ldk/kcna/prestige2/01-pods (master -> origin/master)$ { cat nginxpod.yaml; echo "---"; cat ubuntupod.yaml; } | tee ubuntunginxpod.yaml

# apply the pod spec
sysuser@ubuntuprod:~/git/ldk/kcna/prestige2/01-pods (master -> origin/master)$ kubectl apply -f ubuntunginxpod.yaml -n kcna

# output
pod/nginxpod created
pod/ubuntupod created

# delete both the pods
sysuser@ubuntuprod:~/git/ldk/kcna/prestige2/01-pods (master -> origin/master)$ kubectl delete -f ubuntunginxpod.yaml -n kcna --now

