apiVersion: v1
kind: Pod
metadata:
  labels:
    run: ubuntupod
  name: ubuntupod
  namespace: myns
spec:
  #schedulerName: none # this scheduler does not exist
  containers:
  - args:
    - /bin/sh
    - -c
    - for i in $(seq 0 1 1000000); do echo "$i"; sleep 1; done
    image: ubuntu
    name: ubuntupod1
    resources: {}
  - args:
    - /bin/sh
    - -c
    - sleep 30; for i in $(seq 0 1 1000000); do echo "$i"; sleep 1; done
    image: ubuntu
    name: ubuntupod2
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
