apiVersion: v1
kind: Pod
metadata:
  labels:
    run: ubuntupod
  name: ubuntupod
  namespace: myns
spec:
  #schedulerName: none # this scheduler does not exist
  containers:
  - args:
    - /bin/sh
    - -c
    - for i in $(seq 0 1 10000000000); do echo "$i"; sleep 0.1; done
    image: ubuntu
    name: ubuntupod
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
