# taints are applied to nodes. pods that do not have matching tolerations are not accepted
# tolerations are applied to pods. this allows them to be scheduled on nodes with matching taints.

# control plane on kind cluster has a taint so no pods will be scheduled on this node.
sysuser@ubuntuprod:~/git/ldk/k8s/16-taints-tolerations (master -> origin/master)$ kubectl describe node/klc-control-plane > klc-control-plane.json && kubectl describe node/klc-control-plane | grep Taints

# output
Taints:             node-role.kubernetes.io/control-plane:NoSchedule

# remove the taint
sysuser@ubuntuprod:~/git/ldk/k8s/16-taints-tolerations (master -> origin/master)$ kubectl taint node klc-control-plane node-role.kubernetes.io/control-plane:NoSchedule-

# output
node/klc-control-plane untainted

# add taint back
sysuser@ubuntuprod:~/git/ldk/k8s/16-taints-tolerations (master -> origin/master)$ kubectl taint node klc-control-plane node-role.kubernetes.io/control-plane:NoSchedule

# output
node/klc-control-plane tainted

# create a taint
sysuser@ubuntuprod:~/git/ldk/k8s/16-taints-tolerations (master -> origin/master)$ kubectl taint node klc-worker custom-taint1:NoSchedule

# output
node/klc-worker tainted

# describe node
sysuser@ubuntuprod:~/git/ldk/k8s/16-taints-tolerations (master -> origin/master)$ kubectl describe node/klc-worker | grep Taints

# output
Taints:             custom-taint1:NoSchedule

# create deployment
sysuser@ubuntuprod:~/git/ldk/k8s/16-taints-tolerations (master -> origin/master)$ kubectl create deployment test-taint --image=nginx --dry-run=client -o yaml | tee test-taint-base.yaml && cp test-taint-base.yaml test-taint-modified.yaml

# output
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: test-taint
  name: test-taint
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-taint
  strategy: {}
  template:
    metadata:
      labels:
        app: test-taint
    spec:
      containers:
      - image: nginx
        name: nginx
        resources: {}
status: {}

# apply the file and get the deployment and pods. it is pending because the node has a taint
sysuser@ubuntuprod:~/git/ldk/k8s/16-taints-tolerations (master -> origin/master)$ kubectl apply -f test-taint-modified.yaml && echo "---DEPLOYMENT---" && kubectl get deployment -o wide && echo "---PODS---" && kubectl get pods -o wide

# output
deployment.apps/test-taint created
---DEPLOYMENT---
NAME         READY   UP-TO-DATE   AVAILABLE   AGE   CONTAINERS   IMAGES   SELECTOR
test-taint   0/1     1            0           0s    nginx        nginx    app=test-taint
---PODS---
NAME                         READY   STATUS    RESTARTS   AGE   IP       NODE     NOMINATED NODE   READINESS GATES
test-taint-7cf87658d-6t2m4   0/1     Pending   0          0s    <none>   <none>   <none>           <none>

# add toleration and apply the file
sysuser@ubuntuprod:~/git/ldk/k8s/16-taints-tolerations (master -> origin/master)$ kubectl apply -f test-taint-toleration.yaml && sleep 2 && echo "---DEPLOYMENT---" && kubectl get deployment -o wide && echo "---PODS---" && kubectl get pods -o wide

# output
deployment.apps/test-taint configured
---DEPLOYMENT---
NAME         READY   UP-TO-DATE   AVAILABLE   AGE     CONTAINERS   IMAGES   SELECTOR
test-taint   0/1     1            0           4m14s   nginx        nginx    app=test-taint
---PODS---
NAME                          READY   STATUS    RESTARTS   AGE   IP           NODE         NOMINATED NODE   READINESS GATES
test-taint-564658ff48-x847s   1/1     Running   0          2s    10.244.1.5   klc-worker   <none>           <none>

# create custom taint 2
sysuser@ubuntuprod:~/git/ldk/k8s/16-taints-tolerations (master -> origin/master)$ kubectl taint node klc-worker custom-taint2=strict:NoExecute

# output
node/klc-worker tainted

# describe the node
sysuser@ubuntuprod:~/git/ldk/k8s/16-taints-tolerations (master -> origin/master)$ kubectl describe node/klc-worker | grep Taints

# output
Taints:             custom-taint2=strict:NoExecute

# get pods
sysuser@ubuntuprod:~/git/ldk/k8s/16-taints-tolerations (master -> origin/master)$ kubectl get pods -o wide

# output
NAME                          READY   STATUS    RESTARTS   AGE     IP       NODE     NOMINATED NODE   READINESS GATES
test-taint-564658ff48-sdqtj   0/1     Pending   0          2m13s   <none>   <none>   <none>           <none>

# modify the deployment to add new toleration to the pod
sysuser@ubuntuprod:~/git/ldk/k8s/16-taints-tolerations (master -> origin/master)$ kubectl apply -f test-taint-toleration2.yaml && sleep 2 && echo "---DEPLOYMENT---" && kubectl get deployment -o wide && echo "---PODS---" && kubectl get pods -o wide

# output
deployment.apps/test-taint configured
---DEPLOYMENT---
NAME         READY   UP-TO-DATE   AVAILABLE   AGE   CONTAINERS   IMAGES   SELECTOR
test-taint   1/1     1            1           13m   nginx        nginx    app=test-taint
---PODS---
NAME                          READY   STATUS    RESTARTS   AGE   IP           NODE         NOMINATED NODE   READINESS GATES
test-taint-77647667d7-5qc5v   1/1     Running   0          2s    10.244.1.6   klc-worker   <none>           <none>

# check the taints on all the nodes and delete them as needed
sysuser@ubuntuprod:~/git/ldk/k8s/17-affinity (master -> origin/master)$ kubectl describe nodes | grep -A3 Taints

# output
Taints:             node-role.kubernetes.io/control-plane:NoSchedule
Unschedulable:      false
Lease:
  HolderIdentity:  klc-control-plane
--
Taints:             custom-taint2=strict:NoExecute
                    custom-taint1:NoSchedule
Unschedulable:      false
Lease:
--
Taints:             <none>
Unschedulable:      false
Lease:
  HolderIdentity:  klc-worker2

# remove taint
sysuser@ubuntuprod:~/git/ldk/k8s/17-affinity (master -> origin/master)$ kubectl taint node klc-worker custom-taint1:NoSchedule-
node/klc-worker untainted

# remove taint
sysuser@ubuntuprod:~/git/ldk/k8s/17-affinity (master -> origin/master)$ kubectl taint node klc-worker custom-taint2=strict:NoExecute-
node/klc-worker untainted
