apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: test-taint
  name: test-taint
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-taint
  strategy: {}
  template:
    metadata:
      labels:
        app: test-taint
    spec:
      nodeSelector:
        kubernetes.io/hostname: klc-worker
      tolerations:
      - key: "custom-taint1" # this is the name of the taint created earlier
        operator: "Exists"
        effect: "NoSchedule"
      - key: "custom-taint2"
        operator: "Equal"
        value: "strict"
        effect: "NoExecute"
      containers:
      - image: nginx
        name: nginx
