# create a secret. values are base64 encoded - not encrypted. stored in etcd.
sysuser@ubuntuprod:~/git/ldk/k8s/09-secrets (master -> origin/master)$ kubectl create secret generic colorsecret --from-literal=color=red --from-literal=key=value -o yaml | tee colorsecret.yaml

# output
apiVersion: v1
data:
  color: cmVk
  key: dmFsdWU=
kind: Secret
metadata:
  creationTimestamp: "2026-06-22T11:08:16Z"
  name: colorsecret
  namespace: myns
  resourceVersion: "253390"
  uid: 835f542e-31e3-4173-94cc-922d9d292d10
type: Opaque


# if we encode the word 'value' and 'red' to base64 the results would match the secret
sysuser@ubuntuprod:~/git/ldk/k8s/09-secrets (master -> origin/master)$ echo -n red | base64 && echo -n value | base64

# output
cmVk
dmFsdWU=

# create an ubuntupod and manually modify it to add secretRef
sysuser@ubuntuprod:~/git/ldk/k8s/09-secrets (master -> origin/master)$ kubectl run ubuntupod --image=ubuntu --dry-run=client -o yaml --command bash -- -c 'env; sleep infinity' | tee ubuntupod.yaml

# output
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: ubuntupod
  name: ubuntupod
spec:
  containers:
  - command:
    - bash
    - -c
    - env; sleep infinity
    image: ubuntu
    name: ubuntupod
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}

# create a modified yaml file and add secretref and apply it
sysuser@ubuntuprod:~/git/ldk/k8s/09-secrets (master -> origin/master)$ kubectl apply -f ubuntupod-colorsecret.yaml && sleep 5 && echo "--SECRET--" && kubectl get secret -o wide && echo "--PODS--" && kubectl get pods -o wide && echo "--LOGS--" && kubectl logs pod/ubuntupod

# output
pod/ubuntupod created
--SECRET--
NAME          TYPE     DATA   AGE
colorsecret   Opaque   2      8m27s
--PODS--
NAME        READY   STATUS    RESTARTS   AGE   IP             NODE         NOMINATED NODE   READINESS GATES
ubuntupod   1/1     Running   0          6s    10.244.1.144   klc-worker   <none>           <none>
--LOGS--
KUBERNETES_SERVICE_PORT_HTTPS=443
KUBERNETES_SERVICE_PORT=443
HOSTNAME=ubuntupod
color=red
PWD=/
HOME=/root
KUBERNETES_PORT_443_TCP=tcp://10.96.0.1:443
key=value
SHLVL=1
KUBERNETES_PORT_443_TCP_PROTO=tcp
KUBERNETES_PORT_443_TCP_ADDR=10.96.0.1
KUBERNETES_SERVICE_HOST=10.96.0.1
KUBERNETES_PORT=tcp://10.96.0.1:443
KUBERNETES_PORT_443_TCP_PORT=443
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
_=/usr/bin/env
