apiVersion: v1
data:
  color: cmVk
  key: dmFsdWU=
kind: Secret
metadata:
  creationTimestamp: "2026-06-22T11:08:16Z"
  name: colorsecret
  namespace: myns
  resourceVersion: "253390"
  uid: 835f542e-31e3-4173-94cc-922d9d292d10
type: Opaque
