# For voluntary disruptions. pdb != replicas

# create myns namespace and set that to the current context if not already. 
sysuser@ubuntuprod:~/git/ldk/k8s/23-pod-disruption-budget (master -> origin/master)$ kubectl create namespace myns && kubectl config set-context --current --namespace=myns && kubectl get all

# output
namespace/myns created
Context "kind-klc" modified.
No resources found in myns namespace.

# Create a deployment with 5 replicas and apply it. 
sysuser@ubuntuprod:~/git/ldk/k8s/23-pod-disruption-budget (master -> origin/master)$ kubectl create deployment nginxdep --image=nginx --replicas=5 --dry-run=client -o yaml | tee nginxdep-base.yaml && kubectl apply -f nginxdep-base.yaml && sleep 7 && echo "---PODS---" && kubectl get pods -o wide

# output
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginxdep
  name: nginxdep
spec:
  replicas: 5
  selector:
    matchLabels:
      app: nginxdep
  strategy: {}
  template:
    metadata:
      labels:
        app: nginxdep
    spec:
      containers:
      - image: nginx
        name: nginx
        resources: {}
status: {}
deployment.apps/nginxdep created
---PODS---
NAME                        READY   STATUS    RESTARTS   AGE   IP            NODE          NOMINATED NODE   READINESS GATES
nginxdep-5f4d9669f8-jjs4k   1/1     Running   0          7s    10.244.1.10   klc-worker    <none>           <none>
nginxdep-5f4d9669f8-vcckh   1/1     Running   0          7s    10.244.2.7    klc-worker2   <none>           <none>
nginxdep-5f4d9669f8-vjdwd   1/1     Running   0          7s    10.244.1.9    klc-worker    <none>           <none>
nginxdep-5f4d9669f8-vsthx   1/1     Running   0          7s    10.244.1.8    klc-worker    <none>           <none>
nginxdep-5f4d9669f8-vsts6   1/1     Running   0          7s    10.244.2.8    klc-worker2   <none>           <none>

# cordon klc-worker node. delete pods on that node. they will end up on klc-worker2
sysuser@ubuntuprod:~/git/ldk/k8s/23-pod-disruption-budget (master -> origin/master)$ kubectl cordon klc-worker && kubectl delete pod/nginxdep-5f4d9669f8-jjs4k pod/nginxdep-5f4d9669f8-vjdwd pod/nginxdep-5f4d9669f8-vsthx

# output
node/klc-worker cordoned
pod "nginxdep-5f4d9669f8-jjs4k" deleted from myns namespace
pod "nginxdep-5f4d9669f8-vjdwd" deleted from myns namespace
pod "nginxdep-5f4d9669f8-vsthx" deleted from myns namespace

# new pods are created
sysuser@ubuntuprod:~/git/ldk/k8s/23-pod-disruption-budget (master -> origin/master)$ kubectl get pods -o wide

# output
NAME                        READY   STATUS    RESTARTS   AGE     IP            NODE          NOMINATED NODE   READINESS GATES
nginxdep-5f4d9669f8-sx6bx   1/1     Running   0          20s     10.244.2.11   klc-worker2   <none>           <none>
nginxdep-5f4d9669f8-t5rds   1/1     Running   0          20s     10.244.2.10   klc-worker2   <none>           <none>
nginxdep-5f4d9669f8-ttbwp   1/1     Running   0          20s     10.244.2.9    klc-worker2   <none>           <none>
nginxdep-5f4d9669f8-vcckh   1/1     Running   0          2m37s   10.244.2.7    klc-worker2   <none>           <none>
nginxdep-5f4d9669f8-vsts6   1/1     Running   0          2m37s   10.244.2.8    klc-worker2   <none>           <none>

# what happens when klc-worker2 is offline. we will drain klc-worker2 and delete empty dir data and ignore daemonsets
sysuser@ubuntuprod:~/git/ldk/k8s/23-pod-disruption-budget (master -> origin/master)$ kubectl drain klc-worker2 --delete-emptydir-data=true --ignore-daemonsets=true

# output
node/klc-worker2 cordoned
Warning: ignoring DaemonSet-managed Pods: kube-system/kindnet-8f9sr, kube-system/kube-proxy-dh4qg
evicting pod myns/nginxdep-5f4d9669f8-vsts6
evicting pod myns/nginxdep-5f4d9669f8-t5rds
evicting pod myns/nginxdep-5f4d9669f8-sx6bx
evicting pod myns/nginxdep-5f4d9669f8-ttbwp
evicting pod myns/nginxdep-5f4d9669f8-vcckh
pod/nginxdep-5f4d9669f8-t5rds evicted
pod/nginxdep-5f4d9669f8-vsts6 evicted
pod/nginxdep-5f4d9669f8-ttbwp evicted
pod/nginxdep-5f4d9669f8-sx6bx evicted
pod/nginxdep-5f4d9669f8-vcckh evicted
node/klc-worker2 drained

# get deployments. this is a full outage
sysuser@ubuntuprod:~/git/ldk/k8s/23-pod-disruption-budget (master -> origin/master)$ kubectl get deployment -o wide && echo "---PODS---" && kubectl get pods -o wide

# output
NAME       READY   UP-TO-DATE   AVAILABLE   AGE     CONTAINERS   IMAGES   SELECTOR
nginxdep   0/5     5            0           6m13s   nginx        nginx    app=nginxdep
---PODS---
NAME                        READY   STATUS    RESTARTS   AGE   IP       NODE     NOMINATED NODE   READINESS GATES
nginxdep-5f4d9669f8-9drr7   0/1     Pending   0          77s   <none>   <none>   <none>           <none>
nginxdep-5f4d9669f8-bdfgr   0/1     Pending   0          77s   <none>   <none>   <none>           <none>
nginxdep-5f4d9669f8-nwxx9   0/1     Pending   0          77s   <none>   <none>   <none>           <none>
nginxdep-5f4d9669f8-sgfhv   0/1     Pending   0          77s   <none>   <none>   <none>           <none>
nginxdep-5f4d9669f8-zn2tf   0/1     Pending   0          77s   <none>   <none>   <none>           <none>

# uncordon both the nodes
sysuser@ubuntuprod:~/git/ldk/k8s/23-pod-disruption-budget (master -> origin/master)$ kubectl uncordon klc-worker klc-worker2

# output
node/klc-worker uncordoned
node/klc-worker2 uncordoned

# get pods
sysuser@ubuntuprod:~/git/ldk/k8s/23-pod-disruption-budget (master -> origin/master)$ kubectl get pods -o wide

# output
NAME                        READY   STATUS    RESTARTS   AGE   IP            NODE         NOMINATED NODE   READINESS GATES
nginxdep-5f4d9669f8-9drr7   1/1     Running   0          45m   10.244.1.14   klc-worker   <none>           <none>
nginxdep-5f4d9669f8-bdfgr   1/1     Running   0          45m   10.244.1.12   klc-worker   <none>           <none>
nginxdep-5f4d9669f8-nwxx9   1/1     Running   0          45m   10.244.1.13   klc-worker   <none>           <none>
nginxdep-5f4d9669f8-sgfhv   1/1     Running   0          45m   10.244.1.11   klc-worker   <none>           <none>
nginxdep-5f4d9669f8-zn2tf   1/1     Running   0          45m   10.244.1.15   klc-worker   <none>           <none>

# get lables for deployment
sysuser@ubuntuprod:~/git/ldk/k8s/23-pod-disruption-budget (master -> origin/master)$ kubectl get deployment --show-labels

# output
NAME       READY   UP-TO-DATE   AVAILABLE   AGE   LABELS
nginxdep   5/5     5            5           52m   app=nginxdep


# use pod disruption budget to set minimum available pods. use label app=nginxdep
sysuser@ubuntuprod:~/git/ldk/k8s/23-pod-disruption-budget (master -> origin/master)$ kubectl create pdb nginxpdb --selector=app=nginxdep --min-available=2 --dry-run=client -o yaml | tee nginxpdb-base.yaml

# output
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: nginxpdb
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: nginxdep
status:
  currentHealthy: 0
  desiredHealthy: 0
  disruptionsAllowed: 0
  expectedPods: 0

# apply the file
sysuser@ubuntuprod:~/git/ldk/k8s/23-pod-disruption-budget (master -> origin/master)$ kubectl apply -f nginxpdb-base.yaml 

# output
poddisruptionbudget.policy/nginxpdb created

# cordon and drain both the nodes
sysuser@ubuntuprod:~/git/ldk/k8s/23-pod-disruption-budget (master -> origin/master)$ kubectl cordon klc-worker klc-worker2 && kubectl drain klc-worker klc-worker2 --delete-emptydir-data=true --ignore-daemonsets=true

# output
node/klc-worker cordoned
node/klc-worker2 cordoned
node/klc-worker already cordoned
node/klc-worker2 already cordoned
Warning: ignoring DaemonSet-managed Pods: kube-system/kindnet-px275, kube-system/kube-proxy-nj65k
evicting pod myns/nginxdep-5f4d9669f8-zn2tf
evicting pod myns/nginxdep-5f4d9669f8-9drr7
evicting pod myns/nginxdep-5f4d9669f8-nwxx9
evicting pod myns/nginxdep-5f4d9669f8-sgfhv
evicting pod myns/nginxdep-5f4d9669f8-bdfgr
pod/nginxdep-5f4d9669f8-9drr7 evicted
error when evicting pods/"nginxdep-5f4d9669f8-sgfhv" -n "myns" (will retry after 5s): Cannot evict pod as it would violate the pod's disruption budget.
error when evicting pods/"nginxdep-5f4d9669f8-bdfgr" -n "myns" (will retry after 5s): Cannot evict pod as it would violate the pod's disruption budget.
pod/nginxdep-5f4d9669f8-zn2tf evicted
pod/nginxdep-5f4d9669f8-nwxx9 evicted
evicting pod myns/nginxdep-5f4d9669f8-sgfhv
error when evicting pods/"nginxdep-5f4d9669f8-sgfhv" -n "myns" (will retry after 5s): Cannot evict pod as it would violate the pod's disruption budget.
evicting pod myns/nginxdep-5f4d9669f8-bdfgr
error when evicting pods/"nginxdep-5f4d9669f8-bdfgr" -n "myns" (will retry after 5s): Cannot evict pod as it would violate the pod's disruption budget.
evicting pod myns/nginxdep-5f4d9669f8-sgfhv
error when evicting pods/"nginxdep-5f4d9669f8-sgfhv" -n "myns" (will retry after 5s): Cannot evict pod as it would violate the pod's disruption budget.
evicting pod myns/nginxdep-5f4d9669f8-bdfgr
error when evicting pods/"nginxdep-5f4d9669f8-bdfgr" -n "myns" (will retry after 5s): Cannot evict pod as it would violate the pod's disruption budget.
evicting pod myns/nginxdep-5f4d9669f8-sgfhv
error when evicting pods/"nginxdep-5f4d9669f8-sgfhv" -n "myns" (will retry after 5s): Cannot evict pod as it would violate the pod's disruption budget.
evicting pod myns/nginxdep-5f4d9669f8-bdfgr
error when evicting pods/"nginxdep-5f4d9669f8-bdfgr" -n "myns" (will retry after 5s): Cannot evict pod as it would violate the pod's disruption budget.
evicting pod myns/nginxdep-5f4d9669f8-sgfhv
error when evicting pods/"nginxdep-5f4d9669f8-sgfhv" -n "myns" (will retry after 5s): Cannot evict pod as it would violate the pod's disruption budget.
evicting pod myns/nginxdep-5f4d9669f8-bdfgr
error when evicting pods/"nginxdep-5f4d9669f8-bdfgr" -n "myns" (will retry after 5s): Cannot evict pod as it would violate the pod's disruption budget.


# in a new terminal window, uncordon klc-worker
sysuser@ubuntuprod:~/git/ldk/k8s/23-pod-disruption-budget (master -> origin/master)$ kubectl uncordon klc-worker

# output
node/klc-worker uncordoned

# switch back to the previous terminal window
# sysuser@ubuntuprod:~/git/ldk/k8s/23-pod-disruption-budget (master -> origin/master)$ kubectl cordon klc-worker klc-worker2 && kubectl drain klc-worker klc-worker2 --delete-emptydir-data=true --ignore-daemonsets=true

# output
error when evicting pods/"nginxdep-5f4d9669f8-sgfhv" -n "myns" (will retry after 5s): Cannot evict pod as it would violate the pod's disruption budget.
evicting pod myns/nginxdep-5f4d9669f8-bdfgr
error when evicting pods/"nginxdep-5f4d9669f8-bdfgr" -n "myns" (will retry after 5s): Cannot evict pod as it would violate the pod's disruption budget.
evicting pod myns/nginxdep-5f4d9669f8-sgfhv
evicting pod myns/nginxdep-5f4d9669f8-bdfgr
pod/nginxdep-5f4d9669f8-bdfgr evicted
pod/nginxdep-5f4d9669f8-sgfhv evicted
node/klc-worker drained
Warning: ignoring DaemonSet-managed Pods: kube-system/kindnet-8f9sr, kube-system/kube-proxy-dh4qg
node/klc-worker2 drained

# get pods
sysuser@ubuntuprod:~/git/ldk/k8s/23-pod-disruption-budget (master -> origin/master)$ kubectl get pods -o wide 

# output
NAME                        READY   STATUS    RESTARTS   AGE     IP            NODE         NOMINATED NODE   READINESS GATES
nginxdep-5f4d9669f8-6brl5   1/1     Running   0          2m32s   10.244.1.17   klc-worker   <none>           <none>
nginxdep-5f4d9669f8-dxcf9   1/1     Running   0          2m32s   10.244.1.16   klc-worker   <none>           <none>
nginxdep-5f4d9669f8-kngk9   1/1     Running   0          96s     10.244.1.20   klc-worker   <none>           <none>
nginxdep-5f4d9669f8-lwl2m   1/1     Running   0          2m32s   10.244.1.18   klc-worker   <none>           <none>
nginxdep-5f4d9669f8-pvzc2   1/1     Running   0          96s     10.244.1.19   klc-worker   <none>           <none>
