# create the deployment and tee it to a file, and then change the container name
sysuser@ubuntuprod:~/git/ldk/k8s/06-services/clusterip (master -> origin/master)$ kubectl create deployment nginxdep --image=spurin/nginx-debug --port=80 --replicas=3 -o yaml --dry-run=client | tee nginxdep.yaml

# apply the deployment and expose it and tee it to a file
sysuser@ubuntuprod:~/git/ldk/k8s/06-services/clusterip (master -> origin/master)$ kubectl apply -f nginxdep.yaml && kubectl expose deployment/nginxdep --dry-run=client -o yaml | tee nginxcip.yaml

# output
deployment.apps/nginxdep created
apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginxdep
  name: nginxdep
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginxdep
status:
  loadBalancer: {}

# apply the file and get the services
sysuser@ubuntuprod:~/git/ldk/k8s/06-services/clusterip (master -> origin/master)$ kubectl apply -f nginxcip.yaml && kubectl get svc -o wide

# output
service/nginxdep created
NAME       TYPE        CLUSTER-IP     EXTERNAL-IP   PORT(S)   AGE   SELECTOR
nginxdep   ClusterIP   10.96.160.87   <none>        80/TCP    0s    app=nginxdep

# get the endpoint slices.
sysuser@ubuntuprod:~/git/ldk/k8s/06-services/clusterip (master -> origin/master)$ kubectl get EndpointSlice -o wide

# output. the endpoints are the IPs of pods
NAME             ADDRESSTYPE   PORTS   ENDPOINTS                             AGE
nginxdep-cqtqb   IPv4          80      10.244.2.52,10.244.1.57,10.244.1.56   2m4s

# get the pods
sysuser@ubuntuprod:~/git/ldk/k8s/06-services/clusterip (master -> origin/master)$ kubectl get pods -o wide

# output
NAME                        READY   STATUS    RESTARTS   AGE   IP            NODE          NOMINATED NODE   READINESS GATES
nginxdep-6489db6bc9-9smnr   1/1     Running   0          23m   10.244.2.52   klc-worker2   <none>           <none>
nginxdep-6489db6bc9-cqxdh   1/1     Running   0          23m   10.244.1.57   klc-worker    <none>           <none>
nginxdep-6489db6bc9-lkzqr   1/1     Running   0          23m   10.244.1.56   klc-worker    <none>           <none>

# curl the cluster ip 
sysuser@ubuntuprod:~/git/ldk/k8s/06-services/clusterip (master -> origin/master)$ kubectl run -it --rm curlpod --image=curlimages/curl --restart=Never -- sh

# inside the curl pod, run the following. this will hit one of the pod IPs each time it the curl command is executed
~ $ watch curl 10.96.160.87

# also possible to port forward
sysuser@ubuntuprod:~/git/ldk/k8s/06-services/clusterip (master -> origin/master)$ kubectl port-forward service/nginxdep 8080:80

# curl localhost:8080
sysuser@ubuntuprod:~/git/ldk/k8s/06-services/clusterip (master -> origin/master)$ watch curl localhost:8080

# it is possible to also use dns name within the cluster. we can curl the dns name of the service
sysuser@ubuntuprod:~/git/ldk/k8s/06-services/clusterip (master -> origin/master)$ kubectl run -it --rm curlpod --image=curlimages/curl --restart=Never -- sh

# inside the curl pod query the dns name of the service
~ $ curl nginxdep.myns.svc.cluster.local

# output
<!DOCTYPE html>
<body>
<p><em>Hostname: nginxdep-6489db6bc9-lkzqr</em></p>
<p><em>IP Address: 10.244.1.56:80</em></p>
<p><em>URL: /</em></p>
<p><em>Request Method: GET</em></p>
<p><em>Request ID: 1910eeed984144dc13cb992a9f5fab60</em></p>
</body>
</html>

# search path of the request can found from within the curlpod
~ $ cat /etc/resolv.conf

# output
search myns.svc.cluster.local svc.cluster.local cluster.local localdomain
nameserver 10.96.0.10
options ndots:5

# this will also work
~ $ curl nginxdep

### NODE PORT ###

# delete the cluster ip service
sysuser@ubuntuprod:~/git/ldk/k8s/06-services/nodeport (master -> origin/master)$ kubectl delete service/nginxdep --now

# now expose the deploymennt as a node port
sysuser@ubuntuprod:~/git/ldk/k8s/06-services/nodeport (master -> origin/master)$ kubectl expose deployment/nginxdep --type=NodePort && kubectl get svc -o wide

# output
service/nginxdep exposed
NAME       TYPE       CLUSTER-IP     EXTERNAL-IP   PORT(S)        AGE   SELECTOR
nginxdep   NodePort   10.96.207.66   <none>        80:32545/TCP   0s    app=nginxdep

# get nodes
sysuser@ubuntuprod:~/git/ldk/k8s/06-services/nodeport (master -> origin/master)$ kubectl get nodes -o wide

# output
NAME                STATUS   ROLES           AGE   VERSION   INTERNAL-IP   EXTERNAL-IP   OS-IMAGE                         KERNEL-VERSION     CONTAINER-RUNTIME
klc-control-plane   Ready    control-plane   11h   v1.35.0   172.18.0.3    <none>        Debian GNU/Linux 12 (bookworm)   7.0.0-22-generic   containerd://2.2.0
klc-worker          Ready    <none>          11h   v1.35.0   172.18.0.2    <none>        Debian GNU/Linux 12 (bookworm)   7.0.0-22-generic   containerd://2.2.0
klc-worker2         Ready    <none>          11h   v1.35.0   172.18.0.4    <none>        Debian GNU/Linux 12 (bookworm)   7.0.0-22-generic   containerd://2.2.0

# get pods
sysuser@ubuntuprod:~/git/ldk/k8s/06-services/nodeport (master -> origin/master)$ kubectl get pods -o wide

# output
NAME                        READY   STATUS    RESTARTS   AGE     IP            NODE          NOMINATED NODE   READINESS GATES
nginxdep-6489db6bc9-7kd74   1/1     Running   0          4m52s   10.244.1.59   klc-worker    <none>           <none>
nginxdep-6489db6bc9-kzwdh   1/1     Running   0          4m52s   10.244.1.58   klc-worker    <none>           <none>
nginxdep-6489db6bc9-r79sv   1/1     Running   0          4m52s   10.244.2.57   klc-worker2   <none>           <none>

# we can now curl the nodes with their internal ip and nodeport port from outside of the cluster
sysuser@ubuntuprod:~/git/ldk/k8s/06-services/nodeport (master -> origin/master)$ curl 172.18.0.3:32545

# output
<!DOCTYPE html>
<body>
<p><em>Hostname: nginxdep-6489db6bc9-7kd74</em></p>
<p><em>IP Address: 10.244.1.59:80</em></p>
<p><em>URL: /</em></p>
<p><em>Request Method: GET</em></p>
<p><em>Request ID: f4e43430741ba32922e26259cdab5c68</em></p>
</body>
</html>

# traffic sent to 172.18.0.3:32545.
# kube-proxy on the control-plane node intercepts it.
# It chooses one of the three healthy pods (using its load-balancing algorithm — often random or round-robin).
# It rewrites the destination IP to the chosen pod's IP (10.244.1.59:80 in your case) and forwards the packet over the pod network (CNI).
# The pod responds. The reply is sent back through the reverse path (with SNAT so the client sees a clean connection).
# The nginx container in the pod prints

### LOAD BALANCER ###

