# pods can be classified as isolated
# limit access to other pods, ip blocks

# create an nginx pod and expose it as a cluster ip service
sysuser@ubuntuprod:~/git/ldk/k8s/20-networkpolicies (master -> origin/master)$ kubectl run nginxpod --image=nginx && kubectl expose pod/nginxpod --port=80 && echo "---SVC---" && kubectl get svc -o wide

# output
pod/nginxpod created
service/nginxpod exposed
---SVC---
NAME       TYPE        CLUSTER-IP     EXTERNAL-IP   PORT(S)   AGE   SELECTOR
nginxpod   ClusterIP   10.96.252.91   <none>        80/TCP    0s    run=nginxpod

# run curlpod
sysuser@ubuntuprod:~/git/ldk/k8s/20-networkpolicies (master -> origin/master)$ kubectl run curlpod -it --image=curlimages/curl --rm --restart=Never -- sh

# output
All commands and output from this session will be recorded in container logs, including credentials and sensitive information passed through the command prompt.
If you don't see a command prompt, try pressing enter.

# nslookup
~ $ nslookup 10.96.252.91
Server:		10.96.0.10
Address:	10.96.0.10:53

91.252.96.10.in-addr.arpa	name = nginxpod.myns.svc.cluster.local

~ $ 


# curl endpoint
~ $ curl nginxpod.myns.svc.cluster.local
<!DOCTYPE html>
<html>
<head>
<title>Welcome to nginx!</title>
<style>
html { color-scheme: light dark; }
body { width: 35em; margin: 0 auto;
font-family: Tahoma, Verdana, Arial, sans-serif; }
</style>
</head>
<body>
<h1>Welcome to nginx!</h1>
<p>If you see this page, nginx is successfully installed and working.
Further configuration is required for the web server, reverse proxy, 
API gateway, load balancer, content cache, or other features.</p>

<p>For online documentation and support please refer to
<a href="https://nginx.org/">nginx.org</a>.<br/>
To engage with the community please visit
<a href="https://community.nginx.org/">community.nginx.org</a>.<br/>
For enterprise grade support, professional services, additional 
security features and capabilities please refer to
<a href="https://f5.com/nginx">f5.com/nginx</a>.</p>

<p><em>Thank you for using nginx.</em></p>
</body>
</html>
~ $ 

# apply network policy
sysuser@ubuntuprod:~/git/ldk/k8s/20-networkpolicies (master -> origin/master)$ kubectl apply -f nginxnp-ingress-network-policy.yaml && echo "---NETWORK-POLICY---" && kubectl get networkpolicies -o wide

# output
networkpolicy.networking.k8s.io/nginxnp created
---NETWORK-POLICY---
NAME      POD-SELECTOR   AGE
nginxnp   run=nginxpod   0s


# create a random curl pod
sysuser@ubuntuprod:~/git/ldk/k8s/20-networkpolicies (master -> origin/master)$ kubectl run random -it --image=curlimages/curl --rm --restart=Never -- sh
All commands and output from this session will be recorded in container logs, including credentials and sensitive information passed through the command prompt.
If you don't see a command prompt, try pressing enter.
~ $ 

# get pod labels in a new terminal window
sysuser@ubuntuprod:~/git/ldk/k8s/20-networkpolicies (master -> origin/master)$ kubectl get pods -n myns --show-labels
NAME       READY   STATUS    RESTARTS   AGE     LABELS
curlpod    1/1     Running   0          6m40s   run=curlpod
nginxpod   1/1     Running   0          8m8s    run=nginxpod
random     1/1     Running   0          4s      run=random

# curl from `random` pod should not work. it should still work from `curlpod`