# limit quantity of resources, number of pods, cpu, memory per namespace
sysuser@ubuntuprod:~/git/ldk/k8s/26-resource-quotas (master -> origin/master)$ kubectl create namespace limited

# output
namespace/limited created

# apply the resource quota
sysuser@ubuntuprod:~/git/ldk/k8s/26-resource-quotas (master -> origin/master)$ kubectl apply -f limited_rq.yaml

# output
resourcequota/limited created

# get resource quota
sysuser@ubuntuprod:~/git/ldk/k8s/26-resource-quotas (master -> origin/master)$ kubectl -n limited get resourcequota

# output
NAME      REQUEST                                                LIMIT                                   AGE
limited   pods: 0/3, requests.cpu: 0/1, requests.memory: 0/1Gi   limits.cpu: 0/2, limits.memory: 0/2Gi   69s

# apply limited_pods.yaml
sysuser@ubuntuprod:~/git/ldk/k8s/26-resource-quotas (master -> origin/master)$ kubectl apply -f limited_pods.yaml

# output
Error from server (Forbidden): error when creating "limited_pods.yaml": pods "red" is forbidden: failed quota: limited: must specify limits.cpu for: red; limits.memory for: red; requests.cpu for: red; requests.memory for: red
Error from server (Forbidden): error when creating "limited_pods.yaml": pods "green" is forbidden: failed quota: limited: must specify limits.cpu for: green; limits.memory for: green; requests.cpu for: green; requests.memory for: green
Error from server (Forbidden): error when creating "limited_pods.yaml": pods "blue" is forbidden: failed quota: limited: must specify limits.cpu for: blue; limits.memory for: blue; requests.cpu for: blue; requests.memory for: blue

# limited_pods2.yaml
sysuser@ubuntuprod:~/git/ldk/k8s/26-resource-quotas (master -> origin/master)$ kubectl apply -f limited_pods2.yaml

# output
pod/red created
pod/green created
pod/blue created

# get resourcequota
sysuser@ubuntuprod:~/git/ldk/k8s/26-resource-quotas (master -> origin/master)$ kubectl -n limited get resourcequota

# output
NAME      REQUEST                                                       LIMIT                                          AGE
limited   pods: 3/3, requests.cpu: 300m/1, requests.memory: 192Mi/1Gi   limits.cpu: 600m/2, limits.memory: 384Mi/2Gi   10m

# apply pod spec with an additional pod
sysuser@ubuntuprod:~/git/ldk/k8s/26-resource-quotas (master -> origin/master)$ kubectl apply -f limited_pods3.yaml

# output
pod/red unchanged
pod/green unchanged
pod/blue unchanged
Error from server (Forbidden): error when creating "limited_pods3.yaml": pods "pink" is forbidden: exceeded quota: limited, requested: pods=1, used: pods=3, limited: pods=3

# modify the resource quota
sysuser@ubuntuprod:~/git/ldk/k8s/26-resource-quotas (master -> origin/master)$ kubectl apply -f limited_rq2.yaml && kubectl -n limited get resourcequota

# output
resourcequota/limited configured
NAME      REQUEST                                                       LIMIT                                          AGE
limited   pods: 3/4, requests.cpu: 300m/1, requests.memory: 192Mi/1Gi   limits.cpu: 600m/2, limits.memory: 384Mi/2Gi   14m

# apply the pod spec file again
sysuser@ubuntuprod:~/git/ldk/k8s/26-resource-quotas (master -> origin/master)$ kubectl apply -f limited_pods3.yaml

# output
pod/red unchanged
pod/green unchanged
pod/blue unchanged
pod/pink created

# replace force 
sysuser@ubuntuprod:~/git/ldk/k8s/26-resource-quotas (master -> origin/master)$ kubectl replace --force -f limited_pods4.yaml

# output
pod "red" deleted from limited namespace
pod "green" deleted from limited namespace
pod "blue" deleted from limited namespace
pod "pink" deleted from limited namespace
pod/red replaced
pod/green replaced
pod/blue replaced
Error from server (Forbidden): pods "pink" is forbidden: exceeded quota: limited, requested: limits.cpu=4, used: limits.cpu=600m, limited: limits.cpu=2

# delete namespace to clean up