apiVersion: v1
kind: ResourceQuota
metadata:
  name: limited
  namespace: limited
spec:
  hard:
    requests.cpu: "1"
    requests.memory: "1Gi"
    limits.cpu: "2"
    limits.memory: "2Gi"
    pods: "3"