# declarative management of kubernetes objects. it is a kubectl sub command
# kustomize never edits source yaml. 

## This is running in default namespace. switch context accordingly. ##

# create base directory
sysuser@ubuntudev:~/git/ldk/k8s/28-kustomize (master -> origin/master)$ mkdir -p kustomize-demo/base

# create a deployment
sysuser@ubuntudev:~/git/ldk/k8s/28-kustomize/kustomize-demo (master -> origin/master)$ kubectl create deployment 

# output
nginxwebdep --image=nginx --port=80 --dry-run=client -o yaml | tee base/nginxwebdep.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginxwebdep
  name: nginxwebdep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginxwebdep
  strategy: {}
  template:
    metadata:
      labels:
        app: nginxwebdep
    spec:
      containers:
      - image: nginx
        name: nginx
        ports:
        - containerPort: 80
        resources: {}
status: {}

# apply the deployment
sysuser@ubuntudev:~/git/ldk/k8s/28-kustomize/kustomize-demo (master -> origin/master)$ kubectl apply -f base/nginxwebdep.yaml 

# output
deployment.apps/nginxwebdep created

# create a service yaml
sysuser@ubuntudev:~/git/ldk/k8s/28-kustomize/kustomize-demo (master -> origin/master)$ kubectl expose deployment nginxwebdep -o yaml --dry-run=client | tee base/nginxwebsvc.yaml

# output
apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginxwebdep
  name: nginxwebdep
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginxwebdep
status:

# delete the deployment at this point because we have the templates needed
sysuser@ubuntudev:~/git/ldk/k8s/28-kustomize/kustomize-demo (master -> origin/master)$ kubectl delete -f base/nginxwebdep.yaml 

# output
deployment.apps "nginxwebdep" deleted from default namespace

# create kustomization.yaml in the base directory and run kubectl kustomize
sysuser@ubuntudev:~/git/ldk/k8s/28-kustomize/kustomize-demo (master -> origin/master)$ kubectl kustomize base | tee base/kustomize-output.yaml

# output
apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginxwebdep
  name: finance-nginxwebdep
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginxwebdep
status:
  loadBalancer: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginxwebdep
  name: finance-nginxwebdep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginxwebdep
  strategy: {}
  template:
    metadata:
      labels:
        app: nginxwebdep
    spec:
      containers:
      - image: nginx
        name: nginx
        ports:
        - containerPort: 80
        resources: {}
status: {}

# either use the file to apply or use kustomize to apply the yaml output
sysuser@ubuntudev:~/git/ldk/k8s/28-kustomize/kustomize-demo (master -> origin/master)$ kubectl apply -k base

# output
service/finance-nginxwebdep created
deployment.apps/finance-nginxwebdep created

# perform a get on the resource created out of base
sysuser@ubuntudev:~/git/ldk/k8s/28-kustomize/kustomize-demo (master -> origin/master)$ kubectl get -k base

# output
NAME                          TYPE        CLUSTER-IP     EXTERNAL-IP   PORT(S)   AGE
service/finance-nginxwebdep   ClusterIP   10.96.18.216   <none>        80/TCP    82s

NAME                                  READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/finance-nginxwebdep   1/1     1            1           82s

# exec into the control plane (or another node) and curl the cluster ip
sysuser@ubuntudev:~/git/ldk/k8s/28-kustomize/kustomize-demo (master -> origin/master)$ docker exec -it klc-control-plane bash

# curl
root@klc-control-plane:/# curl 10.96.18.216

# output
<!DOCTYPE html>
<html>
<head>
<title>Welcome to nginx!</title>
<style>
html { color-scheme: light dark; }
body { width: 35em; margin: 0 auto;
font-family: Tahoma, Verdana, Arial, sans-serif; }
</style>
</head>
<body>
<h1>Welcome to nginx!</h1>
<p>If you see this page, nginx is successfully installed and working.
Further configuration is required for the web server, reverse proxy, 
API gateway, load balancer, content cache, or other features.</p>

<p>For online documentation and support please refer to
<a href="https://nginx.org/">nginx.org</a>.<br/>
To engage with the community please visit
<a href="https://community.nginx.org/">community.nginx.org</a>.<br/>
For enterprise grade support, professional services, additional 
security features and capabilities please refer to
<a href="https://f5.com/nginx">f5.com/nginx</a>.</p>

<p><em>Thank you for using nginx.</em></p>
</body>
</html>

# delete resources
sysuser@ubuntudev:~/git/ldk/k8s/28-kustomize/kustomize-demo (master -> origin/master)$ kubectl delete -k base

# output
service "finance-nginxwebdep" deleted from default namespace
deployment.apps "finance-nginxwebdep" deleted from default namespace

# create directories
sysuser@ubuntudev:~/git/ldk/k8s/28-kustomize/kustomize-demo (master -> origin/master)$ mkdir -p overlays/dev overlays/prod

# copy template file into dev
sysuser@ubuntudev:~/git/ldk/k8s/28-kustomize/kustomize-demo (master -> origin/master)$ cp base/kustomization.yaml overlays/dev/

# make appropriate changes and run kustomize on the overlays/dev directory
sysuser@ubuntudev:~/git/ldk/k8s/28-kustomize/kustomize-demo (master -> origin/master)$ kubectl kustomize overlays/dev/ | tee overlays/dev/kustomize-output.yaml

# output
apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginxwebdep
    env: dev
  name: dev-finance-nginxwebdep-v1
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginxwebdep
    env: dev
status:
  loadBalancer: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginxwebdep
    env: dev
  name: dev-finance-nginxwebdep-v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginxwebdep
      env: dev
  strategy: {}
  template:
    metadata:
      labels:
        app: nginxwebdep
        env: dev
    spec:
      containers:
      - image: nginx
        name: nginx
        ports:
        - containerPort: 80
        resources: {}
status: {}

# apply kustomize
sysuser@ubuntudev:~/git/ldk/k8s/28-kustomize/kustomize-demo (master -> origin/master)$ kubectl apply -k overlays/dev/

# output
service/dev-finance-nginxwebdep-v1 created
deployment.apps/dev-finance-nginxwebdep-v1 created

# copy files from dev to prod
sysuser@ubuntudev:~/git/ldk/k8s/28-kustomize/kustomize-demo (master -> origin/master)$ cp overlays/dev/* overlays/prod/

# copy deployment file from base to prod to serve as a patch
sysuser@ubuntudev:~/git/ldk/k8s/28-kustomize/kustomize-demo (master -> origin/master)$ cp base/nginxwebdep.yaml overlays/prod/

# get the kustomize output
sysuser@ubuntudev:~/git/ldk/k8s/28-kustomize/kustomize-demo (master -> origin/master)$ kubectl kustomize overlays/prod/ | tee kustomize-output.yaml
apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginxwebdep
    env: prod
  name: prod-finance-nginxwebdep-v1
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginxwebdep
    env: prod
status:
  loadBalancer: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginxwebdep
    env: prod
  name: prod-finance-nginxwebdep-v1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginxwebdep
      env: prod
  strategy: {}
  template:
    metadata:
      labels:
        app: nginxwebdep
        env: prod
    spec:
      containers:
      - image: nginx
        name: nginx
        ports:
        - containerPort: 80
        resources: {}
status: {}

# apply the kustomize
sysuser@ubuntudev:~/git/ldk/k8s/28-kustomize/kustomize-demo (master -> origin/master)$ kubectl apply -k overlays/prod/

# output
service/prod-finance-nginxwebdep-v1 created
deployment.apps/prod-finance-nginxwebdep-v1 created

# get all resources
sysuser@ubuntudev:~/git/ldk/k8s/28-kustomize/kustomize-demo (master -> origin/master)$ kubectl get all -A

# output
NAMESPACE            NAME                                               READY   STATUS    RESTARTS   AGE
default              pod/dev-finance-nginxwebdep-v1-b5d96dd6c-mnbl8     1/1     Running   0          7m8s
default              pod/prod-finance-nginxwebdep-v1-869d69ddb9-88zwm   1/1     Running   0          31s
default              pod/prod-finance-nginxwebdep-v1-869d69ddb9-dpmsz   1/1     Running   0          31s
default              pod/prod-finance-nginxwebdep-v1-869d69ddb9-rz5w8   1/1     Running   0          31s
kube-system          pod/coredns-7d764666f9-8kwgz                       1/1     Running   0          112m
kube-system          pod/coredns-7d764666f9-kmc9k                       1/1     Running   0          112m
kube-system          pod/etcd-klc-control-plane                         1/1     Running   0          112m
kube-system          pod/kindnet-7qjbt                                  1/1     Running   0          112m
kube-system          pod/kindnet-7t8nt                                  1/1     Running   0          112m
kube-system          pod/kindnet-crxc6                                  1/1     Running   0          112m
kube-system          pod/kube-apiserver-klc-control-plane               1/1     Running   0          112m
kube-system          pod/kube-controller-manager-klc-control-plane      1/1     Running   0          112m
kube-system          pod/kube-proxy-ckzpg                               1/1     Running   0          112m
kube-system          pod/kube-proxy-k85wl                               1/1     Running   0          112m
kube-system          pod/kube-proxy-p8mtv                               1/1     Running   0          112m
kube-system          pod/kube-scheduler-klc-control-plane               1/1     Running   0          112m
kube-system          pod/metrics-server-9c47cf9fd-bvtrz                 1/1     Running   0          112m
local-path-storage   pod/local-path-provisioner-67b8995b4b-db2gz        1/1     Running   0          112m

NAMESPACE     NAME                                  TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)                  AGE
default       service/dev-finance-nginxwebdep-v1    ClusterIP   10.96.98.25     <none>        80/TCP                   7m8s
default       service/kubernetes                    ClusterIP   10.96.0.1       <none>        443/TCP                  112m
default       service/prod-finance-nginxwebdep-v1   ClusterIP   10.96.204.199   <none>        80/TCP                   31s
kube-system   service/kube-dns                      ClusterIP   10.96.0.10      <none>        53/UDP,53/TCP,9153/TCP   112m
kube-system   service/metrics-server                ClusterIP   10.96.224.76    <none>        443/TCP                  112m

NAMESPACE     NAME                        DESIRED   CURRENT   READY   UP-TO-DATE   AVAILABLE   NODE SELECTOR            AGE
kube-system   daemonset.apps/kindnet      3         3         3       3            3           kubernetes.io/os=linux   112m
kube-system   daemonset.apps/kube-proxy   3         3         3       3            3           kubernetes.io/os=linux   112m

NAMESPACE            NAME                                          READY   UP-TO-DATE   AVAILABLE   AGE
default              deployment.apps/dev-finance-nginxwebdep-v1    1/1     1            1           7m8s
default              deployment.apps/prod-finance-nginxwebdep-v1   3/3     3            3           31s
kube-system          deployment.apps/coredns                       2/2     2            2           112m
kube-system          deployment.apps/metrics-server                1/1     1            1           112m
local-path-storage   deployment.apps/local-path-provisioner        1/1     1            1           112m

NAMESPACE            NAME                                                     DESIRED   CURRENT   READY   AGE
default              replicaset.apps/dev-finance-nginxwebdep-v1-b5d96dd6c     1         1         1       7m8s
default              replicaset.apps/prod-finance-nginxwebdep-v1-869d69ddb9   3         3         3       31s
kube-system          replicaset.apps/coredns-7d764666f9                       2         2         2       112m
kube-system          replicaset.apps/metrics-server-9c47cf9fd                 1         1         1       112m
local-path-storage   replicaset.apps/local-path-provisioner-67b8995b4b        1         1         1       112m

# cleanup using kustomize delete
sysuser@ubuntudev:~/git/ldk/k8s/28-kustomize/kustomize-demo (master -> origin/master)$ kubectl delete -k overlays/prod/ && kubectl delete -k overlays/dev/

# output
service "prod-finance-nginxwebdep-v1" deleted from default namespace
deployment.apps "prod-finance-nginxwebdep-v1" deleted from default namespace
service "dev-finance-nginxwebdep-v1" deleted from default namespace
deployment.apps "dev-finance-nginxwebdep-v1" deleted from default namespace
