# ci/cd pipeline can use labels to idenfity applications and also for deployment. network policies can use label selectors for rules. 
# create an nginx pod and tee it to a file
sysuser@ubuntuprod:~/git/ldk/k8s/10-labels (master -> origin/master)$ kubectl run nginxpod --image=nginx --port=80 -o yaml --dry-run=client | tee nginxpod.yaml 

# output
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginxpod
  name: nginxpod
spec:
  containers:
  - image: nginx
    name: nginxpod
    ports:
    - containerPort: 80
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}

# apply the file
sysuser@ubuntuprod:~/git/ldk/k8s/10-labels (master -> origin/master)$ kubectl apply -f nginxpod.yaml 

# output
pod/nginxpod created

# expose as a ClusterIP
sysuser@ubuntuprod:~/git/ldk/k8s/10-labels (master -> origin/master)$ kubectl expose pod/nginxpod --type=ClusterIP --port 8080 --target-port 80 --dry-run=client -o yaml | tee nginxpodcip.yaml && kubectl apply -f nginxpodcip.yaml && kubectl get all -o wide

# output
apiVersion: v1
kind: Service
metadata:
  labels:
    run: nginxpod
  name: nginxpod
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 80
  selector:
    run: nginxpod
  type: ClusterIP
status:
  loadBalancer: {}
service/nginxpod created
NAME           READY   STATUS    RESTARTS   AGE   IP             NODE         NOMINATED NODE   READINESS GATES
pod/nginxpod   1/1     Running   0          7s    10.244.1.146   klc-worker   <none>           <none>

NAME               TYPE        CLUSTER-IP     EXTERNAL-IP   PORT(S)    AGE   SELECTOR
service/nginxpod   ClusterIP   10.96.78.107   <none>        8080/TCP   0s    run=nginxpod

# curl the clusterip to ensure that the pod is serving
sysuser@ubuntuprod:~/git/ldk/k8s/10-labels (master -> origin/master)$ kubectl run -it --rm curlpod --image=curlimages/curl -n myns --restart=Never -- sh

# outpit
~ $ curl 10.96.78.107:8080
<!DOCTYPE html>
<html>
<head>
<title>Welcome to nginx!</title>
<style>
html { color-scheme: light dark; }
body { width: 35em; margin: 0 auto;
font-family: Tahoma, Verdana, Arial, sans-serif; }
</style>
</head>
<body>
<h1>Welcome to nginx!</h1>
<p>If you see this page, nginx is successfully installed and working.
Further configuration is required for the web server, reverse proxy, 
API gateway, load balancer, content cache, or other features.</p>

<p>For online documentation and support please refer to
<a href="https://nginx.org/">nginx.org</a>.<br/>
To engage with the community please visit
<a href="https://community.nginx.org/">community.nginx.org</a>.<br/>
For enterprise grade support, professional services, additional 
security features and capabilities please refer to
<a href="https://f5.com/nginx">f5.com/nginx</a>.</p>

<p><em>Thank you for using nginx.</em></p>
</body>
</html>

# create a yaml output of three ubuntu pods with a separator and tee it to a file
sysuser@ubuntuprod:~/git/ldk/k8s/10-labels (master -> origin/master)$ YAML=$(kubectl run ubuntupod --image=ubuntu --dry-run=client -o yaml --command sleep infinity) && echo -e "${YAML}\n---\n${YAML}\n---\n${YAML}" | tee colorpods.yaml

# output
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: ubuntupod
  name: ubuntupod
spec:
  containers:
  - command:
    - sleep
    - infinity
    image: ubuntu
    name: ubuntupod
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: ubuntupod
  name: ubuntupod
spec:
  containers:
  - command:
    - sleep
    - infinity
    image: ubuntu
    name: ubuntupod
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: ubuntupod
  name: ubuntupod
spec:
  containers:
  - command:
    - sleep
    - infinity
    image: ubuntu
    name: ubuntupod
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}

# manually edit the file and add labels and apply it
sysuser@ubuntuprod:~/git/ldk/k8s/10-labels (master -> origin/master)$ kubectl apply -f colorpods.yaml 

# output
pod/ubuntupod-red created
pod/ubuntupod-green created
pod/ubuntupod-pink created

# get pods
sysuser@ubuntuprod:~/git/ldk/k8s/10-labels (master -> origin/master)$ kubectl get pods -o wide

# output
NAME              READY   STATUS    RESTARTS   AGE     IP             NODE          NOMINATED NODE   READINESS GATES
nginxpod          1/1     Running   0          7h48m   10.244.1.146   klc-worker    <none>           <none>
ubuntupod-green   1/1     Running   0          41s     10.244.1.147   klc-worker    <none>           <none>
ubuntupod-pink    1/1     Running   0          41s     10.244.2.104   klc-worker2   <none>           <none>
ubuntupod-red     1/1     Running   0          41s     10.244.2.103   klc-worker2   <none>           <none>

# select using label
sysuser@ubuntuprod:~/git/ldk/k8s/10-labels (master -> origin/master)$ kubectl get all --selector color=green -o wide

# output
NAME                  READY   STATUS    RESTARTS   AGE     IP             NODE         NOMINATED NODE   READINESS GATES
pod/ubuntupod-green   1/1     Running   0          7m45s   10.244.1.147   klc-worker   <none>           <none>
sysuser@ubuntuprod:~/git/ldk/k8s/10-labels (master -> origin/master)$ kubectl get all -l color=green -o wide
NAME                  READY   STATUS    RESTARTS   AGE     IP             NODE         NOMINATED NODE   READINESS GATES
pod/ubuntupod-green   1/1     Running   0          7m55s   10.244.1.147   klc-worker   <none>           <none>
