# empty dir volume is created when a pod is assigned to a node. scratch space. empty dir can be set to memory - tmpfs. 

# create an empty dir ubuntu pod
sysuser@ubuntuprod:~/git/ldk/k8s/18-storage (master -> origin/master)$ kubectl run ubuntupod_emptydir --image=ubuntu --dry-run=client -o yaml --command sleep infinity | tee ubuntupod_emptydir_base.yaml

# output
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: ubuntupod_emptydir
  name: ubuntupod_emptydir
spec:
  containers:
  - command:
    - sleep
    - infinity
    image: ubuntu
    name: ubuntupod_emptydir
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}

