# empty dir volume is created when a pod is assigned to a node. scratch space. empty dir can be set to memory - tmpfs. 

# create an empty dir ubuntu pod
sysuser@ubuntuprod:~/git/ldk/k8s/18-storage (master -> origin/master)$ kubectl run ubuntupod-emptydir --image=ubuntu --dry-run=client -o yaml --command sleep infinity | tee ubuntupod-emptydir-base.yaml

# output
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: ubuntupod-emptydir
  name: ubuntupod-emptydir
spec:
  containers:
  - command:
    - sleep
    - infinity
    image: ubuntu
    name: ubuntupod-emptydir
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}

# create ubuntu pod
sysuser@ubuntuprod:~/git/ldk/k8s/18-storage (master -> origin/master)$ kubectl apply -f ubuntupod-emptydir-modified.yaml && echo "---PODS---" && sleep 3 && kubectl get pods -o wide

# output
pod/ubuntupod-emptydir created
---PODS---
NAME                 READY   STATUS    RESTARTS   AGE   IP           NODE         NOMINATED NODE   READINESS GATES
ubuntupod-emptydir   1/1     Running   0          3s    10.244.1.2   klc-worker   <none>           <none>
sysuser@ubuntuprod:~/git/ldk/k8s/18-storage (master -> origin/master)$ 

# exec into the pod
sysuser@ubuntuprod:~/git/ldk/k8s/18-storage (master -> origin/master)$ kubectl exec -it pod/ubuntupod-emptydir -- bash

# from inside the pod, run the following
root@ubuntupod-emptydir:/cache# df -h .

# output
Filesystem      Size  Used Avail Use% Mounted on
tmpfs           7.3G     0  7.3G   0% /cache

# run a performance test
root@ubuntupod-emptydir:/cache# dd if=/dev/zero of=output oflag=sync bs=1024k count=1000

# output
1000+0 records in
1000+0 records out
1048576000 bytes (1.0 GB, 1000 MiB) copied, 5.36438 s, 195 MB/s

# cleanup
sysuser@ubuntuprod:~/git/ldk/k8s/18-storage (master -> origin/master)$ kubectl delete pod/ubuntupod-emptydir

# get storage class
sysuser@ubuntuprod:~/git/ldk/k8s/18-storage (master -> origin/master)$ kubectl get storageclass

# output
NAME                 PROVISIONER             RECLAIMPOLICY   VOLUMEBINDINGMODE      ALLOWVOLUMEEXPANSION   AGE
standard (default)   rancher.io/local-path   Delete          WaitForFirstConsumer   false                  8d

# reclaimPolicy: Delete, Recycle (scrub), Retain
# volumes: manual, dynamic

# manual approach: create pv and then pvc for that specific pv
# create pv
sysuser@ubuntuprod:~/git/ldk/k8s/18-storage (master -> origin/master)$ kubectl apply -f manual-pv.yaml && echo "---PV---" && kubectl get pv -o wide

# output
persistentvolume/manual-pv-0001 created
---PV---
NAME             CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS      CLAIM   STORAGECLASS   VOLUMEATTRIBUTESCLASS   REASON   AGE   VOLUMEMODE
manual-pv-0001   1Gi        RWO            Retain           Available           standard       <unset>                          0s    Filesystem

# create pvc
sysuser@ubuntuprod:~/git/ldk/k8s/18-storage (master -> origin/master)$ kubectl apply -f manual-pv-claim.yaml && sleep 3 && echo "---PVC---"  && kubectl get pvc -o wide && echo "---PV---" && kubectl get pv -o wide

# output
persistentvolumeclaim/manual-claim created
---PVC---
NAME           STATUS   VOLUME           CAPACITY   ACCESS MODES   STORAGECLASS   VOLUMEATTRIBUTESCLASS   AGE   VOLUMEMODE
manual-claim   Bound    manual-pv-0001   1Gi        RWO            standard       <unset>                 4s    Filesystem
---PV---
NAME             CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS   CLAIM               STORAGECLASS   VOLUMEATTRIBUTESCLASS   REASON   AGE   VOLUMEMODE
manual-pv-0001   1Gi        RWO            Retain           Bound    myns/manual-claim   standard       <unset>                          34s   Filesystem

# dynamic approach: create pvc
sysuser@ubuntuprod:~/git/ldk/k8s/18-storage (master -> origin/master)$ cp manual-pv-claim.yaml dynamic-pv-claim.yaml

# apply dynamic pvc
sysuser@ubuntuprod:~/git/ldk/k8s/18-storage (master -> origin/master)$ kubectl apply -f dynamic-pv-claim.yaml && sleep 3 && echo "---PVC---" && kubectl get pvc -o wide && echo "---PV---" && kubectl get pv -o wide && kubectl describe pvc/dynamic-claim

# output
persistentvolumeclaim/dynamic-claim created
---PVC---
NAME            STATUS    VOLUME           CAPACITY   ACCESS MODES   STORAGECLASS   VOLUMEATTRIBUTESCLASS   AGE   VOLUMEMODE
dynamic-claim   Pending                                              standard       <unset>                 3s    Filesystem
manual-claim    Bound     manual-pv-0001   1Gi        RWO            standard       <unset>                 31s   Filesystem
---PV---
NAME             CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS   CLAIM               STORAGECLASS   VOLUMEATTRIBUTESCLASS   REASON   AGE   VOLUMEMODE
manual-pv-0001   1Gi        RWO            Retain           Bound    myns/manual-claim   standard       <unset>                          61s   Filesystem
Name:          dynamic-claim
Namespace:     myns
StorageClass:  standard
Status:        Pending
Volume:        
Labels:        <none>
Annotations:   <none>
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:      
Access Modes:  
VolumeMode:    Filesystem
Used By:       <none>
Events:
  Type    Reason                Age              From                         Message
  ----    ------                ----             ----                         -------
  Normal  WaitForFirstConsumer  2s (x2 over 3s)  persistentvolume-controller  waiting for first consumer to be created before binding

# describe the worker node to use its label as the node selector inside the pod we are about to create
sysuser@ubuntuprod:~/git/ldk/k8s/18-storage (master -> origin/master)$ kubectl describe node/klc-worker

# output
Name:               klc-worker
Roles:              <none>
Labels:             beta.kubernetes.io/arch=amd64
                    beta.kubernetes.io/os=linux
                    disktype=ssd
                    kubernetes.io/arch=amd64
                    kubernetes.io/hostname=klc-worker
                    kubernetes.io/os=linux
Annotations:        node.alpha.kubernetes.io/ttl: 0
                    volumes.kubernetes.io/controller-managed-attach-detach: true
CreationTimestamp:  Sat, 20 Jun 2026 08:26:45 -0500
Taints:             <none>
Unschedulable:      false
Lease:
  HolderIdentity:  klc-worker
  AcquireTime:     <unset>
  RenewTime:       Sun, 28 Jun 2026 10:37:55 -0500
Conditions:
  Type             Status  LastHeartbeatTime                 LastTransitionTime                Reason                       Message
  ----             ------  -----------------                 ------------------                ------                       -------
  MemoryPressure   False   Sun, 28 Jun 2026 10:37:37 -0500   Sat, 20 Jun 2026 08:26:45 -0500   KubeletHasSufficientMemory   kubelet has sufficient memory available
  DiskPressure     False   Sun, 28 Jun 2026 10:37:37 -0500   Sat, 20 Jun 2026 08:26:45 -0500   KubeletHasNoDiskPressure     kubelet has no disk pressure
  PIDPressure      False   Sun, 28 Jun 2026 10:37:37 -0500   Sat, 20 Jun 2026 08:26:45 -0500   KubeletHasSufficientPID      kubelet has sufficient PID available
  Ready            True    Sun, 28 Jun 2026 10:37:37 -0500   Sat, 20 Jun 2026 08:26:58 -0500   KubeletReady                 kubelet is posting ready status
Addresses:
  InternalIP:  172.18.0.2
  Hostname:    klc-worker
Capacity:
  cpu:                2
  ephemeral-storage:  61608748Ki
  hugepages-1Gi:      0
  hugepages-2Mi:      0
  memory:             7553660Ki
  pods:               110
Allocatable:
  cpu:                2
  ephemeral-storage:  61608748Ki
  hugepages-1Gi:      0
  hugepages-2Mi:      0
  memory:             7553660Ki
  pods:               110
System Info:
  Machine ID:                 7f5c84c6558d43b7918502bc74a5e4f4
  System UUID:                c801c12e-944a-4d47-bcd0-139ac88cf1de
  Boot ID:                    03a8b941-ff55-4651-99bd-3d66d2f26347
  Kernel Version:             7.0.0-27-generic
  OS Image:                   Debian GNU/Linux 12 (bookworm)
  Operating System:           linux
  Architecture:               amd64
  Container Runtime Version:  containerd://2.2.0
  Kubelet Version:            v1.35.0
PodCIDR:                      10.244.1.0/24
PodCIDRs:                     10.244.1.0/24
ProviderID:                   kind://docker/klc/klc-worker
Non-terminated Pods:          (2 in total)
  Namespace                   Name                CPU Requests  CPU Limits  Memory Requests  Memory Limits  Age
  ---------                   ----                ------------  ----------  ---------------  -------------  ---
  kube-system                 kindnet-wh4jv       100m (5%)     100m (5%)   50Mi (0%)        50Mi (0%)      8d
  kube-system                 kube-proxy-6gwcq    0 (0%)        0 (0%)      0 (0%)           0 (0%)         8d
Allocated resources:
  (Total limits may be over 100 percent, i.e., overcommitted.)
  Resource           Requests   Limits
  --------           --------   ------
  cpu                100m (5%)  100m (5%)
  memory             50Mi (0%)  50Mi (0%)
  ephemeral-storage  0 (0%)     0 (0%)
  hugepages-1Gi      0 (0%)     0 (0%)
  hugepages-2Mi      0 (0%)     0 (0%)
Events:              <none>

# create pod
sysuser@ubuntuprod:~/git/ldk/k8s/18-storage (master -> origin/master)$ kubectl apply -f ubuntupod-with-volumes.yaml && sleep 5 && echo "---PVC---"  && kubectl get pvc -o wide && echo "---PV---" && kubectl get pv -o wide && echo "---PODS---" && kubectl get pods -o wide

# output
pod/ubuntupod-with-volumes created
---PVC---
NAME            STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   VOLUMEATTRIBUTESCLASS   AGE     VOLUMEMODE
dynamic-claim   Bound    pvc-24293884-eae0-4a00-9a57-57d6ff0bb653   1Gi        RWO            standard       <unset>                 3m58s   Filesystem
manual-claim    Bound    manual-pv-0001                             1Gi        RWO            standard       <unset>                 4m26s   Filesystem
---PV---
NAME                                       CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS   CLAIM                STORAGECLASS   VOLUMEATTRIBUTESCLASS   REASON   AGE     VOLUMEMODE
manual-pv-0001                             1Gi        RWO            Retain           Bound    myns/manual-claim    standard       <unset>                          4m56s   Filesystem
pvc-24293884-eae0-4a00-9a57-57d6ff0bb653   1Gi        RWO            Delete           Bound    myns/dynamic-claim   standard       <unset>                          2m4s    Filesystem
---PODS---
NAME                     READY   STATUS    RESTARTS   AGE   IP           NODE         NOMINATED NODE   READINESS GATES
ubuntupod-with-volumes   1/1     Running   0          6s    10.244.1.5   klc-worker   <none>           <none>

# exec into the pod
sysuser@ubuntuprod:~/git/ldk/k8s/18-storage (master -> origin/master)$ kubectl exec -it ubuntupod-with-volumes -- bash

# get directories
root@ubuntupod-with-volumes:/# ll

# output
total 76
drwxr-xr-x   1 root root 4096 Jun 28 16:15 ./
drwxr-xr-x   1 root root 4096 Jun 28 16:15 ../
drwxr-xr-x   2 root root 4096 Jun 10 03:30 .rock/
lrwxrwxrwx   1 root root    7 Apr 20 08:46 bin@ -> usr/bin
drwxr-xr-x   2 root root 4096 Apr 20 08:46 boot/
drwxr-xr-x   5 root root  360 Jun 28 16:15 dev/
drwxrwxrwx   2 root root 4096 Jun 28 16:13 dynamic/
drwxr-xr-x  31 root root 4096 Jun 10 03:30 etc/
drwxr-xr-x   3 root root 4096 Jun 10 03:30 home/
lrwxrwxrwx   1 root root    7 Apr 20 08:46 lib@ -> usr/lib
lrwxrwxrwx   1 root root    9 Apr 20 08:46 lib64@ -> usr/lib64
drwxr-xr-x   2 root root 4096 Jun 28 16:13 manual/
drwxr-xr-x   2 root root 4096 Jun 10 03:29 media/
drwxr-xr-x   2 root root 4096 Jun 10 03:29 mnt/
drwxr-xr-x   2 root root 4096 Jun 10 03:29 opt/
dr-xr-xr-x 469 root root    0 Jun 28 16:15 proc/
-rw-r--r--   1 root root    5 Jun 28 16:15 product_name
-rw-r--r--   1 root root   37 Jun 28 16:15 product_uuid
drwx------   1 root root 4096 Jun 28 16:17 root/
drwxr-xr-x   1 root root 4096 Jun 28 16:15 run/
lrwxrwxrwx   1 root root    8 Apr 20 08:46 sbin@ -> usr/sbin
drwxr-xr-x   2 root root 4096 Jun 10 03:29 srv/
dr-xr-xr-x  13 root root    0 Jun 28 16:16 sys/
drwxrwxrwt   2 root root 4096 Jun 10 03:30 tmp/
drwxr-xr-x  12 root root 4096 Jun 10 03:29 usr/
drwxr-xr-x  11 root root 4096 Jun 10 03:30 var/

# run df
root@ubuntupod-with-volumes:/# cd /dynamic/ && df -h . && cd ../manual/ && df -h . && cd ..

# output
Filesystem      Size  Used Avail Use% Mounted on
/dev/sda2        59G   25G   32G  45% /dynamic
Filesystem      Size  Used Avail Use% Mounted on
/dev/sda2        59G   25G   32G  45% /manual
root@ubuntupod-with-volumes:/# 

# create text files in mounted directories
root@ubuntupod-with-volumes:/# echo hello > /manual/manual.txt && echo hello > /dynamic/dynamic.txt

# delete the pod and recreate it and then ensure that the files exist. 
sysuser@ubuntuprod:~/git/ldk/k8s/18-storage (master -> origin/master)$ kubectl delete pod ubuntupod-with-volumes --now && kubectl apply -f ubuntupod-with-volumes.yaml && sleep 7 && echo "---PVC---"  && kubectl get pvc -o wide && echo "---PV---" && kubectl get pv -o wide && echo "---PODS---" && kubectl get pods -o wide && kubectl exec -it ubuntupod-with-volumes -- bash

# output
pod "ubuntupod-with-volumes" deleted from myns namespace
pod/ubuntupod-with-volumes created
---PVC---
NAME            STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   VOLUMEATTRIBUTESCLASS   AGE   VOLUMEMODE
dynamic-claim   Bound    pvc-24293884-eae0-4a00-9a57-57d6ff0bb653   1Gi        RWO            standard       <unset>                 11m   Filesystem
manual-claim    Bound    manual-pv-0001                             1Gi        RWO            standard       <unset>                 12m   Filesystem
---PV---
NAME                                       CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS   CLAIM                STORAGECLASS   VOLUMEATTRIBUTESCLASS   REASON   AGE     VOLUMEMODE
manual-pv-0001                             1Gi        RWO            Retain           Bound    myns/manual-claim    standard       <unset>                          12m     Filesystem
pvc-24293884-eae0-4a00-9a57-57d6ff0bb653   1Gi        RWO            Delete           Bound    myns/dynamic-claim   standard       <unset>                          9m44s   Filesystem
---PODS---
NAME                     READY   STATUS    RESTARTS   AGE   IP           NODE         NOMINATED NODE   READINESS GATES
ubuntupod-with-volumes   1/1     Running   0          7s    10.244.1.7   klc-worker   <none>           <none>
root@ubuntupod-with-volumes:/# 

# cat the contents of the text files
root@ubuntupod-with-volumes:/# cat /manual/manual.txt && cat /dynamic/dynamic.txt 
hello
hello

# test the reclaim policy by deleting the pod and the manual and dynamic pvc. dynamic pv is automatically deleted, but manual pv still remains
sysuser@ubuntuprod:~/git/ldk/k8s/18-storage (master -> origin/master)$ kubectl delete pod ubuntupod-with-volumes --now && echo "---PVC---" && kubectl get pvc -o wide && echo "---PV---" && kubectl get pv -o wide && kubectl delete pvc dynamic-claim manual-claim && sleep 3 && echo "---PVC---" && kubectl get pvc -o wide && echo "---PV---" && kubectl get pv -o wide

# output
pod "ubuntupod-with-volumes" deleted from myns namespace
---PVC---
NAME            STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   VOLUMEATTRIBUTESCLASS   AGE   VOLUMEMODE
dynamic-claim   Bound    pvc-24293884-eae0-4a00-9a57-57d6ff0bb653   1Gi        RWO            standard       <unset>                 19m   Filesystem
manual-claim    Bound    manual-pv-0001                             1Gi        RWO            standard       <unset>                 19m   Filesystem
---PV---
NAME                                       CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS   CLAIM                STORAGECLASS   VOLUMEATTRIBUTESCLASS   REASON   AGE   VOLUMEMODE
manual-pv-0001                             1Gi        RWO            Retain           Bound    myns/manual-claim    standard       <unset>                          20m   Filesystem
pvc-24293884-eae0-4a00-9a57-57d6ff0bb653   1Gi        RWO            Delete           Bound    myns/dynamic-claim   standard       <unset>                          17m   Filesystem
persistentvolumeclaim "dynamic-claim" deleted from myns namespace
persistentvolumeclaim "manual-claim" deleted from myns namespace
---PVC---
No resources found in myns namespace.
---PV---
NAME             CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS     CLAIM               STORAGECLASS   VOLUMEATTRIBUTESCLASS   REASON   AGE   VOLUMEMODE
manual-pv-0001   1Gi        RWO            Retain           Released   myns/manual-claim   standard       <unset>                          20m   Filesystem
