apiVersion: v1
kind: Pod
metadata:
  labels:
    run: ubuntupod-emptydir
  name: ubuntupod-emptydir
spec:
  containers:
  - command:
    - sleep
    - infinity
    image: ubuntu
    name: ubuntupod-emptydir
    resources: {}
    volumeMounts:
    - mountPath: /cache
      name: cache-volume
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  volumes:
  - name: cache-volume
    emptyDir: {
      medium: Memory,
    }
status: {}