apiVersion: v1
kind: Pod
metadata:
  labels:
    run: ubuntupod-emptydir
  name: ubuntupod-emptydir
spec:
  containers:
  - command:
    - sleep
    - infinity
    image: ubuntu
    name: ubuntupod-emptydir
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
