Name:                   nginxdep
Namespace:              myns
CreationTimestamp:      Sat, 20 Jun 2026 13:26:55 -0500
Labels:                 app=nginxdep
Annotations:            deployment.kubernetes.io/revision: 6
Selector:               app=nginxdep
Replicas:               3 desired | 3 updated | 3 total | 3 available | 0 unavailable
StrategyType:           RollingUpdate
MinReadySeconds:        0
RollingUpdateStrategy:  25% max unavailable, 25% max surge
Pod Template:
  Labels:  app=nginxdep
  Containers:
   ubuntucontainer:
    Image:      ubuntu:24.04
    Port:       <none>
    Host Port:  <none>
    Args:
      sleep
      infinity
    Environment:  <none>
    Mounts:       <none>
   nginxcontainer:
    Image:         nginx
    Port:          <none>
    Host Port:     <none>
    Environment:   <none>
    Mounts:        <none>
  Volumes:         <none>
  Node-Selectors:  <none>
  Tolerations:     <none>
Conditions:
  Type           Status  Reason
  ----           ------  ------
  Available      True    MinimumReplicasAvailable
  Progressing    True    NewReplicaSetAvailable
OldReplicaSets:  nginxdep-5f4d9669f8 (0/0 replicas created), nginxdep-67bc8846d9 (0/0 replicas created), nginxdep-77d549b97b (0/0 replicas created), nginxdep-6cdf86cb68 (0/0 replicas created)
NewReplicaSet:   nginxdep-67cfd488b6 (3/3 replicas created)
Events:
  Type    Reason             Age                From                   Message
  ----    ------             ----               ----                   -------
  Normal  ScalingReplicaSet  57m                deployment-controller  Scaled up replica set nginxdep-5f4d9669f8 from 0 to 3
  Normal  ScalingReplicaSet  54m                deployment-controller  Scaled down replica set nginxdep-5f4d9669f8 from 3 to 2
  Normal  ScalingReplicaSet  54m                deployment-controller  Scaled down replica set nginxdep-5f4d9669f8 from 2 to 1
  Normal  ScalingReplicaSet  54m                deployment-controller  Scaled down replica set nginxdep-5f4d9669f8 from 1 to 0
  Normal  ScalingReplicaSet  43m                deployment-controller  Scaled up replica set nginxdep-77d549b97b from 0 to 1
  Normal  ScalingReplicaSet  43m                deployment-controller  Scaled up replica set nginxdep-77d549b97b from 1 to 2
  Normal  ScalingReplicaSet  43m                deployment-controller  Scaled up replica set nginxdep-77d549b97b from 2 to 3
  Normal  ScalingReplicaSet  43m                deployment-controller  Scaled down replica set nginxdep-67bc8846d9 from 2 to 1
  Normal  ScalingReplicaSet  43m                deployment-controller  Scaled down replica set nginxdep-67bc8846d9 from 1 to 0
  Normal  ScalingReplicaSet  24m (x2 over 54m)  deployment-controller  Scaled up replica set nginxdep-67bc8846d9 from 0 to 1
  Normal  ScalingReplicaSet  24m (x2 over 54m)  deployment-controller  Scaled up replica set nginxdep-67bc8846d9 from 1 to 2
  Normal  ScalingReplicaSet  24m                deployment-controller  Scaled down replica set nginxdep-77d549b97b from 3 to 2
  Normal  ScalingReplicaSet  24m (x2 over 54m)  deployment-controller  Scaled up replica set nginxdep-67bc8846d9 from 2 to 3
  Normal  ScalingReplicaSet  24m                deployment-controller  Scaled down replica set nginxdep-77d549b97b from 2 to 1
  Normal  ScalingReplicaSet  24m                deployment-controller  Scaled down replica set nginxdep-77d549b97b from 1 to 0
  Normal  ScalingReplicaSet  20m                deployment-controller  Scaled up replica set nginxdep-6cdf86cb68 from 0 to 1
  Normal  ScalingReplicaSet  20m                deployment-controller  Scaled up replica set nginxdep-6cdf86cb68 from 1 to 2
  Normal  ScalingReplicaSet  20m (x2 over 43m)  deployment-controller  Scaled down replica set nginxdep-67bc8846d9 from 3 to 2
  Normal  ScalingReplicaSet  20m (x3 over 20m)  deployment-controller  (combined from similar events): Scaled down replica set nginxdep-67bc8846d9 from 1 to 0
  Normal  ScalingReplicaSet  2m                 deployment-controller  Scaled up replica set nginxdep-67cfd488b6 from 0 to 1
  Normal  ScalingReplicaSet  114s               deployment-controller  Scaled down replica set nginxdep-6cdf86cb68 from 3 to 2
  Normal  ScalingReplicaSet  113s               deployment-controller  Scaled up replica set nginxdep-67cfd488b6 from 1 to 2
  Normal  ScalingReplicaSet  107s               deployment-controller  Scaled down replica set nginxdep-6cdf86cb68 from 2 to 1
  Normal  ScalingReplicaSet  107s               deployment-controller  Scaled up replica set nginxdep-67cfd488b6 from 2 to 3
  Normal  ScalingReplicaSet  104s               deployment-controller  Scaled down replica set nginxdep-6cdf86cb68 from 1 to 0
