# feature to check pods before they are admitted. make sure they meet the security standards. 
# API request is set to admission control, and it can be rejected if they are not up to the standards. 
# they are built on pod security standards. privileged, baseline, restricted. 
# works at namespace level and admission controller enforces this rule. modes: enforce, warn, audit
# pod-security.kubernetes.io/enforce=[restricted,privileged,baseline]
# pod-security.kubernetes.io/enforce-version=latest

# create a namespace and show its labels
sysuser@ubuntuprod:~/git/ldk/k8s/25-pod-security-admission (master -> origin/master)$ kubectl create namespace psa-unrestricted && echo "---NS---" && kubectl get ns psa-unrestricted --show-labels

# output
namespace/psa-unrestricted created
---NS---
NAME               STATUS   AGE   LABELS
psa-unrestricted   Active   0s    kubernetes.io/metadata.name=psa-unrestricted

# set the current context to psa-unrestricted. switch it back once done with the tutorial. 
sysuser@ubuntuprod:~/git/ldk/k8s/25-pod-security-admission (master -> origin/master)$ kubectl config set-context --current --namespace=psa-unrestricted && kubectl get all

# output
Context "kind-klc" modified.
No resources found in psa-unrestricted namespace.

# create a pod in psa-unrestricted namespace
sysuser@ubuntuprod:~/git/ldk/k8s/25-pod-security-admission (master -> origin/master)$ kubectl -n psa-unrestricted run nginxpod-insecure --image=nginx --dry-run=client -o yaml | tee nginxpod-insecure.yaml

# output
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginxpod-insecure
  name: nginxpod-insecure
  namespace: psa-unrestricted
spec:
  containers:
  - image: nginx
    name: nginxpod-insecure
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}

# manually edit the pod spec to add things that are not desirable and apply the file
sysuser@ubuntuprod:~/git/ldk/k8s/25-pod-security-admission (master -> origin/master)$ kubectl apply -f nginxpod-insecure.yaml && sleep 2 && echo "---PODS---" && kubectl get pods -o wide --show-labels

# output
pod/nginxpod-insecure created
---PODS---
NAME                READY   STATUS    RESTARTS   AGE   IP           NODE         NOMINATED NODE   READINESS GATES   LABELS
nginxpod-insecure   1/1     Running   0          2s    172.18.0.4   klc-worker   <none>           <none>            run=nginxpod-insecure

# create new namespace
sysuser@ubuntuprod:~/git/ldk/k8s/25-pod-security-admission (master -> origin/master)$ kubectl create namespace psa-baseline

# output
namespace/psa-baseline created

# label the namespace
sysuser@ubuntuprod:~/git/ldk/k8s/25-pod-security-admission (master -> origin/master)$ kubectl label namespace psa-baseline \
pod-security.kubernetes.io/enforce=baseline \
pod-security.kubernetes.io/enforce-version=latest \
pod-security.kubernetes.io/warn=baseline \
pod-security.kubernetes.io/warn-version=latest

# output
namespace/psa-baseline labeled

# get namespace
sysuser@ubuntuprod:~/git/ldk/k8s/25-pod-security-admission (master -> origin/master)$ kubectl get ns -o wide --show-labels

# output
NAME                 STATUS   AGE     LABELS
default              Active   2d18h   kubernetes.io/metadata.name=default
kube-node-lease      Active   2d18h   kubernetes.io/metadata.name=kube-node-lease
kube-public          Active   2d18h   kubernetes.io/metadata.name=kube-public
kube-system          Active   2d18h   kubernetes.io/metadata.name=kube-system
local-path-storage   Active   2d18h   kubernetes.io/metadata.name=local-path-storage
myns                 Active   2d16h   kubernetes.io/metadata.name=myns
psa-baseline         Active   4m2s    kubernetes.io/metadata.name=psa-baseline,pod-security.kubernetes.io/enforce-version=latest,pod-security.kubernetes.io/enforce=baseline,pod-security.kubernetes.io/warn-version=latest,pod-security.kubernetes.io/warn=baseline
psa-unrestricted     Active   17m     kubernetes.io/metadata.name=psa-unrestricted

# create this file from the previous pod spec, nginxpod-baseline.yaml. make necessary changes and apply it. 
sysuser@ubuntuprod:~/git/ldk/k8s/25-pod-security-admission (master -> origin/master)$ kubectl apply -f nginxpod-baseline.yaml 

# output
Error from server (Forbidden): error when creating "nginxpod-baseline.yaml": pods "nginxpod-baseline" is forbidden: violates PodSecurity "baseline:latest": host namespaces (hostNetwork=true, hostPID=true), privileged (container "nginxpod-baseline" must not set securityContext.privileged=true)

# create namespace psa-restricted
sysuser@ubuntuprod:~/git/ldk/k8s/25-pod-security-admission (master -> origin/master)$ kubectl create namespace psa-restricted

# output
namespace/psa-restricted created

# add labels
sysuser@ubuntuprod:~/git/ldk/k8s/25-pod-security-admission (master -> origin/master)$ kubectl label namespace psa-restricted \

# output
pod-security.kubernetes.io/enforce=restricted \
pod-security.kubernetes.io/enforce-version=latest \
pod-security.kubernetes.io/warn=restricted \
pod-security.kubernetes.io/warn-version=latest
namespace/psa-restricted labeled

# create pod spec. this will be rejected because restricted standards would reject this. make changes to this and apply it
sysuser@ubuntuprod:~/git/ldk/k8s/25-pod-security-admission (master -> origin/master)$ kubectl run -n psa-restricted nginxpod-restricted --image=nginx --dry-run=client -o yaml | tee nginxpod-restricted.yaml
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginxpod-restricted
  name: nginxpod-restricted
  namespace: psa-restricted
spec:
  containers:
  - image: nginx
    name: nginxpod-restricted
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}


# pod got created, but the container cannot initialize
sysuser@ubuntuprod:~/git/ldk/k8s/25-pod-security-admission (master -> origin/master)$ kubectl apply -f nginxpod-restricted.yaml && sleep 2 && echo "---PODS---" && kubectl -n psa-restricted get pods -o wide --show-labels

# output
pod/nginxpod-restricted created
---PODS---
NAME                  READY   STATUS                       RESTARTS   AGE   IP           NODE         NOMINATED NODE   READINESS GATES   LABELS
nginxpod-restricted   0/1     CreateContainerConfigError   0          2s    10.244.1.8   klc-worker   <none>           <none>            run=nginxpod-restricted

# describe the pod. blocked by kubelet because image is running as root. 
sysuser@ubuntuprod:~/git/ldk/k8s/25-pod-security-admission (master -> origin/master)$ kubectl -n psa-restricted describe pod nginxpod-restricted | tee nginxpod-restricted-describe.txt
Name:             nginxpod-restricted
Namespace:        psa-restricted
Priority:         0
Service Account:  default
Node:             klc-worker/172.18.0.4
Start Time:       Thu, 09 Jul 2026 07:32:10 -0500
Labels:           run=nginxpod-restricted
Annotations:      <none>
Status:           Pending
IP:               10.244.1.8
IPs:
  IP:  10.244.1.8
Containers:
  nginxpod-restricted:
    Container ID:    
    Image:           nginx
    Image ID:        
    Port:            <none>
    Host Port:       <none>
    SeccompProfile:  RuntimeDefault
    State:           Waiting
      Reason:        CreateContainerConfigError
    Ready:           False
    Restart Count:   0
    Environment:     <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-xv727 (ro)
Conditions:
  Type                        Status
  PodReadyToStartContainers   True 
  Initialized                 True 
  Ready                       False 
  ContainersReady             False 
  PodScheduled                True 
Volumes:
  kube-api-access-xv727:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    Optional:                false
    DownwardAPI:             true
QoS Class:                   BestEffort
Node-Selectors:              <none>
Tolerations:                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason     Age                  From               Message
  ----     ------     ----                 ----               -------
  Normal   Scheduled  2m13s                default-scheduler  Successfully assigned psa-restricted/nginxpod-restricted to klc-worker
  Normal   Pulled     2m12s                kubelet            spec.containers{nginxpod-restricted}: Successfully pulled image "nginx" in 833ms (833ms including waiting). Image size: 63132621 bytes.
  Normal   Pulled     2m11s                kubelet            spec.containers{nginxpod-restricted}: Successfully pulled image "nginx" in 865ms (865ms including waiting). Image size: 63132621 bytes.
  Normal   Pulled     114s                 kubelet            spec.containers{nginxpod-restricted}: Successfully pulled image "nginx" in 1.051s (1.051s including waiting). Image size: 63132621 bytes.
  Normal   Pulled     100s                 kubelet            spec.containers{nginxpod-restricted}: Successfully pulled image "nginx" in 753ms (753ms including waiting). Image size: 63132621 bytes.
  Normal   Pulled     86s                  kubelet            spec.containers{nginxpod-restricted}: Successfully pulled image "nginx" in 861ms (861ms including waiting). Image size: 63132621 bytes.
  Normal   Pulled     72s                  kubelet            spec.containers{nginxpod-restricted}: Successfully pulled image "nginx" in 892ms (892ms including waiting). Image size: 63132621 bytes.
  Normal   Pulled     60s                  kubelet            spec.containers{nginxpod-restricted}: Successfully pulled image "nginx" in 877ms (877ms including waiting). Image size: 63132621 bytes.
  Normal   Pulled     43s                  kubelet            spec.containers{nginxpod-restricted}: Successfully pulled image "nginx" in 1.562s (1.562s including waiting). Image size: 63132621 bytes.
  Normal   Pulled     30s                  kubelet            spec.containers{nginxpod-restricted}: Successfully pulled image "nginx" in 942ms (942ms including waiting). Image size: 63132621 bytes.
  Normal   Pulling    6s (x11 over 2m13s)  kubelet            spec.containers{nginxpod-restricted}: Pulling image "nginx"
  Warning  Failed     5s (x11 over 2m12s)  kubelet            spec.containers{nginxpod-restricted}: Error: container has runAsNonRoot and image will run as root (pod: "nginxpod-restricted_psa-restricted(e87aa9c4-28cd-47e8-9913-a24fd8aaf630)", container: nginxpod-restricted)
  Normal   Pulled     5s (x2 over 17s)     kubelet            spec.containers{nginxpod-restricted}: (combined from similar events): Successfully pulled image "nginx" in 871ms (871ms including waiting). Image size: 63132621 bytes.

# update the image in the following file: nginxpod-restricted2.yaml and apply it. 
sysuser@ubuntuprod:~/git/ldk/k8s/25-pod-security-admission (master -> origin/master)$ kubectl apply -f nginxpod-restricted2.yaml

# output
pod/nginxpod-restricted configured

# get pods
sysuser@ubuntuprod:~/git/ldk/k8s/25-pod-security-admission (master -> origin/master)$ kubectl -n psa-restricted get pods -o wide --show-labels

# output
NAME                  READY   STATUS    RESTARTS   AGE     IP           NODE         NOMINATED NODE   READINESS GATES   LABELS
nginxpod-restricted   1/1     Running   0          7m32s   10.244.1.8   klc-worker   <none>           <none>            run=nginxpod-restricted

# create namespace
sysuser@ubuntuprod:~/git/ldk/k8s/25-pod-security-admission (master -> origin/master)$ kubectl create namespace psa-warn-audit

# output
namespace/psa-warn-audit created

# label the namespace
sysuser@ubuntuprod:~/git/ldk/k8s/25-pod-security-admission (master -> origin/master)$ kubectl label namespace psa-warn-audit \
pod-security.kubernetes.io/enforce=baseline \
pod-security.kubernetes.io/enforce-version=latest \
pod-security.kubernetes.io/warn=restricted \
pod-security.kubernetes.io/warn-version=latest \
pod-security.kubernetes.io/audit=restricted \
pod-security.kubernetes.io/audit-version=latest

# output
namespace/psa-warn-audit labeled

# create a pod
sysuser@ubuntuprod:~/git/ldk/k8s/25-pod-security-admission (master -> origin/master)$ kubectl -n psa-warn-audit run nginxpod-warnaudit --image=nginx:stable -o yaml --dry-run=client | tee nginxpod-warnaudit.yaml
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginxpod-warnaudit
  name: nginxpod-warnaudit
  namespace: psa-warn-audit
spec:
  containers:
  - image: nginx:stable
    name: nginxpod-warnaudit
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}

# apply it
sysuser@ubuntuprod:~/git/ldk/k8s/25-pod-security-admission (master -> origin/master)$ kubectl apply -f nginxpod-warnaudit.yaml 

# output
Warning: would violate PodSecurity "restricted:latest": allowPrivilegeEscalation != false (container "nginxpod-warnaudit" must set securityContext.allowPrivilegeEscalation=false), unrestricted capabilities (container "nginxpod-warnaudit" must set securityContext.capabilities.drop=["ALL"]), runAsNonRoot != true (pod or container "nginxpod-warnaudit" must set securityContext.runAsNonRoot=true), seccompProfile (pod or container "nginxpod-warnaudit" must set securityContext.seccompProfile.type to "RuntimeDefault" or "Localhost")
pod/nginxpod-warnaudit created

# clean up the resources and set the context back to myns