apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginxpod-restricted
  name: nginxpod-restricted
  namespace: psa-restricted
spec:
  securityContext:
    runAsNonRoot: true
  containers:
  - image: nginxinc/nginx-unprivileged:stable # update the image
    name: nginxpod-restricted
    securityContext: 
      allowPrivilegeEscalation: false
      capabilities:
        drop: ["ALL"]
      seccompProfile:
        type: RuntimeDefault
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
