# create a configmap and store two key value pairs
sysuser@ubuntuprod:~/git/ldk/k8s/08-configmaps (master -> origin/master)$ kubectl create configmap colorcm --dry-run=client -o yaml --from-literal=color=red --from-literal=key=value | tee colorcm.yaml

# output
apiVersion: v1
data:
  color: red
  key: value
kind: ConfigMap
metadata:
  name: colorcm

# apply the file, get and describe the configmap
sysuser@ubuntuprod:~/git/ldk/k8s/08-configmaps (master -> origin/master)$ kubectl apply -f colorcm.yaml && kubectl get configmap -o wide && kubectl describe configmap/colorcm

# output
configmap/colorcm created
NAME               DATA   AGE
colorcm            2      0s
kube-root-ca.crt   1      44h
Name:         colorcm
Namespace:    myns
Labels:       <none>
Annotations:  <none>

Data
====
color:
----
red

key:
----
value


BinaryData
====

Events:  <none>

# delete this for now
sysuser@ubuntuprod:~/git/ldk/k8s/08-configmaps (master -> origin/master)$ kubectl delete configmap/colorcm

# output
configmap "colorcm" deleted from myns namespace

# create using properties file
sysuser@ubuntuprod:~/git/ldk/k8s/08-configmaps (master -> origin/master)$ cat <<EOF > colorcm.properties
> color=green
> key=value
> EOF

# cat the properties file
sysuser@ubuntuprod:~/git/ldk/k8s/08-configmaps (master -> origin/master)$ cat colorcm.properties 

# output
color=green
key=value

# create the configmap, get and describe
sysuser@ubuntuprod:~/git/ldk/k8s/08-configmaps (master -> origin/master)$ kubectl create configmap colorcm-properties --from-env-file=colorcm.properties && kubectl get configmap -o wide && kubectl describe configmap/colorcm-properties

# output
configmap/colorcm-properties created
NAME                 DATA   AGE
colorcm-properties   2      0s
kube-root-ca.crt     1      44h
Name:         colorcm-properties
Namespace:    myns
Labels:       <none>
Annotations:  <none>

Data
====
color:
----
green

key:
----
value


BinaryData
====

Events:  <none>

# create a pod that dumps all environment variables and sleeps
sysuser@ubuntuprod:~/git/ldk/k8s/08-configmaps (master -> origin/master)$ kubectl run ubuntupod --image=ubuntu --dry-run=client -o yaml --command bash -- -c 'env; sleep infinity' | tee ubuntupod.yaml

# output
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: ubuntupod
  name: ubuntupod
spec:
  containers:
  - command:
    - bash
    - -c
    - env; sleep infinity
    image: ubuntu
    name: ubuntupod
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}

# apply and get logs
sysuser@ubuntuprod:~/git/ldk/k8s/08-configmaps (master -> origin/master)$ kubectl apply -f ubuntupod.yaml && sleep 10 && echo "--PODS--" && kubectl get pods -o wide && echo "--LOGS--" && kubectl logs pod/ubuntupod

# output
pod/ubuntupod created
--PODS--
NAME        READY   STATUS    RESTARTS   AGE   IP             NODE          NOMINATED NODE   READINESS GATES
ubuntupod   1/1     Running   0          97s   10.244.2.100   klc-worker2   <none>           <none>
--LOGS--
KUBERNETES_SERVICE_PORT_HTTPS=443
KUBERNETES_SERVICE_PORT=443
HOSTNAME=ubuntupod
PWD=/
HOME=/root
KUBERNETES_PORT_443_TCP=tcp://10.96.0.1:443
SHLVL=1
KUBERNETES_PORT_443_TCP_PROTO=tcp
KUBERNETES_PORT_443_TCP_ADDR=10.96.0.1
KUBERNETES_SERVICE_HOST=10.96.0.1
KUBERNETES_PORT=tcp://10.96.0.1:443
KUBERNETES_PORT_443_TCP_PORT=443
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
_=/usr/bin/env

# we will add the configmap to the pod by manually adding it to /home/sysuser/git/ldk/k8s/08-configmaps/ubuntupod-colorcm-properties.yaml and delete the ubuntupod and then recreate it
sysuser@ubuntuprod:~/git/ldk/k8s/08-configmaps (master -> origin/master)$ kubectl delete -f ubuntupod.yaml --now && sleep 2 && kubectl apply -f ubuntupod-colorcm-properties.yaml && sleep 10 && echo "--PODS--" && kubectl get pods -o wide && echo "--LOGS--" && kubectl logs pod/ubuntupod

# output
pod "ubuntupod" deleted from myns namespace
pod/ubuntupod created
--PODS--
NAME        READY   STATUS    RESTARTS   AGE   IP             NODE         NOMINATED NODE   READINESS GATES
ubuntupod   1/1     Running   0          10s   10.244.1.141   klc-worker   <none>           <none>
--LOGS--
KUBERNETES_SERVICE_PORT_HTTPS=443
KUBERNETES_SERVICE_PORT=443
HOSTNAME=ubuntupod
color=green
PWD=/
HOME=/root
KUBERNETES_PORT_443_TCP=tcp://10.96.0.1:443
key=value
SHLVL=1
KUBERNETES_PORT_443_TCP_PROTO=tcp
KUBERNETES_PORT_443_TCP_ADDR=10.96.0.1
KUBERNETES_SERVICE_HOST=10.96.0.1
KUBERNETES_PORT=tcp://10.96.0.1:443
KUBERNETES_PORT_443_TCP_PORT=443
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
_=/usr/bin/env

# create a modified configmap with color=red, apply it
sysuser@ubuntuprod:~/git/ldk/k8s/08-configmaps (master -> origin/master)$ kubectl delete configmap/colorcm-properties && sleep 1 && kubectl create configmap colorcm-properties --from-env-file=colorcm-modified.properties && sleep 1 && echo "--CONFIG MAP--" && kubectl get configmap -o wide && echo "--DESCRIBE--" && kubectl describe configmap/colorcm-properties
configmap "colorcm-properties" deleted from myns namespace
configmap/colorcm-properties created
--CONFIG MAP--
NAME                 DATA   AGE
colorcm-properties   2      1s
kube-root-ca.crt     1      44h
--DESCRIBE--
Name:         colorcm-properties
Namespace:    myns
Labels:       <none>
Annotations:  <none>

Data
====
color:
----
red

key:
----
value


BinaryData
====

Events:  <none>

# recycle ubuntupod
sysuser@ubuntuprod:~/git/ldk/k8s/08-configmaps (master -> origin/master)$ kubectl delete -f ubuntupod.yaml --now && sleep 2 && kubectl apply -f ubuntupod-colorcm-properties.yaml && sleep 10 && echo "--PODS--" && kubectl get pods -o wide && echo "--LOGS--" && kubectl logs pod/ubuntupod

# output
pod "ubuntupod" deleted from myns namespace
pod/ubuntupod created
--PODS--
NAME        READY   STATUS    RESTARTS   AGE   IP             NODE         NOMINATED NODE   READINESS GATES
ubuntupod   1/1     Running   0          10s   10.244.1.142   klc-worker   <none>           <none>
--LOGS--
KUBERNETES_SERVICE_PORT_HTTPS=443
KUBERNETES_SERVICE_PORT=443
HOSTNAME=ubuntupod
color=red
PWD=/
HOME=/root
KUBERNETES_PORT_443_TCP=tcp://10.96.0.1:443
key=value
SHLVL=1
KUBERNETES_PORT_443_TCP_PROTO=tcp
KUBERNETES_PORT_443_TCP_ADDR=10.96.0.1
KUBERNETES_SERVICE_HOST=10.96.0.1
KUBERNETES_PORT=tcp://10.96.0.1:443
KUBERNETES_PORT_443_TCP_PORT=443
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
_=/usr/bin/env

# we want to make an immutable version of the same configmap. we will first get the yaml of the configmap, tee it to a file and add the necessary properties
sysuser@ubuntuprod:~/git/ldk/k8s/08-configmaps (master -> origin/master)$ kubectl get configmap/colorcm-properties -o yaml | tee colorcm-properties-immutable.yaml

# output
apiVersion: v1
data:
  color: red
  key: value
kind: ConfigMap
metadata:
  creationTimestamp: "2026-06-22T10:07:57Z"
  name: colorcm-properties
  namespace: myns
  resourceVersion: "247909"
  uid: a24c1dd0-1dcc-4f49-acd7-d24903973ad1

# edit the yaml file manually and apply it, and then get the configmap and describe it
sysuser@ubuntuprod:~/git/ldk/k8s/08-configmaps (master -> origin/master)$ kubectl apply -f colorcm-properties-immutable.yaml && sleep 1 && echo "--CONFIG MAP--" && kubectl get configmap -o wide && echo "--DESCRIBE--" && kubectl describe configmap/colorcm-properties

# output
Warning: resource configmaps/colorcm-properties is missing the kubectl.kubernetes.io/last-applied-configuration annotation which is required by kubectl apply. kubectl apply should only be used on resources created declaratively by either kubectl create --save-config or kubectl apply. The missing annotation will be patched automatically.
configmap/colorcm-properties configured
--CONFIG MAP--
NAME                 DATA   AGE
colorcm-properties   2      7m7s
kube-root-ca.crt     1      44h
--DESCRIBE--
Name:         colorcm-properties
Namespace:    myns
Labels:       <none>
Annotations:  <none>

Data
====
color:
----
purple

key:
----
value


BinaryData
====

Events:  <none>

# recycle ubuntupod
sysuser@ubuntuprod:~/git/ldk/k8s/08-configmaps (master -> origin/master)$ kubectl delete -f ubuntupod.yaml --now && sleep 2 && kubectl apply -f ubuntupod-colorcm-properties.yaml && sleep 10 && echo "--PODS--" && kubectl get pods -o wide && echo "--LOGS--" && kubectl logs pod/ubuntupod

# output
pod "ubuntupod" deleted from myns namespace
pod/ubuntupod created
--PODS--
NAME        READY   STATUS    RESTARTS   AGE   IP             NODE         NOMINATED NODE   READINESS GATES
ubuntupod   1/1     Running   0          10s   10.244.1.143   klc-worker   <none>           <none>
--LOGS--
KUBERNETES_SERVICE_PORT_HTTPS=443
KUBERNETES_SERVICE_PORT=443
HOSTNAME=ubuntupod
color=purple
PWD=/
HOME=/root
KUBERNETES_PORT_443_TCP=tcp://10.96.0.1:443
key=value
SHLVL=1
KUBERNETES_PORT_443_TCP_PROTO=tcp
KUBERNETES_PORT_443_TCP_ADDR=10.96.0.1
KUBERNETES_SERVICE_HOST=10.96.0.1
KUBERNETES_PORT=tcp://10.96.0.1:443
KUBERNETES_PORT_443_TCP_PORT=443
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
_=/usr/bin/env

# create a modified configmap file (colorcm-properties-immutable2.yaml and apply it. this will fail 
sysuser@ubuntuprod:~/git/ldk/k8s/08-configmaps (master -> origin/master)$ kubectl apply -f colorcm-properties-immutable2.yaml

# output
The ConfigMap "colorcm-properties" is invalid: data: Forbidden: field is immutable when `immutable` is set
