apiVersion: v1
data:
  color: purple
  key: value
immutable: true
kind: ConfigMap
metadata:
  creationTimestamp: "2026-06-22T10:07:57Z"
  name: colorcm-properties
  namespace: myns
  resourceVersion: "247909"
  uid: a24c1dd0-1dcc-4f49-acd7-d24903973ad1
