apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginxwebdep
    env: dev
  name: dev-finance-nginxwebdep-v1
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginxwebdep
    env: dev
status:
  loadBalancer: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginxwebdep
    env: dev
  name: dev-finance-nginxwebdep-v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginxwebdep
      env: dev
  strategy: {}
  template:
    metadata:
      labels:
        app: nginxwebdep
        env: dev
    spec:
      containers:
      - image: nginx
        name: nginx
        ports:
        - containerPort: 80
        resources: {}
status: {}
