# create a base nginxpod yaml and make a copy of it. 
sysuser@ubuntuprod:~/git/ldk/k8s/15-scheduling-nodename (master -> origin/master)$ kubectl run nginxpod --image=nginx --dry-run=client -o yaml | tee nginxpod.yaml && cp nginxpod.yaml nginxpod-custom-scheduler.yaml

# output
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginxpod
  name: nginxpod
spec:
  containers:
  - image: nginx
    name: nginxpod
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}

# get info on schedulerName
sysuser@ubuntuprod:~/git/ldk/k8s/15-scheduling-nodename (master -> origin/master)$ kubectl explain pod.spec | grep scheduler

# output
schedulerName <string>
If specified, the pod will be dispatched by specified scheduler. If not specified, the pod will be dispatched by default scheduler.

# edit nginxpod-custom-scheduler.yaml and add a custom scheduler and apply it. 
sysuser@ubuntuprod:~/git/ldk/k8s/15-scheduling-nodename (master -> origin/master)$ kubectl apply -f nginxpod-custom-scheduler.yaml && sleep 2 && echo "---PODS---" && kubectl get pods -o wide

# output
pod/nginxpod created
---PODS---
NAME       READY   STATUS    RESTARTS   AGE   IP       NODE     NOMINATED NODE   READINESS GATES
nginxpod   0/1     Pending   0          2s    <none>   <none>   <none>           <none>

# clone the repo for the custom scheduler 
sysuser@ubuntuprod:~/git$ git clone https://github.com/spurin/simple-kubernetes-scheduler-example.git
Cloning into 'simple-kubernetes-scheduler-example'...
remote: Enumerating objects: 6, done.
remote: Counting objects: 100% (6/6), done.
remote: Compressing objects: 100% (5/5), done.
remote: Total 6 (delta 0), reused 3 (delta 0), pack-reused 0 (from 0)
Receiving objects: 100% (6/6), done.

# cd into the directory and run the script
sysuser@ubuntuprod:~/git/simple-kubernetes-scheduler-example (main -> origin/main)$ ./my-scheduler.sh 
🚀 Starting the custom scheduler...
🎯 Attempting to bind the pod nginxpod in namespace myns to node klc-worker2
🎉 Successfully bound the pod nginxpod to node klc-worker2
^C

# get pods
sysuser@ubuntuprod:~/git/ldk/k8s/15-scheduling-nodename (master -> origin/master)$ kubectl get pods -o wide

# output
NAME       READY   STATUS    RESTARTS   AGE     IP           NODE          NOMINATED NODE   READINESS GATES
nginxpod   1/1     Running   0          2m48s   10.244.2.7   klc-worker2   <none>           <none>

# make a copy of the base pod yaml
sysuser@ubuntuprod:~/git/ldk/k8s/15-scheduling-nodename (master -> origin/master)$ cp nginxpod.yaml nginxpod-nodename.yaml

# add node name and apply it. delete the previous or change the name of the pod in the new yaml file. 
sysuser@ubuntuprod:~/git/ldk/k8s/15-scheduling-nodename (master -> origin/master)$ kubectl apply -f nginxpod-nodename.yaml

# output
pod/nginxpod-nodename created

sysuser@ubuntuprod:~/git/ldk/k8s/15-scheduling-nodename (master -> origin/master)$ kubectl get pods -o wide

# output
NAME                READY   STATUS    RESTARTS   AGE     IP           NODE          NOMINATED NODE   READINESS GATES
nginxpod            1/1     Running   0          7m51s   10.244.2.7   klc-worker2   <none>           <none>
nginxpod-nodename   1/1     Running   0          9s      10.244.1.4   klc-worker    <none>           <none>