apiVersion: v1
kind: Pod
metadata:
  labels:
    run: ubuntupod
  name: ubuntupod
spec:
  containers:
  - args:
    - sleeep # arg with typo
    - infinity
    image: ubuntu
    name: ubuntupod
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
