apiVersion: v1
kind: Pod
metadata:
  labels:
    run: ubuntupod
  name: ubuntupod
spec:
  containers:
  - args:
    - /bin/sh
    - -c
    - for i in $(seq 0 1 1000000); do echo "ubuntucontainer1 $i"; sleep 0.1; done
    image: ubuntu
    name: ubuntucontainer1
    resources: {}
  - args:
    - /bin/sh
    - -c
    - sleep 15; for i in $(seq 0 1 1000000); do echo "ubuntucontainer2 $i"; sleep 0.1; done
    image: ubuntu
    name: ubuntucontainer2
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
