apiVersion: v1
kind: Pod
metadata:
  labels:
    run: ubuntupod
  name: ubuntupod
spec:
  containers:
  - args:
    - /bin/sh
    - -c
    - touch /running; ps -p 1 -o lstart=; while [ -f /running ]; do sleep 1; done
    image: ubuntu
    name: ubuntupod
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
