apiVersion: v1
kind: Pod
metadata:
  labels:
    run: ubuntupod
  name: ubuntupod
spec:
  # custom scheduler that does not exist. enable this to make the pod stay in pending state
  # schedulerName: none
  containers:
  - args:
    - sleep
    - infinity
    # use this image to break the container creation phase
    # image: ubuntuX
    # use this image to generate imagepullbackoff state
    # image: ubuntux
    image: ubuntu
    name: ubuntupod
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
