apiVersion: v1
kind: Pod
metadata:
  labels:
    run: ubuntupod
  name: ubuntupod
spec:
  containers:
  - image: ubuntu
    name: ubuntupod
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
