# add helm prometheus helm repo
sysuser@ubuntudev:~/git/ldk/k8s/30-prometheus-grafana (master -> origin/master)$ helm repo add prometheus-community https://prometheus-community.github.io/helm-charts

# output
"prometheus-community" has been added to your repositories

# update helm repo
sysuser@ubuntudev:~/git/ldk/k8s/30-prometheus-grafana (master -> origin/master)$ helm repo update

# output
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "metrics-server" chart repository
...Successfully got an update from the "prometheus-community" chart repository
Update Complete. ⎈Happy Helming!⎈

# pull prometheus
sysuser@ubuntudev:~/git/ldk/k8s/30-prometheus-grafana (master -> origin/master)$ helm pull prometheus-community/prometheus --untar

# run tree
sysuser@ubuntudev:~/git/ldk/k8s/30-prometheus-grafana (master -> origin/master)$ tree

# output
.
├── 30-prometheus-grafana-commands.ini
└── prometheus
    ├── Chart.lock
    ├── charts
    │   ├── alertmanager
    │   │   ├── Chart.yaml
    │   │   ├── README.md
    │   │   ├── templates
    │   │   │   ├── configmap.yaml
    │   │   │   ├── _helpers.tpl
    │   │   │   ├── httproute.yaml
    │   │   │   ├── ingressperreplica.yaml
    │   │   │   ├── ingress.yaml
    │   │   │   ├── NOTES.txt
    │   │   │   ├── pdb.yaml
    │   │   │   ├── serviceaccount.yaml
    │   │   │   ├── servicemonitor.yaml
    │   │   │   ├── serviceperreplica.yaml
    │   │   │   ├── services.yaml
    │   │   │   ├── statefulset.yaml
    │   │   │   ├── tests
    │   │   │   │   └── test-connection.yaml
    │   │   │   └── vpa.yaml
    │   │   ├── values.schema.json
    │   │   └── values.yaml
    │   ├── kube-state-metrics
    │   │   ├── Chart.yaml
    │   │   ├── README.md
    │   │   ├── templates
    │   │   │   ├── ciliumnetworkpolicy.yaml
    │   │   │   ├── clusterrolebinding.yaml
    │   │   │   ├── crs-configmap.yaml
    │   │   │   ├── deployment.yaml
    │   │   │   ├── extra-manifests.yaml
    │   │   │   ├── _helpers.tpl
    │   │   │   ├── kubeconfig-secret.yaml
    │   │   │   ├── networkpolicy.yaml
    │   │   │   ├── NOTES.txt
    │   │   │   ├── pdb.yaml
    │   │   │   ├── rbac-configmap.yaml
    │   │   │   ├── rolebinding.yaml
    │   │   │   ├── role.yaml
    │   │   │   ├── scrapeconfig.yaml
    │   │   │   ├── serviceaccount.yaml
    │   │   │   ├── servicemonitor.yaml
    │   │   │   ├── service.yaml
    │   │   │   ├── stsdiscovery-rolebinding.yaml
    │   │   │   ├── stsdiscovery-role.yaml
    │   │   │   └── verticalpodautoscaler.yaml
    │   │   └── values.yaml
    │   ├── prometheus-node-exporter
    │   │   ├── Chart.yaml
    │   │   ├── README.md
    │   │   ├── templates
    │   │   │   ├── clusterrolebinding.yaml
    │   │   │   ├── clusterrole.yaml
    │   │   │   ├── daemonset.yaml
    │   │   │   ├── endpoints.yaml
    │   │   │   ├── extra-manifests.yaml
    │   │   │   ├── _helpers.tpl
    │   │   │   ├── networkpolicy.yaml
    │   │   │   ├── NOTES.txt
    │   │   │   ├── podmonitor.yaml
    │   │   │   ├── rbac-configmap.yaml
    │   │   │   ├── serviceaccount.yaml
    │   │   │   ├── servicemonitor.yaml
    │   │   │   ├── service.yaml
    │   │   │   └── verticalpodautoscaler.yaml
    │   │   └── values.yaml
    │   └── prometheus-pushgateway
    │       ├── Chart.yaml
    │       ├── README.md
    │       ├── templates
    │       │   ├── deployment.yaml
    │       │   ├── extra-manifests.yaml
    │       │   ├── _helpers.tpl
    │       │   ├── httproute.yaml
    │       │   ├── ingress.yaml
    │       │   ├── networkpolicy.yaml
    │       │   ├── NOTES.txt
    │       │   ├── pdb.yaml
    │       │   ├── pushgateway-pvc.yaml
    │       │   ├── secret.yaml
    │       │   ├── serviceaccount.yaml
    │       │   ├── servicemonitor.yaml
    │       │   ├── service.yaml
    │       │   └── statefulset.yaml
    │       └── values.yaml
    ├── Chart.yaml
    ├── README.md
    ├── templates
    │   ├── clusterrolebinding.yaml
    │   ├── clusterrole.yaml
    │   ├── cm.yaml
    │   ├── deploy.yaml
    │   ├── extra-manifests.yaml
    │   ├── headless-svc.yaml
    │   ├── _helpers.tpl
    │   ├── httproute.yaml
    │   ├── ingress.yaml
    │   ├── network-policy.yaml
    │   ├── NOTES.txt
    │   ├── pdb.yaml
    │   ├── pvc.yaml
    │   ├── rolebinding.yaml
    │   ├── serviceaccount.yaml
    │   ├── service.yaml
    │   └── vpa.yaml
    ├── values.schema.json
    └── values.yaml

13 directories, 98 files

# install prometheus as myprom
sysuser@ubuntudev:~/git/ldk/k8s/30-prometheus-grafana (master -> origin/master)$ helm install myprom ./prometheus

# output
NAME: myprom
LAST DEPLOYED: Fri Jul 10 17:05:40 2026
NAMESPACE: default
STATUS: deployed
REVISION: 1
DESCRIPTION: Install complete
TEST SUITE: None
NOTES:
The Prometheus server can be accessed via port 80 on the following DNS name from within your cluster:
myprom-prometheus-server.default.svc.cluster.local


Get the Prometheus server URL by running these commands in the same shell:
  export POD_NAME=$(kubectl get pods --namespace default -l "app.kubernetes.io/name=prometheus,app.kubernetes.io/instance=myprom" -o jsonpath="{.items[0].metadata.name}")
  kubectl --namespace default port-forward $POD_NAME 9090

Prometheus alertmanager can be accessed via port 9093 on the following DNS name from within your cluster:
myprom-alertmanager.default.svc.cluster.local


Get the Alertmanager URL by running these commands in the same shell:
  export POD_NAME=$(kubectl get pods --namespace default -l "app.kubernetes.io/name=alertmanager,app.kubernetes.io/instance=myprom" -o jsonpath="{.items[0].metadata.name}")
  kubectl --namespace default port-forward $POD_NAME 9090

Prometheus Pushgateway can be accessed via port 9091 on the following DNS name from within your cluster:
myprom-prometheus-pushgateway.default.svc.cluster.local


Get the Pushgateway URL by running these commands in the same shell:
  export POD_NAME=$(kubectl get pods --namespace default -l "app.kubernetes.io/name=prometheus-pushgateway,app.kubernetes.io/instance=myprom" -o jsonpath="{.items[0].metadata.name}")
  kubectl --namespace default port-forward $POD_NAME 9091

For more information on running Prometheus, visit:
https://prometheus.io/

# get all resources. lot of myprom resources. 
sysuser@ubuntudev:~/git/ldk/k8s/30-prometheus-grafana (master -> origin/master)$ kubectl get all -A -o wide > all-resources.txt

### NOTE ###

# prometheus instructions say to forward to 9090, but portainer runs on 9090. if portainer is running, forward to 9093 instead, but confirm first.

# run the following to see if there is any process running on 9090
sysuser@ubuntudev:~/git/ldk/k8s/30-prometheus-grafana (master -> origin/master)$ sudo ss -tulp | grep :9090

# output
[sudo] password for sysuser: 
tcp   LISTEN 0      4096         0.0.0.0:9090        0.0.0.0:*    users:(("docker-proxy",pid=3051,fd=8))   
tcp   LISTEN 0      4096            [::]:9090           [::]:*    users:(("docker-proxy",pid=3061,fd=8)) 

# if the output is similar to above output, run the following command to check docker containers.
sysuser@ubuntudev:~/git/ldk/k8s/30-prometheus-grafana (master -> origin/master)$ docker ps | grep -E 'prometheus|9090'
6f2bd55c2b42   portainer/portainer-ce:sts      "/portainer"             3 weeks ago    Up 3 hours   0.0.0.0:8000->8000/tcp, [::]:8000->8000/tcp, 0.0.0.0:9000->9000/tcp, [::]:9000->9000/tcp, 0.0.0.0:9090->9090/tcp, [::]:9090->9090/tcp, 0.0.0.0:9443->9443/tcp, [::]:9443->9443/tcp   portainer

# if so, run the following commands. this will get the pod that is running prometheus server and store it in POD_NAME
sysuser@ubuntudev:~/git/ldk/k8s/30-prometheus-grafana (master -> origin/master)$ export POD_NAME=$(kubectl get pods --namespace default -l "app.kubernetes.io/name=prometheus,app.kubernetes.io/instance=myprom" -o jsonpath="{.items[0].metadata.name}") && echo $POD_NAME

# output
myprom-prometheus-server-6ddf69cc9d-l5dvn

# port forward POD_NAME to 9093. access http://localhost:9093 for prometheus
sysuser@ubuntudev:~/git/ldk/k8s/30-prometheus-grafana (master -> origin/master)$ kubectl --namespace default port-forward $POD_NAME 9093:9090

# we will install the entire stack (prometheus and grafana). so uninstall this for now.
sysuser@ubuntudev:~/git/ldk/k8s/30-prometheus-grafana (master -> origin/master)$ helm uninstall myprom

# output
release "myprom" uninstalled

# pull the stack
sysuser@ubuntudev:~/git/ldk/k8s/30-prometheus-grafana (master -> origin/master)$ helm pull prometheus-community/kube-prometheus-stack --untar

# install the stack
sysuser@ubuntudev:~/git/ldk/k8s/30-prometheus-grafana (master -> origin/master)$ helm install myprom ./kube-prometheus-stack

# output
NAME: myprom
LAST DEPLOYED: Fri Jul 10 18:20:15 2026
NAMESPACE: default
STATUS: deployed
REVISION: 1
DESCRIPTION: Install complete
TEST SUITE: None
NOTES:
kube-prometheus-stack has been installed. Check its status by running:
  kubectl --namespace default get pods -l "release=myprom"

Get Grafana 'admin' user password by running:

  kubectl --namespace default get secrets myprom-grafana -o jsonpath="{.data.admin-password}" | base64 -d ; echo

Access Grafana local instance:

  export POD_NAME=$(kubectl --namespace default get pod -l "app.kubernetes.io/name=grafana,app.kubernetes.io/instance=myprom" -oname)
  kubectl --namespace default port-forward $POD_NAME 3000

Get your grafana admin user password by running:

  kubectl get secret --namespace default -l app.kubernetes.io/component=admin-secret -o jsonpath="{.items[0].data.admin-password}" | base64 --decode ; echo


Visit https://github.com/prometheus-operator/kube-prometheus for instructions on how to create & configure Alertmanager and Prometheus instances using the Operator.

# get all resources
sysuser@ubuntudev:~/git/ldk/k8s/30-prometheus-grafana (master -> origin/master)$ kubectl get all -A > get-all-resources-stack.txt

# get grafana admin password
sysuser@ubuntudev:~/git/ldk/k8s/30-prometheus-grafana (master -> origin/master)$ kubectl --namespace default get secrets myprom-grafana -o jsonpath="{.data.admin-password}" | base64 -d ; echo

# output
tDefsL4VsYvleC2hr11ZeOvHGpZk46kpSPnSdUD0

# get the grafana pod
sysuser@ubuntudev:~/git/ldk/k8s/30-prometheus-grafana (master -> origin/master)$ export POD_NAME=$(kubectl --namespace default get pod -l "app.kubernetes.io/name=grafana,app.kubernetes.io/instance=myprom" -oname) ; echo $POD_NAME

# output
pod/myprom-grafana-59945674bc-klxm7

# port forward the traffic
sysuser@ubuntudev:~/git/ldk/k8s/30-prometheus-grafana (master -> origin/master)$ kubectl --namespace default port-forward $POD_NAME 3000

# output
Forwarding from 127.0.0.1:3000 -> 3000
Forwarding from [::1]:3000 -> 3000

# access http://localhost:3000 and use admin/tDefsL4VsYvleC2hr11ZeOvHGpZk46kpSPnSdUD0 to access grafana

# to access prometheus
sysuser@ubuntudev:~/git/ldk/k8s/30-prometheus-grafana (master -> origin/master)$ kubectl port-forward svc/myprom-kube-prometheus-sta-prometheus 9093:9090

# output
Forwarding from 127.0.0.1:9093 -> 9090
Forwarding from [::1]:9093 -> 9090
Handling connection for 9093
Handling connection for 9093
Handling connection for 9093

# create pods, so we can gather stats
sysuser@ubuntudev:~/git/ldk/k8s/30-prometheus-grafana (master -> origin/master)$ for i in {1..10}; do kubectl run nginx-${i} --image=nginx; sleep 30; done

# output
pod/nginx-1 created
pod/nginx-2 created
pod/nginx-3 created
pod/nginx-4 created
pod/nginx-5 created
pod/nginx-6 created
pod/nginx-7 created
pod/nginx-8 created
pod/nginx-9 created
pod/nginx-10 created

# in prometheus, use the following query
sum by (namespace) (kube_pod_ips)

# for grafana, the id of the dashboard is 15759, 15757

# clean up
sysuser@ubuntudev:~/git/ldk/k8s/30-prometheus-grafana (master -> origin/master)$ helm uninstall myprom

# output
release "myprom" uninstalled

# delete the pods
sysuser@ubuntudev:~/git/ldk/k8s/30-prometheus-grafana (master -> origin/master)$ for i in {1..10}; do kubectl delete pod/nginx-${i}; done

# output
pod "nginx-1" deleted from default namespace
pod "nginx-2" deleted from default namespace
pod "nginx-3" deleted from default namespace
pod "nginx-4" deleted from default namespace
pod "nginx-5" deleted from default namespace
pod "nginx-6" deleted from default namespace
pod "nginx-7" deleted from default namespace
pod "nginx-8" deleted from default namespace
pod "nginx-9" deleted from default namespace
pod "nginx-10" deleted from default namespace
