# check out local branch called dev and set upstream to origin/dev

git checkout -b dev origin/dev

#### delete commit history ####

# set the local username and email from the root of the git repository
git config user.name "Your Repo Name"
git config user.email "your-repo-email@example.com"

# from the root of the git repository, run the following. this should retrn the new username and email for the local gitconfig inside the repository
git config --local --list

# checkout the master branch and pull all the changes. make sure there are no local changes.
git checkout master && git pull

# get the commit history of the master branch
git log --oneline

# output
sysuser@ubuntuprod:~/git/test (master -> origin/master)$ git log --oneline
581515d (HEAD -> master, origin/master, origin/HEAD) test commit 4
ddf7932 test commit 3
58da784 test commit 2
dbad5ef test commit 1
3b0d0e7 Create README.md
369a418 Create README.md

# create an orphan branch without any history
sysuser@ubuntuprod:~/git/test (master -> origin/master)$ git checkout --orphan latest

# output
Switched to a new branch 'latest'
sysuser@ubuntuprod:~/git/test (latest)$

# add all files
git add -A

# initial commit
git commit -m "Initial commit (history reset)"

# delete master
git branch -D master

# output
Deleted branch master (was 581515d).

# rename current branch to master
git branch -m master

# push to remote master
git push -f origin master

# there is no origin at this point
sysuser@ubuntuprod:~/git/test (master)$ git status

# output
On branch master
nothing to commit, working tree clean

# set upstream to origin/master
git branch -u origin/master master

# run git status
sysuser@ubuntuprod:~/git/test (master -> origin/master)$ git status

# output
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean

# add alias to git config
git config --global user.name "RC" && \
git config --global user.email "alinuxuser@fastmail.com" && \
git config --global alias.acp '!f() { git add -A && git commit -m "$@" && git push; }; f' && \
git config --global alias.aamd '!f() { git add -A && git commit --amend --no-edit; }; f' && \
git config --global alias.ac '!f() { git add -A && git commit -m "$@"; }; f'

git config --global alias.sqmaster '!f() { msg="${*:-Squash merge dev}"; git checkout master && git fetch && git reset --hard origin/master && git read-tree --reset -u dev && git commit -m "$msg" --allow-empty && git push --force && git checkout dev; }; f'
