# tool for managing micro servers. helper for microservices. 
# data plane (side car proxy pattern, ex- istio) and control plane, acts as a management hub. 
# mutual tls. 
# service mesh interface - common interface to manage service mesh capabilities
