# startup - has the app finished starting?; liveness probe - should kubernetes restart the container?; readiness probe - should the pod receive traffic?

# git repo link: https://github.com/spurin/readiness-liveness-startup-probe-api/blob/main/template.yaml

# save the template as ~/git/ldk/k8s/12-startup-liveness-readiness-probes/probe-demo.yaml

kubectl apply -f probe-demo.yaml; watch -n 0 'kubectl describe pod/probe-demo | sed '0,/Events:/d' | tail -20; echo; kubectl logs pod/probe-demo | tail -20; echo; kubectl get pod/probe-demo -o wide'