apiVersion: v1
kind: Service
metadata:
  labels:
    app: myensvc
  name: myensvc
spec:
  externalName: nginxdepblue.myns.svc.cluster.local
  selector:
    app: myensvc
  type: ExternalName
status:
  loadBalancer: {}
