apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginxdepred
  name: nginxdepred
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginxdepred
  strategy: {}
  template:
    metadata:
      labels:
        app: nginxdepred
    spec:
      containers:
      - image: spurin/nginx-red
        name: nginx-red
        ports:
        - containerPort: 8080
        resources: {}
status: {}
