apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginxdepblue
  name: nginxdepblue
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 80
  selector:
    app: nginxdepblue
status:
  loadBalancer: {}
