# daemon sets do not have a spec in kubernetes. it is best to create a deployment and change it to a daemon set. 

# create a deployment to run a while loop in alpine linux
sysuser@ubuntuprod:~/git/ldk/k8s/04-daemonsets (master -> origin/master)$ kubectl create deployment loggerdep --image=alpine -n myns -o yaml --dry-run=client -- /bin/sh -c 'while true; do date +"%Y-%m-%d-%H:%M:%S - Hello from $NODE_NAME"; sleep 30; done' | tee loggerdep.yaml

# output
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: loggerdep
  name: loggerdep
  namespace: myns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loggerdep
  strategy: {}
  template:
    metadata:
      labels:
        app: loggerdep
    spec:
      containers:
      - command:
        - /bin/sh
        - -c
        - while true; do date +"%Y-%m-%d-%H:%M:%S - Hello from $NODE_NAME"; sleep
          30; done
        image: alpine
        name: alpine
        resources: {}
status: {}

# apply the deployment
sysuser@ubuntuprod:~/git/ldk/k8s/04-daemonsets (master -> origin/master)$ kubectl apply -f loggerdep.yaml 

# output
deployment.apps/loggerdep created

# get the logs based on the label
sysuser@ubuntuprod:~/git/ldk/k8s/04-daemonsets (master -> origin/master)$ kubectl logs -l app=loggerdep

# output
# NODE_NAME doesnt exist yet, so its empty
2026-06-20-16:23:58 - Hello from 
2026-06-20-16:24:28 - Hello from

# get pod spec
sysuser@ubuntuprod:~/git/ldk/k8s/04-daemonsets (master -> origin/master)$ kubectl get pod/loggerdep-b65c4cb75-gjrjt -o yaml | tee loggerdep-b65c4cb75-gjrjt.yaml

# create a new deployment file, add the environment varialble and monitor the logs
sysuser@ubuntuprod:~/git/ldk/k8s/04-daemonsets (master -> origin/master)$ kubectl replace --force=true -f loggerdep-env.yaml && kubectl rollout status deployment/loggerdep && kubectl logs -l app=loggerdep

# output. node name is now printed - 2026-06-20-16:32:38 - Hello from klc-worker2
deployment.apps "loggerdep" deleted from myns namespace
deployment.apps/loggerdep replaced
Waiting for deployment "loggerdep" rollout to finish: 0 out of 1 new replicas have been updated...
Waiting for deployment "loggerdep" rollout to finish: 0 of 1 updated replicas are available...
deployment "loggerdep" successfully rolled out
2026-06-20-16:32:38 - Hello from klc-worker2
2026-06-20-16:27:58 - Hello from 
2026-06-20-16:28:28 - Hello from 
2026-06-20-16:28:58 - Hello from 
2026-06-20-16:29:28 - Hello from 
2026-06-20-16:29:58 - Hello from 
2026-06-20-16:30:28 - Hello from 
2026-06-20-16:30:58 - Hello from 
2026-06-20-16:31:28 - Hello from 
2026-06-20-16:31:58 - Hello from 
2026-06-20-16:32:28 - Hello from 

# we will delete this deployment and convert it into a daemonset
sysuser@ubuntuprod:~/git/ldk/k8s/04-daemonsets (master -> origin/master)$ kubectl apply -f loggerds.yaml 

# output
daemonset.apps/loggerds created

# get daemonsets, pods and logs. pods are automatically created on all nodes where it can run. if it is not running on control plane, its because something is preventing it from running on it, like a taint
sysuser@ubuntuprod:~/git/ldk/k8s/04-daemonsets (master -> origin/master)$ kubectl get daemonset -o wide && kubectl get pods -o wide && kubectl logs -l app=loggerds

# output
NAME       DESIRED   CURRENT   READY   UP-TO-DATE   AVAILABLE   NODE SELECTOR   AGE    CONTAINERS   IMAGES   SELECTOR
loggerds   2         2         2       2            2           <none>          2m8s   alpine       alpine   app=loggerds
NAME             READY   STATUS    RESTARTS   AGE    IP            NODE          NOMINATED NODE   READINESS GATES
loggerds-s87ft   1/1     Running   0          2m7s   10.244.2.39   klc-worker2   <none>           <none>
loggerds-zk88k   1/1     Running   0          2m7s   10.244.1.37   klc-worker    <none>           <none>
2026-06-20-16:44:46 - Hello from klc-worker2
2026-06-20-16:45:16 - Hello from klc-worker2
2026-06-20-16:45:46 - Hello from klc-worker2
2026-06-20-16:46:16 - Hello from klc-worker2
2026-06-20-16:46:46 - Hello from klc-worker2
2026-06-20-16:44:45 - Hello from klc-worker
2026-06-20-16:45:15 - Hello from klc-worker
2026-06-20-16:45:45 - Hello from klc-worker
2026-06-20-16:46:15 - Hello from klc-worker
2026-06-20-16:46:45 - Hello from klc-worker

# get the taint on the control plane
sysuser@ubuntuprod:~/git/ldk/k8s/04-daemonsets (master -> origin/master)$ kubectl describe node klc-control-plane | grep -i taint
Taints:             node-role.kubernetes.io/control-plane:NoSchedule
