apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: loggerdep
  name: loggerdep
  namespace: myns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loggerdep
  strategy: {}
  template:
    metadata:
      labels:
        app: loggerdep
    spec:
      containers:
      - command:
        - /bin/sh
        - -c
        - while true; do date +"%Y-%m-%d-%H:%M:%S - Hello from $NODE_NAME"; sleep
          30; done
        image: alpine
        name: alpine
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName # refer to /home/sysuser/git/ldk/k8s/04-daemonsets/loggerdep-b65c4cb75-gjrjt.yaml
        resources: {}
status: {}
