# configure shared folder vmshare as a mount
sudo apt update

# install git, openssh server and client, kate, open-vm-tools, go, apache2-utils (for bcrypt)
sudo apt install -y open-vm-tools open-vm-tools-desktop git-all openssh-client openssh-server kate golang-go apache2-utils npm curl tree snapd

# snap
sudo systemctl enable --now snapd

# install hugo
sudo snap install hugo --channel=extended/stable

# formatting plugin
sysuser@ubuntuprod:~/temp$ sudo npm install -g prettier


# check status of the ssh server
sudo systemctl status ssh

# create base directories
mkdir -p ~/Templates ~/git ~/temp

# right click to add files
touch ~/Templates/"New Text File.txt";touch ~/Templates/"New ini File.ini";touch ~/Templates/"EmptyFile";touch ~/Templates/"New Yaml File.yaml"

# either this or add it via command line
sudo nano /etc/fstab
.host:/  /mnt/hgfs  fuse.vmhgfs-fuse  defaults,allow_other  0  0
ctrl+o -> Enter
ctrl+x

# command line approach
echo ".host:/  /mnt/hgfs  fuse.vmhgfs-fuse  defaults,allow_other  0  0" | sudo tee -a /etc/fstab

# create symlink to vmshare
ln -s /mnt/hgfs/vmshare ~/vmshare

# install kind
https://kind.sigs.k8s.io/docs/user/quick-start/#installing-with-a-package-manager

# install kubectl
https://kubernetes.io/docs/tasks/tools/install-kubectl-linux/

# add alias to git config
git config --global user.name "Ravi Chandra" && \
git config --global user.email "rch@fast.com" && \
git config --global alias.acp '!f() { git add -A && git commit -m "$@" && git push; }; f' && \
git config --global alias.aamd '!f() { git add -A && git commit --amend --no-edit; }; f' && \
git config --global alias.ac '!f() { git add -A && git commit -m "$@"; }; f'

# add alias to .bashrc
printf "\nalias mytemp='cd ~/temp'\nalias ldk='cd ~/git/docker/kcna'\nalias vmshare='cd ~/vmshare'\nalias opengit='cd ~/git'\n" | sudo tee -a ~/.bashrc
source ~/.bashrc

# install helm
curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-4 | bash

# install yq
sysuser@ubuntuprod:~/git/ldk/kcna/kubernetes/prometheus$ sudo apt install -y yq

# install , needed for argocd password
sysuser@ubuntuprod:~/git/ldk/kcna/kubernetes/argocd$ sudo apt-get install -y apache2-utils

# install yq and assign it execute permission
sudo wget -qO /usr/local/bin/yq https://github.com/mikefarah/yq/releases/latest/download/yq_linux_$(dpkg --print-architecture) && sudo chmod +x /usr/local/bin/yq

# kate uuid no new line
Quick Fix: Edit the Built-in "Insert UUID" Tool

Go to Tools → External Tools → Manage Tools... (or Configure Kate... → Plugins → External Tools and click the configure button).
In the list of tools, find Insert UUID and click Edit.
Change these settings:
Executable: printf
Arguments: %{UUID}
printf does not add a newline by default.

# add date insert into kate
Settings -> Configure Kate -> External Tools -> Add Tool -> insert details
Executable: date
Arguments: +"%b %d, %Y %A %I:%M:%S %p %Z"

#### wsl2 ubuntu ####

echo "/mnt/c/temp   /home/sysuser/mnthost   drvfs   defaults,bind   0 0" | sudo tee -a /etc/fstab
sysuser@PCI-FZ961B3:/mnt/c/git/gitlab.powercosts.io$ sudo systemctl daemon-reload
sysuser@PCI-FZ961B3:/mnt/c/git/gitlab.powercosts.io$ sudo mount -a
