# create kind cluster with metrics
bash ~/git/ldk/kind-cluster/create-kind-cluster-with-metrics.sh

# run the following command
sysuser@ubuntudev:~/git/ldk (master -> origin/master)$ bash ~/git/ldk/kind-cluster/create-kind-cluster-with-metrics.sh

# output
[+] Creating Kind cluster: klc using /home/sysuser/git/ldk/kind-cluster/klc.yaml
Creating cluster "klc" ...
 ✓ Ensuring node image (kindest-node-image-with-utils) 🖼
 ✓ Preparing nodes 📦 📦 📦  
 ✓ Writing configuration 📜 
 ✓ Starting control-plane 🕹️ 
 ✓ Installing CNI 🔌 
 ✓ Installing StorageClass 💾 
 ✓ Joining worker nodes 🚜 
Set kubectl context to "kind-klc"
You can now use your cluster with:

kubectl cluster-info --context kind-klc

Thanks for using kind! 😊
[+] Waiting for kube-system core pods to be ready...
pod/coredns-7d764666f9-dp2wl condition met
pod/coredns-7d764666f9-kpgll condition met
pod/etcd-klc-control-plane condition met
pod/kindnet-5fsgh condition met
pod/kindnet-hngfv condition met
pod/kindnet-mpg76 condition met
pod/kube-apiserver-klc-control-plane condition met
pod/kube-controller-manager-klc-control-plane condition met
pod/kube-proxy-lcxhz condition met
pod/kube-proxy-mpjmr condition met
pod/kube-proxy-zqxbr condition met
pod/kube-scheduler-klc-control-plane condition met
Release "metrics-server" does not exist. Installing it now.
NAME: metrics-server
LAST DEPLOYED: Sat Jul 11 06:56:51 2026
NAMESPACE: kube-system
STATUS: deployed
REVISION: 1
DESCRIPTION: Install complete
TEST SUITE: None
NOTES:
***********************************************************************
* Metrics Server                                                      *
***********************************************************************
  Chart version: 3.13.1
  App version:   0.8.1
  Image tag:     registry.k8s.io/metrics-server/metrics-server:v0.8.1
***********************************************************************
[+] Waiting for metrics-server to be available...
Waiting for deployment "metrics-server" rollout to finish: 0 of 1 updated replicas are available...
deployment "metrics-server" successfully rolled out

# create kind cluster without metrics
kind create cluster --config ~/git/ldk/kind-cluster/klc.yaml

# shell/exec into the control plane
docker exec -it klc-control-plane bash

# to delete cluster
kind delete cluster --name=klc

# stop kind containers
docker stop $(docker ps -q --filter "name=klc")

# to start kind containers
docker start $(docker ps -aq --filter "name=klc")

# port forward all traffic to 8001 on localhost
kubectl proxy --port=8001

# combine into one line to disown the process
sysuser@ubuntudev:~$ (kubectl proxy --port=8001 &); sleep 2; disown

# get the pid to kill the process if needed
sysuser@ubuntudev:~$ ps aux | grep 8001

### Cloud Provider KIND ###

# https://kind.sigs.k8s.io/docs/user/loadbalancer/
go install sigs.k8s.io/cloud-provider-kind@latest

# add to path
echo 'export PATH=$PATH:$HOME/go/bin' >> ~/.bashrc
source ~/.bashrc

# run this to detach the terminal
cloud-provider-kind --enable-lb-port-mapping > ~/go/bin/cloud-provider-kind.log 2>&1 &

# disown so that the terminal can be closed
disown

# ensure that the process is still running
sysuser@ubuntudev:~$ ps aux | grep cloud-provider-kind

# to stop the service
ps aux | grep cloud-provider-kind
kill <PID>