kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: klc
nodes:
    - role: control-plane
      image: kindest-node-image-with-utils
    - role: worker
      image: kindest-node-image-with-utils
    - role: worker
      image: kindest-node-image-with-utils
